<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GetMuxConsumerExport1_GetMuxConsumerHttp_Service" targetNamespace="urn:com.tcl.ace.tdm.getmux.ws.GetMuxConsumer/Binding" xmlns:Port_0="urn:com.tcl.ace.tdm.getmux.ws.GetMuxConsumer" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="urn:com.tcl.ace.tdm.getmux.ws.GetMuxConsumer/Binding">
  <wsdl:import namespace="urn:com.tcl.ace.tdm.getmux.ws.GetMuxConsumer" location="GetMuxConsumerWS.wsdl"/>
  <wsdl:binding name="GetMuxConsumerExport1_GetMuxConsumerHttpBinding" type="Port_0:GetMuxConsumer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getMuxInfo">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getMuxInfoFault">
        <soap:fault name="getMuxInfoFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="submitMuxDetailFailureResponse">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="submitMuxDetailFailureResponseFault">
        <soap:fault name="submitMuxDetailFailureResponseFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetMuxConsumerExport1_GetMuxConsumerHttpService">
    <wsdl:port name="GetMuxConsumerExport1_GetMuxConsumerHttpPort" binding="this:GetMuxConsumerExport1_GetMuxConsumerHttpBinding">
      <soap:address location="http://10.133.208.194/optimus-serviceactivation/api/ws/getmuxinfoasync.wsdl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>