<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TimeSlotsConsumptionExport1_TimeSlotsConsumptionHttp_Service" targetNamespace="com.tatacommunications.cramer.ace.tsSubmition.ws.TimeSlotsConsumption/Binding" xmlns:Port_0="com.tatacommunications.cramer.ace.tsSubmition.ws.TimeSlotsConsumption" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="com.tatacommunications.cramer.ace.tsSubmition.ws.TimeSlotsConsumption/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:import namespace="com.tatacommunications.cramer.ace.tsSubmition.ws.TimeSlotsConsumption" location="TSReservation.wsdl"/>
  <wsdl:binding name="TimeSlotsConsumptionExport1_TimeSlotsConsumptionHttpBinding" type="Port_0:TimeSlotsConsumption">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="setOpticalHandOffDetails">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="setOpticalHandOffDetailsFault">
        <soap:fault name="setOpticalHandOffDetailsFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="setElectricalHandOffDetails">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="setElectricalHandOffDetailsFault">
        <soap:fault name="setElectricalHandOffDetailsFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="submitTSSelectionFault">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="submitFault">
        <soap:fault name="submitFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TimeSlotsConsumptionExport1_TimeSlotsConsumptionHttpService">
    <wsdl:port name="TimeSlotsConsumptionExport1_TimeSlotsConsumptionHttpPort" binding="this:TimeSlotsConsumptionExport1_TimeSlotsConsumptionHttpBinding">
      <soap:address location="http://10.133.208.194/optimus-serviceactivation/api/ws/offnetdetails.wsdl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>