<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CreateOrderRequestInterfaceExport1_CreateOrderRequestInterfaceHttp_Service" targetNamespace="http://InstaCCLibrary/CreateOrderInterface" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://InstaCCLibrary/CreateOrderInterface" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:import namespace="http://InstaCCLibrary/CreateOrderInterface" location="CreateOrderRequestInterface.wsdl"/>
  <wsdl:binding name="CreateOrderRequestInterfaceExport1_CreateOrderRequestInterfaceHttpBinding" type="this:CreateOrderRequestInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="createOrder">
      <soap:operation soapAction=""/>
      <wsdl:input name="createOrderRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="createOrderResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CreateOrderRequestInterfaceExport1_CreateOrderRequestInterfaceHttpService">
    <wsdl:port name="CreateOrderRequestWSExport_CreateOrderRequestInterfaceHttpPort" binding="this:CreateOrderRequestInterfaceExport1_CreateOrderRequestInterfaceHttpBinding">
      <soap:address location="http://10.133.20.12:9080/AS.InstaCC-CreateOrderModuleWeb/sca/CreateOrderRequestWSExport"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>