<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GetHDCONFIGDetailsExport1_GetHDCONFIGDetailsHttp_Service" targetNamespace="http://ACEIAS_HDCONFIG_Module/GetHDCONFIGDetails" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://ACEIAS_HDCONFIG_Module/GetHDCONFIGDetails" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:import namespace="http://ACEIAS_HDCONFIG_Module/GetHDCONFIGDetails" location="GetHDCONFIGDetails.wsdl"/>
  <wsdl:binding name="GetHDCONFIGDetailsExport1_GetHDCONFIGDetailsHttpBinding" type="this:GetHDCONFIGDetails">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getHDCONFIGDetails">
      <soap:operation soapAction=""/>
      <wsdl:input name="getHDCONFIGDetailsRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getHDCONFIGDetailsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getHDCONFIGDetailsFault">
        <soap:fault name="getHDCONFIGDetailsFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="submitHDCONFIGFailureResponse">
      <soap:operation soapAction=""/>
      <wsdl:input name="submitHDCONFIGFailureResponseRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="submitHDCONFIGFailureResponseResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="submitHDCONFIGFailureResponseFault">
        <soap:fault name="submitHDCONFIGFailureResponseFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetHDCONFIGDetailsExport1_GetHDCONFIGDetailsHttpService">
    <wsdl:port name="GetHDCONFIGDetailsExport1_GetHDCONFIGDetailsHttpPort" binding="this:GetHDCONFIGDetailsExport1_GetHDCONFIGDetailsHttpBinding">
      <soap:address location="http://10.133.208.194/optimus-serviceactivation/api/ws/getHDConfig.wsdl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>