<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NetPResponse" targetNamespace="http://www.tcl.com/v1/netpresponse/inf/Binding" xmlns:Port_0="http://www.tcl.com/v1/netpresponse/inf" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://www.tcl.com/v1/netpresponse/inf/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="NetPResponse.wsdl" namespace="http://www.tcl.com/v1/netpresponse/inf"/>
  <wsdl:service name="NetPResponseExport1_NetPResponseHttpService">
    <wsdl:port binding="Port_0:NetPResponseBinding" name="NetPResponsePort">
      <soap:address location="http://localhost:9080/HelloWorldMediationWeb/sca/NetPResponseExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>