<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="NetPRequestService"
	targetNamespace="http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding"
	xmlns:Port_0="http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:this="http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
	<wsdl:import location="NetPRequest.wsdl"
		namespace="http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest" />
	<wsdl:binding name="NetPRequestService"
		type="Port_0:NetPRequest">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="performNetworkOrderRequest">
			<soap:operation
				soapAction="http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding/performNetworkOrderRequest" />
			<wsdl:input name="performNetworkOrderRequestRequest">
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
		<wsdl:operation name="performIPServiceActivation">
			<soap:operation
				soapAction="http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding/performIPServiceActivation" />
			<wsdl:input name="performIPServiceActivationRequest">
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
		<wsdl:operation
			name="performTransmissionServiceActivation">
			<soap:operation
				soapAction="http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding/performTransmissionServiceActivation" />
			<wsdl:input
				name="performTransmissionServiceActivationRequest">
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
		<wsdl:operation name="performIPIORActivation">
			<soap:operation
				soapAction="http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding/performIPIORActivation" />
			<wsdl:input name="performIPIORActivationRequest">
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="NetPRequestService">
		<wsdl:port binding="this:NetPRequestService"
			name="NetPRequestPort">
			<soap:address
				location="http://localhost:9080/TestWeb/sca/NetPRequestExport1" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>