<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GetCLRCreationDetailsExport_GetCLRCreationDetailsHttp_Service" targetNamespace="http://ACE_CLRCreation_Module/GetCLRCreationDetails/Binding" xmlns:Port_0="http://ACE_CLRCreation_Module/GetCLRCreationDetails" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://ACE_CLRCreation_Module/GetCLRCreationDetails/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:import namespace="http://ACE_CLRCreation_Module/GetCLRCreationDetails" location="clrcreationdetails_1.wsdl"/>
  <wsdl:binding name="GetCLRCreationDetailsExport_GetCLRCreationDetailsHttpBinding" type="Port_0:GetCLRCreationDetails">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getCLRCreationDetails">
      <soap:operation soapAction=""/>
      <wsdl:input name="getCLRCreationDetailsRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getCLRCreationDetailsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getCLRCreationDetailsFault">
        <soap:fault name="getCLRCreationDetailsFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="submitCLRCreationFailureResponse">
      <soap:operation soapAction=""/>
      <wsdl:input name="submitCLRCreationFailureResponseRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="submitCLRCreationFailureResponseResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="submitCLRCreationFailureResponseFault">
        <soap:fault name="submitCLRCreationFailureResponseFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetCLRCreationDetailsExport_GetCLRCreationDetailsHttpService">
    <wsdl:port name="GetCLRCreationDetailsExport_GetCLRCreationDetailsHttpPort" binding="this:GetCLRCreationDetailsExport_GetCLRCreationDetailsHttpBinding">
    <soap:address location="http://10.133.208.194/optimus-serviceactivation/api/ws/clrcreationdetails.wsdl"/>
   </wsdl:port>
  </wsdl:service>
</wsdl:definitions>