//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.07 at 01:28:50 PM IST 
//


package com.tcl.dias.servicehandover.bean.lr.termination;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OptimusTerminationResponse" type="{http://OptimusTermination}OptimusTerminationResponseBO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "optimusTerminationResponse"
})
@XmlRootElement(name = "RequestResponse")
public class RequestResponse {

    @XmlElement(name = "OptimusTerminationResponse", required = true, nillable = true)
    protected OptimusTerminationResponseBO optimusTerminationResponse;

    /**
     * Gets the value of the optimusTerminationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link OptimusTerminationResponseBO }
     *     
     */
    public OptimusTerminationResponseBO getOptimusTerminationResponse() {
        return optimusTerminationResponse;
    }

    /**
     * Sets the value of the optimusTerminationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptimusTerminationResponseBO }
     *     
     */
    public void setOptimusTerminationResponse(OptimusTerminationResponseBO value) {
        this.optimusTerminationResponse = value;
    }

}
