INSERT INTO `mst_product_family` (`id`, `name`, `status`) VALUES (7, 'IPC', 1);

INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('Flavor', 'IaaS', 1, 'optimus_jumio@legomail.com', '2019-05-27 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('OS', 'OS', 1, 'optimus_jumio@legomail.com', '2019-05-27 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('Access Type', 'Access Type', 1, 'optimus_inventurus@legomail.com', '2019-05-27 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('Access info', 'Access Info', 1, 'optimus_jumio@legomail.com', '2019-05-27 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('Additional Ip', 'Additional IP', 1, 'optimus_jumio@legomail.com', '2019-05-27 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('VPN Connection', 'VPN Connection', 1, 'optimus_jumio@legomail.com', '2019-05-27 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('Backup', 'Backup', 1, 'optimus_jumio@legomail.com', '2019-05-27 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('Managed', 'Managed', 1, 'optimus_jumio@legomail.com', '2019-05-27 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('Additional Storage', 'Additional Storage', 1, 'optimus_inventurus@legomail.com', '2019-05-29 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('IPC Common', 'IPC Common', 1, 'optimus_inventurus@legomail.com', '2019-06-17 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('Storage Partition', 'Storage Partition', 1, 'optimus_inventurus@legomail.com', '2019-06-20 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('VDOM', 'VDOM', 1, 'optimus_inventurus@legomail.com', '2019-07-26 00:00:00');
INSERT INTO `mst_product_component` (`name`, `description`, `status`, `created_by`, `created_time`) VALUES ('IPC_DISCOUNT_PROPERTIES', NULL, 1, 'optimus_inv_knowledge@legomail.com', '2019-08-07 00:00:00');

INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('vCPU','vCPU',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('vRAM','vRAM',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Storage','Storage',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Hypervisor','Hypervisor',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Type','Type',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Version','Version',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('accessType','accessType',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('dataLimit','dataLimit',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('ipVersion','ipversion',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('volume size','volume size',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('managed','managed',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('targetDataStorage','targetDataStorage',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('targetVolume','targetVolume',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('frontVolumeSize','frontVolumeSize',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('clientToSite','clientToSite',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('siteToSite','siteToSite',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('minimumCommitment','minimumCommitment',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('portBandwidth','portBandwidth',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('accessOption','accessOption',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Storage Type','Storage Type',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Storage Value','Storage Value',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('ipQuantity','ipQuantity',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Host Name','Host Name',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Zone name','Zone name',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Environment name','Environment name',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Businessunit name','Businessunit name',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Public IP','Public IP',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('boot','boot',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('swap','swap',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('kdump','kdump',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('accessOption','accessOption',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('minimumCommitment','minimumCommitment',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('mininumCommitment','mininumCommitment',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('acccessOption','acccessOption',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('IOPS Value','IOPS Value',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Additional Storage Path','Additional Storage Path',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('cleinet 2site','cleinet 2site',1,NULL,'root',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('usr','usr',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Unallocated','Unallocated',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('root','root',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('vdom','vdom',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('LM MAN bw','LM MAN bw',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('LM MAN MUX','LM MAN MUX',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('LM MAN inbuilding','LM MAN inbuilding',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('MAN OCP','MAN OCP',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('MAN Rentals','MAN Rentals',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Provider Chanrge','Provider Chanrge',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Mast Charge offnrt','Mast Charge offnrt',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Radwin','Radwin',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Mast Charge onnet','Mast Charge onnet',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('CPE Discount Install','CPE Discount Install',1,NULL,'optimus_sales',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('CPE Discount Outright Sale','CPE Discount Outright Sale',1,NULL,'optimus_sales',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('CPE Discount Rental','CPE Discount Rental',1,NULL,'optimus_sales',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('CPE Discount Management','CPE Discount Management',1,NULL,'optimus_sales',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('ASK_PRICE_ARC','ASK_PRICE_ARC',1,NULL,'optimus_sales','2019-07-30 07:21:21');
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('ASK_PRICE_NRC','ASK_PRICE_NRC',1,NULL,'optimus_sales','2019-07-30 07:21:21');
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Quantity','Quantity',1,NULL,'optimus_inventurus@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('COMMERCIAL_APPROVER1_COMMENTS','COMMERCIAL_APPROVER1_COMMENTS',1,NULL,'c1_user@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('COMMERCIAL_APPROVER2_COMMENTS','COMMERCIAL_APPROVER2_COMMENTS',1,NULL,'c2_user@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('APPROVAL_LEVEL','APPROVAL_LEVEL',1,NULL,'c1_user@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('COMMERCIAL_APPROVER3_COMMENTS','COMMERCIAL_APPROVER3_COMMENTS',1,NULL,'c3_user@legomail.com',NULL);
INSERT INTO `product_attribute_master` (`name`,`description`,`status`,`category`,`created_by`,`created_time`) VALUES ('Compressed Internet Ratio','Compressed Internet Ratio',1,NULL,'optimus_inv_knowledge@legomail.com',NULL);
