
package com.tcl.dias.serviceactivation.cramer.createservicegvpn.beans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateCramerISC", targetNamespace = "http://com.tcl.cboss.ossbss.isc.ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateCramerISC {


    /**
     * 
     * @param serviceInfo
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UpdateCramer")
    @WebResult(name = "Success", targetNamespace = "http://com.tcl.cboss.ossbss.isc.ws", partName = "Success")
    public boolean updateCramer(
        @WebParam(name = "ServiceInfo", targetNamespace = "http://com.tcl.cboss.ossbss.isc.ws", partName = "ServiceInfo")
        ServiceInfo serviceInfo);

}
