//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.19 at 11:39:50 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://WS.InternationalTaxManagement.com")
package com.tcl.dias.servicehandover.beans.taxcapture;
