package com.tcl.dias.performance.constants;
/**
 * 
 * This file contains the SQLQueryConstants.java class. This constant file have
 * all the SQL query
 * 
 *
 * @author Biswajit
 * @link http://www.tatacommunications.com/
 * @copyright 2018 Tata Communications Limited
 */
public class SQLQueryConstants {
	public static final String PERFORMANCE_RPT_QUERY_5MIN = "select sys_datetime, t.agg_start_time,m.mpd , avg_pmos_tx, avg_pmos_rx ,avg_jitter_tx, avg_jitter_rx, avg_packetloss_tx, avg_packetloss_rx from TBL_TELCHEMY_AGGREGATION_AUDIO t INNER JOIN (select agg_start_time, max(max_process_datetime) as mpd from TBL_TELCHEMY_AGGREGATION_AUDIO group by agg_start_time) m on t.agg_start_time=m.agg_start_time where     t.agg_start_time>= to_timestamptz(:agg_start_time, 'YYYY-MM-DD') and t.agg_start_time<= to_timestamptz(:agg_end_time, 'YYYY-MM-DD') and (orig_cuid in (:orig_cuid) or dest_cuid in (:dest_cuid))";
	public static final String PERFORMANCE_RPT_QUERY_HOUR = "select sys_datetime, t.agg_start_time,m.mpd , avg_pmos_tx, avg_pmos_rx ,avg_jitter_tx, avg_jitter_rx, avg_packetloss_tx, avg_packetloss_rx from TBL_TELCHEMY_AGGREGATION_AUDIO_HOUR t INNER JOIN (select agg_start_time, max(max_process_datetime) as mpd from TBL_TELCHEMY_AGGREGATION_AUDIO_HOUR group by agg_start_time) m on t.agg_start_time=m.agg_start_time where     t.agg_start_time>= to_timestamptz(:agg_start_time, 'YYYY-MM-DD') and t.agg_start_time<= to_timestamptz(:agg_end_time, 'YYYY-MM-DD') and (orig_cuid in (:orig_cuid) or dest_cuid in (:dest_cuid))";
	public static final String PERFORMANCE_RPT_QUERY_DAY = "select sys_datetime, t.agg_start_time,m.mpd , avg_pmos_tx, avg_pmos_rx ,avg_jitter_tx, avg_jitter_rx, avg_packetloss_tx, avg_packetloss_rx from TBL_TELCHEMY_AGGREGATION_AUDIO_DAY t INNER JOIN (select agg_start_time, max(max_process_datetime) as mpd from TBL_TELCHEMY_AGGREGATION_AUDIO_DAY group by agg_start_time) m on t.agg_start_time=m.agg_start_time where     t.agg_start_time>= to_timestamptz(:agg_start_time, 'YYYY-MM-DD') and t.agg_start_time<= to_timestamptz(:agg_end_time, 'YYYY-MM-DD') and (orig_cuid in (:orig_cuid) or dest_cuid in (:dest_cuid))";
	public static final String USAGE_RPT_QUERY_5MIN = "select sys_datetime, t.agg_start_time, m.mpd,total_answered_calls/total_call_attempts as asr , total_completed_calls/total_call_attempts as ner ,avg_call_duration as acd, avg_pdd as pdd,duration_total_minutes mou,total_call_attempts as callAttempts from TBL_TELCHEMY_AGGREGATION_AUDIO t INNER JOIN (select agg_start_time, max(max_process_datetime) as mpd from TBL_TELCHEMY_AGGREGATION_AUDIO group by agg_start_time) m on t.agg_start_time=m.agg_start_time and  m.mpd=t.max_process_datetime  where total_call_attempts != '0' and  t.agg_start_time>= to_timestamptz(:agg_start_time, 'YYYY-MM-DD') and t.agg_start_time<= to_timestamptz(:agg_end_time, 'YYYY-MM-DD') and (orig_cuid in (:orig_cuid) or dest_cuid in (:dest_cuid))";
	public static final String USAGE_RPT_QUERY_HOUR = "select sys_datetime, t.agg_start_time, m.mpd,total_answered_calls/total_call_attempts as asr , total_completed_calls/total_call_attempts as ner ,avg_call_duration as acd, avg_pdd as pdd,duration_total_minutes mou,total_call_attempts as callAttempts from TBL_TELCHEMY_AGGREGATION_AUDIO_HOUR t INNER JOIN (select agg_start_time, max(max_process_datetime) as mpd from TBL_TELCHEMY_AGGREGATION_AUDIO_HOUR group by agg_start_time) m on t.agg_start_time=m.agg_start_time and  m.mpd=t.max_process_datetime  where total_call_attempts != '0' and  t.agg_start_time>= to_timestamptz(:agg_start_time, 'YYYY-MM-DD') and t.agg_start_time<= to_timestamptz(:agg_end_time, 'YYYY-MM-DD') and (orig_cuid in (:orig_cuid) or dest_cuid in (:dest_cuid))";
	public static final String USAGE_RPT_QUERY_DAY = "select sys_datetime, t.agg_start_time, m.mpd,total_answered_calls/total_call_attempts as asr , total_completed_calls/total_call_attempts as ner ,avg_call_duration as acd, avg_pdd as pdd,duration_total_minutes mou,total_call_attempts as callAttempts from TBL_TELCHEMY_AGGREGATION_AUDIO_DAY t INNER JOIN (select agg_start_time, max(max_process_datetime) as mpd from TBL_TELCHEMY_AGGREGATION_AUDIO_DAY group by agg_start_time) m on t.agg_start_time=m.agg_start_time and  m.mpd=t.max_process_datetime  where total_call_attempts != '0' and  t.agg_start_time>= to_timestamptz(:agg_start_time, 'YYYY-MM-DD') and t.agg_start_time<= to_timestamptz(:agg_end_time, 'YYYY-MM-DD') and (orig_cuid in (:orig_cuid) or dest_cuid in (:dest_cuid))";
	public static final String CONCURRENT_BANDWIDTH_RPT_QUERY_5MIN = "select t.calltime, m.mpd, outbound_call, inbound_call, max_call, max_outbound_call, max_inbound_call, max_bandwidth, max_outbound_bandwidth, max_inbound_bandwidth from TBL_CONCURRENT_AGGREGATION_5MIN  t INNER JOIN (select calltime, max(max_process_datetime) as mpd from TBL_CONCURRENT_AGGREGATION_5MIN group by calltime) m on t.calltime=m.calltime and  m.mpd=t.max_process_datetime where  t.calltime>= to_timestamptz(:call_start_time, 'YYYY-MM-DD') and t.calltime<= to_timestamptz(:call_end_time, 'YYYY-MM-DD') and cuid in (:cuid)";
	public static final String CONCURRENT_BANDWIDTH_RPT_QUERY_HOUR = "select t.calltime, m.mpd, outbound_call, inbound_call, max_call, max_outbound_call, max_inbound_call, max_bandwidth, max_outbound_bandwidth, max_inbound_bandwidth from TBL_CONCURRENT_AGGREGATION_HOUR  t INNER JOIN (select calltime, max(max_process_datetime) as mpd from TBL_CONCURRENT_AGGREGATION_HOUR group by calltime) m on t.calltime=m.calltime and  m.mpd=t.max_process_datetime where  t.calltime>= to_timestamptz(:call_start_time, 'YYYY-MM-DD') and t.calltime<= to_timestamptz(:call_end_time, 'YYYY-MM-DD') and cuid in (:cuid)";
	public static final String CONCURRENT_BANDWIDTH_RPT_QUERY_DAY = "select t.calltime, m.mpd, outbound_call, inbound_call, max_call, max_outbound_call, max_inbound_call, max_bandwidth, max_outbound_bandwidth, max_inbound_bandwidth from TBL_CONCURRENT_AGGREGATION_DAY  t INNER JOIN (select calltime, max(max_process_datetime) as mpd from TBL_CONCURRENT_AGGREGATION_DAY group by calltime) m on t.calltime=m.calltime and  m.mpd=t.max_process_datetime where  t.calltime>= to_timestamptz(:call_start_time, 'YYYY-MM-DD') and t.calltime<= to_timestamptz(:call_end_time, 'YYYY-MM-DD') and cuid in (:cuid)";
	public static final String SOURCE_COUNTRY_LIST_QUERY_5MIN="select distinct orig_country as origCounrtry from TBL_TELCHEMY_AGGREGATION_AUDIO where orig_cuid in (:orig_cuid)";
	public static final String SOURCE_COUNTRY_LIST_QUERY_HOUR="select distinct orig_country as origCounrtry from TBL_TELCHEMY_AGGREGATION_AUDIO_HOUR where orig_cuid in (:orig_cuid)";
	public static final String SOURCE_COUNTRY_LIST_QUERY_DAY="select distinct orig_country as origCounrtry  from TBL_TELCHEMY_AGGREGATION_AUDIO_DAY where orig_cuid in (:orig_cuid)";
	public static final String DST_COUNTRY_LIST_QUERY_5MIN="select distinct dst_country as dstCountry from TBL_TELCHEMY_AGGREGATION_AUDIO where dest_cuid in (:dest_cuid)";
	public static final String DST_COUNTRY_LIST_QUERY_HOUR="select distinct dst_country as dstCountry from TBL_TELCHEMY_AGGREGATION_AUDIO_HOUR where dest_cuid in (:dest_cuid)";
	public static final String DST_COUNTRY_LIST_QUERY_DAY="select distinct dst_country as dstCountry from TBL_TELCHEMY_AGGREGATION_AUDIO_DAY where dest_cuid in (:dest_cuid)";
	public static final String ORIG_LOCATION_LIST_QUERY_5MIN="select distinct orig_location from TBL_TELCHEMY_AGGREGATION_AUDIO where orig_country=:orig_country and orig_cuid in (:orig_cuid)";
	public static final String ORIG_LOCATION_LIST_QUERY_HOUR="select distinct orig_location from TBL_TELCHEMY_AGGREGATION_AUDIO_HOUR where orig_country=:orig_country and orig_cuid in (:orig_cuid)";
	public static final String ORIG_LOCATION_LIST_QUERY_DAY="select distinct orig_location from TBL_TELCHEMY_AGGREGATION_AUDIO_DAY where orig_country=:orig_country and orig_cuid in (:orig_cuid)";
	public static final String DST_LOCATION_LIST_QUERY_5MIN="select distinct dst_location from TBL_TELCHEMY_AGGREGATION_AUDIO where dst_country=:dst_country and dest_cuid in (:dest_cuid)";
	public static final String DST_LOCATION_LIST_QUERY_HOUR="select distinct dst_location from TBL_TELCHEMY_AGGREGATION_AUDIO_HOUR where dst_country=:dst_country and  dest_cuid in (:dest_cuid)";
	public static final String DST_LOCATION_LIST_QUERY_DAY="select distinct dst_location from TBL_TELCHEMY_AGGREGATION_AUDIO_DAY where dst_country=:dst_country and  dest_cuid in (:dest_cuid)";
	public static final String CONCRRNT_LOCATION_LIST_QUERY_5MIN="select distinct location from TBL_CONCURRENT_AGGREGATION_5MIN where cuid in (:cuid)";
	public static final String CONCRRNT_LOCATION_LIST_QUERY_HOUR="select distinct location from TBL_CONCURRENT_AGGREGATION_HOUR where cuid in (:cuid)";
	public static final String CONCRRNT_LOCATION_LIST_QUERY_DAY="select distinct location from TBL_CONCURRENT_AGGREGATION_DAY where cuid in (:cuid)";
	

}
