<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SetActualTaxExport1_SetActualTaxHttp_Service" targetNamespace="http://WS.InternationalTaxManagement.com/SetActualTax/Binding" xmlns:Port_0="http://WS.InternationalTaxManagement.com/SetActualTax" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://WS.InternationalTaxManagement.com/SetActualTax/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:import namespace="http://WS.InternationalTaxManagement.com/SetActualTax" location="SetActualTax.wsdl"/>
  <wsdl:binding name="SetActualTaxExport1_SetActualTaxHttpBinding" type="Port_0:SetActualTax">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="setActualTax">
      <soap:operation soapAction=""/>
      <wsdl:input name="setActualTaxRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="setActualTaxResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SetActualTaxExport1_SetActualTaxHttpService">
    <wsdl:port name="SetActualTaxExport1_SetActualTaxHttpPort" binding="this:SetActualTaxExport1_SetActualTaxHttpBinding">
      <soap:address location="http://10.133.20.12:9080/WS.InternationalTaxManagement.comWeb/sca/SetActualTaxExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>