
package com.tcl.dias.serviceactivation.cramer.getclrsync.beans;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Async_ServiceDetailFault", targetNamespace = "http://com.tatacommunications.cramer.ace.service.async.ws.getclr.ServiceDetail_Async")
public class AsyncServiceDetailFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AsyncCLRInfoFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AsyncServiceDetailFault(String message, AsyncCLRInfoFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AsyncServiceDetailFault(String message, AsyncCLRInfoFault faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.tcl.dias.networkinventoryclient.cramer.getclrsync.beans.AsyncCLRInfoFault
     */
    public AsyncCLRInfoFault getFaultInfo() {
        return faultInfo;
    }

}
