<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SetSECSProfileExport1_SetSECSProfileHttp_Service" targetNamespace="http://WS.InternationalCustomerMngmnt.com/SetSECSProfile/Binding" xmlns:Port_0="http://WS.InternationalCustomerMngmnt.com/SetSECSProfile" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://WS.InternationalCustomerMngmnt.com/SetSECSProfile/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:import namespace="http://WS.InternationalCustomerMngmnt.com/SetSECSProfile" location="SetSECSProfile.wsdl"/>
  <wsdl:binding name="SetSECSProfileExport1_SetSECSProfileHttpBinding" type="Port_0:SetSECSProfile">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="setSECSProfile">
      <soap:operation soapAction=""/>
      <wsdl:input name="setSECSProfileRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="setSECSProfileResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SetSECSProfileExport1_SetSECSProfileHttpService">
    <wsdl:port name="SetSECSProfileExport1_SetSECSProfileHttpPort" binding="this:SetSECSProfileExport1_SetSECSProfileHttpBinding">
      <soap:address location="http://121.244.254.241:10083/WS.InternationalCustomerMngmnt.comWeb/sca/SetSECSProfileExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>