//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.12 at 10:48:57 AM IST 
//


package com.tcl.dias.servicehandover.ipc.beans.createorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountCreationRequestBO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountCreationRequestBO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="account_input" type="{http://InstaCCLibrary/BSSEBOs}AccountCreationInputBO" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountCreationRequestBO", propOrder = {
    "accountInput"
})
public class AccountCreationRequestBO {

    @XmlElement(name = "account_input")
    protected AccountCreationInputBO accountInput;

    /**
     * Gets the value of the accountInput property.
     * 
     * @return
     *     possible object is
     *     {@link AccountCreationInputBO }
     *     
     */
    public AccountCreationInputBO getAccountInput() {
        return accountInput;
    }

    /**
     * Sets the value of the accountInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountCreationInputBO }
     *     
     */
    public void setAccountInput(AccountCreationInputBO value) {
        this.accountInput = value;
    }

}
