//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.12 at 10:48:57 AM IST 
//


package com.tcl.dias.servicehandover.ipc.beans.createorder;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tcl.dias.servicehandover.ipc.beans.createorder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tcl.dias.servicehandover.ipc.beans.createorder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateOrder }
     * 
     */
    public CreateOrder createCreateOrder() {
        return new CreateOrder();
    }

    /**
     * Create an instance of {@link CreateOrderBO }
     * 
     */
    public CreateOrderBO createCreateOrderBO() {
        return new CreateOrderBO();
    }

    /**
     * Create an instance of {@link CreateOrderResponse }
     * 
     */
    public CreateOrderResponse createCreateOrderResponse() {
        return new CreateOrderResponse();
    }

    /**
     * Create an instance of {@link CreateOrderRequestAckBO }
     * 
     */
    public CreateOrderRequestAckBO createCreateOrderRequestAckBO() {
        return new CreateOrderRequestAckBO();
    }

    /**
     * Create an instance of {@link CommonBO }
     * 
     */
    public CommonBO createCommonBO() {
        return new CommonBO();
    }

    /**
     * Create an instance of {@link CommonAttributesBO }
     * 
     */
    public CommonAttributesBO createCommonAttributesBO() {
        return new CommonAttributesBO();
    }

    /**
     * Create an instance of {@link ProductCreationInputBO }
     * 
     */
    public ProductCreationInputBO createProductCreationInputBO() {
        return new ProductCreationInputBO();
    }

    /**
     * Create an instance of {@link ProductCreationRequestBO }
     * 
     */
    public ProductCreationRequestBO createProductCreationRequestBO() {
        return new ProductCreationRequestBO();
    }

    /**
     * Create an instance of {@link AccountCreationInputBO }
     * 
     */
    public AccountCreationInputBO createAccountCreationInputBO() {
        return new AccountCreationInputBO();
    }

    /**
     * Create an instance of {@link AccountCreationRequestBO }
     * 
     */
    public AccountCreationRequestBO createAccountCreationRequestBO() {
        return new AccountCreationRequestBO();
    }

    /**
     * Create an instance of {@link CreateOrderRequestBO }
     * 
     */
    public CreateOrderRequestBO createCreateOrderRequestBO() {
        return new CreateOrderRequestBO();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link ProductCreationOutputBO }
     * 
     */
    public ProductCreationOutputBO createProductCreationOutputBO() {
        return new ProductCreationOutputBO();
    }

    /**
     * Create an instance of {@link AccountCreationOutputBO }
     * 
     */
    public AccountCreationOutputBO createAccountCreationOutputBO() {
        return new AccountCreationOutputBO();
    }

    /**
     * Create an instance of {@link CreateOrderResponseBO }
     * 
     */
    public CreateOrderResponseBO createCreateOrderResponseBO() {
        return new CreateOrderResponseBO();
    }

    /**
     * Create an instance of {@link ProductCreationResponseBO }
     * 
     */
    public ProductCreationResponseBO createProductCreationResponseBO() {
        return new ProductCreationResponseBO();
    }

    /**
     * Create an instance of {@link AccountCreationResponseBO }
     * 
     */
    public AccountCreationResponseBO createAccountCreationResponseBO() {
        return new AccountCreationResponseBO();
    }

}
