//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.12 at 10:48:57 AM IST 
//


package com.tcl.dias.servicehandover.ipc.beans.createorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductCreationInputBO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductCreationInputBO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="prorate_boo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cps_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="invocing_coName_prd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="currency_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vat_identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="charge_period" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="refund_boo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="business_unit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="product_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="source_parentProductSeq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="currency_code_prd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="contract_duration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customer_orderNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="taxExempt_ref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="taxExempt_txt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prod_addr1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prod_addr2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prod_addr3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prod_city" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prod_state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prod_zipcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prod_country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prod_quantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eventSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eventsource_label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eventSource_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="event_string" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creation_date_prd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="source_oldProdSeq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="scenario_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rate_override_boo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="final_flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="discount_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="discount_tiers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="min_qty_tier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="attr9" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="attr10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cost_bandName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="terminate_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eventClass_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="chargeSegment_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="chargingRate_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rate_endDtm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ovrdn_intPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ovrdn_periodicPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="component_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="delivery_addr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="warehouse_addr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="equipment_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="system_idicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="term_proposedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="term_reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="term_charges" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="deposit_refund_boo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="c_form" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="copf_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="addEventSRC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="termEventSRC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="i_size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="term_endDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="taxation_docsURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orderType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="change_orderType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="commission_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="billActivation_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="billGeneration_date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="attribute_string" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="siteA_GeoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="siteZ_GeoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customer_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customer_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cpe_account_nums" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cpe_delivery_adds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="total_arc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="total_nrc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ciruit_count" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SITE_A_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SITE_B_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CONTRACTING_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SITE_END" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CONTRACT_GSTIN_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SITE_GSTIN_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CONTRACTING_GSTIN_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SITE_GSTIN_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductCreationInputBO", propOrder = {
    "prorateBoo",
    "cpsName",
    "invocingCoNamePrd",
    "currencyCode",
    "vatIdentifier",
    "chargePeriod",
    "refundBoo",
    "businessUnit",
    "productName",
    "sourceParentProductSeq",
    "currencyCodePrd",
    "contractDuration",
    "customerOrderNum",
    "taxExemptRef",
    "taxExemptTxt",
    "prodAddr1",
    "prodAddr2",
    "prodAddr3",
    "prodCity",
    "prodState",
    "prodZipcode",
    "prodCountry",
    "prodQuantity",
    "eventSource",
    "eventsourceLabel",
    "eventSourceText",
    "eventString",
    "creationDatePrd",
    "sourceOldProdSeq",
    "scenarioType",
    "rateOverrideBoo",
    "finalFlag",
    "discountName",
    "discountTiers",
    "minQtyTier",
    "attr9",
    "attr10",
    "costBandName",
    "terminateName",
    "eventClassName",
    "chargeSegmentName",
    "chargingRateValue",
    "rateEndDtm",
    "ovrdnIntPrice",
    "ovrdnPeriodicPrice",
    "componentName",
    "deliveryAddr",
    "warehouseAddr",
    "equipmentType",
    "systemIdicator",
    "termProposedDate",
    "termReason",
    "termCharges",
    "depositRefundBoo",
    "username",
    "cForm",
    "serviceId",
    "copfId",
    "addEventSRC",
    "termEventSRC",
    "iSize",
    "termEndDate",
    "taxationDocsURL",
    "orderType",
    "changeOrderType",
    "commissionDate",
    "billActivationDate",
    "billGenerationDate",
    "attributeString",
    "siteAGeoCode",
    "siteZGeoCode",
    "customerType",
    "customerName",
    "cpeAccountNums",
    "cpeDeliveryAdds",
    "totalArc",
    "totalNrc",
    "ciruitCount",
    "siteaaddress",
    "sitebaddress",
    "contractingaddress",
    "siteend",
    "contractgstinaddress",
    "sitegstinaddress",
    "contractinggstinno",
    "sitegstinno"
})
public class ProductCreationInputBO {

    @XmlElement(name = "prorate_boo")
    protected String prorateBoo;
    @XmlElement(name = "cps_name")
    protected String cpsName;
    @XmlElement(name = "invocing_coName_prd")
    protected String invocingCoNamePrd;
    @XmlElement(name = "currency_code")
    protected String currencyCode;
    @XmlElement(name = "vat_identifier")
    protected String vatIdentifier;
    @XmlElement(name = "charge_period")
    protected String chargePeriod;
    @XmlElement(name = "refund_boo")
    protected String refundBoo;
    @XmlElement(name = "business_unit")
    protected String businessUnit;
    @XmlElement(name = "product_name")
    protected String productName;
    @XmlElement(name = "source_parentProductSeq")
    protected String sourceParentProductSeq;
    @XmlElement(name = "currency_code_prd")
    protected String currencyCodePrd;
    @XmlElement(name = "contract_duration")
    protected String contractDuration;
    @XmlElement(name = "customer_orderNum")
    protected String customerOrderNum;
    @XmlElement(name = "taxExempt_ref")
    protected String taxExemptRef;
    @XmlElement(name = "taxExempt_txt")
    protected String taxExemptTxt;
    @XmlElement(name = "prod_addr1")
    protected String prodAddr1;
    @XmlElement(name = "prod_addr2")
    protected String prodAddr2;
    @XmlElement(name = "prod_addr3")
    protected String prodAddr3;
    @XmlElement(name = "prod_city")
    protected String prodCity;
    @XmlElement(name = "prod_state")
    protected String prodState;
    @XmlElement(name = "prod_zipcode")
    protected String prodZipcode;
    @XmlElement(name = "prod_country")
    protected String prodCountry;
    @XmlElement(name = "prod_quantity")
    protected String prodQuantity;
    protected String eventSource;
    @XmlElement(name = "eventsource_label")
    protected String eventsourceLabel;
    @XmlElement(name = "eventSource_text")
    protected String eventSourceText;
    @XmlElement(name = "event_string")
    protected String eventString;
    @XmlElement(name = "creation_date_prd")
    protected String creationDatePrd;
    @XmlElement(name = "source_oldProdSeq")
    protected String sourceOldProdSeq;
    @XmlElement(name = "scenario_type")
    protected String scenarioType;
    @XmlElement(name = "rate_override_boo")
    protected String rateOverrideBoo;
    @XmlElement(name = "final_flag")
    protected String finalFlag;
    @XmlElement(name = "discount_name")
    protected String discountName;
    @XmlElement(name = "discount_tiers")
    protected String discountTiers;
    @XmlElement(name = "min_qty_tier")
    protected String minQtyTier;
    protected String attr9;
    protected String attr10;
    @XmlElement(name = "cost_bandName")
    protected String costBandName;
    @XmlElement(name = "terminate_name")
    protected String terminateName;
    @XmlElement(name = "eventClass_name")
    protected String eventClassName;
    @XmlElement(name = "chargeSegment_name")
    protected String chargeSegmentName;
    @XmlElement(name = "chargingRate_value")
    protected String chargingRateValue;
    @XmlElement(name = "rate_endDtm")
    protected String rateEndDtm;
    @XmlElement(name = "ovrdn_intPrice")
    protected String ovrdnIntPrice;
    @XmlElement(name = "ovrdn_periodicPrice")
    protected String ovrdnPeriodicPrice;
    @XmlElement(name = "component_name")
    protected String componentName;
    @XmlElement(name = "delivery_addr")
    protected String deliveryAddr;
    @XmlElement(name = "warehouse_addr")
    protected String warehouseAddr;
    @XmlElement(name = "equipment_type")
    protected String equipmentType;
    @XmlElement(name = "system_idicator")
    protected String systemIdicator;
    @XmlElement(name = "term_proposedDate")
    protected String termProposedDate;
    @XmlElement(name = "term_reason")
    protected String termReason;
    @XmlElement(name = "term_charges")
    protected String termCharges;
    @XmlElement(name = "deposit_refund_boo")
    protected String depositRefundBoo;
    protected String username;
    @XmlElement(name = "c_form")
    protected String cForm;
    @XmlElement(name = "service_id")
    protected String serviceId;
    @XmlElement(name = "copf_id")
    protected String copfId;
    protected String addEventSRC;
    protected String termEventSRC;
    @XmlElement(name = "i_size")
    protected String iSize;
    @XmlElement(name = "term_endDate")
    protected String termEndDate;
    @XmlElement(name = "taxation_docsURL")
    protected String taxationDocsURL;
    protected String orderType;
    @XmlElement(name = "change_orderType")
    protected String changeOrderType;
    @XmlElement(name = "commission_date")
    protected String commissionDate;
    @XmlElement(name = "billActivation_date")
    protected String billActivationDate;
    @XmlElement(name = "billGeneration_date")
    protected String billGenerationDate;
    @XmlElement(name = "attribute_string")
    protected String attributeString;
    @XmlElement(name = "siteA_GeoCode")
    protected String siteAGeoCode;
    @XmlElement(name = "siteZ_GeoCode")
    protected String siteZGeoCode;
    @XmlElement(name = "customer_type")
    protected String customerType;
    @XmlElement(name = "customer_name")
    protected String customerName;
    @XmlElement(name = "cpe_account_nums")
    protected String cpeAccountNums;
    @XmlElement(name = "cpe_delivery_adds")
    protected String cpeDeliveryAdds;
    @XmlElement(name = "total_arc")
    protected String totalArc;
    @XmlElement(name = "total_nrc")
    protected String totalNrc;
    @XmlElement(name = "ciruit_count")
    protected String ciruitCount;
    @XmlElement(name = "SITE_A_ADDRESS")
    protected String siteaaddress;
    @XmlElement(name = "SITE_B_ADDRESS")
    protected String sitebaddress;
    @XmlElement(name = "CONTRACTING_ADDRESS")
    protected String contractingaddress;
    @XmlElement(name = "SITE_END")
    protected String siteend;
    @XmlElement(name = "CONTRACT_GSTIN_ADDRESS")
    protected String contractgstinaddress;
    @XmlElement(name = "SITE_GSTIN_ADDRESS")
    protected String sitegstinaddress;
    @XmlElement(name = "CONTRACTING_GSTIN_NO")
    protected String contractinggstinno;
    @XmlElement(name = "SITE_GSTIN_NO")
    protected String sitegstinno;

    /**
     * Gets the value of the prorateBoo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProrateBoo() {
        return prorateBoo;
    }

    /**
     * Sets the value of the prorateBoo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProrateBoo(String value) {
        this.prorateBoo = value;
    }

    /**
     * Gets the value of the cpsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpsName() {
        return cpsName;
    }

    /**
     * Sets the value of the cpsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpsName(String value) {
        this.cpsName = value;
    }

    /**
     * Gets the value of the invocingCoNamePrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvocingCoNamePrd() {
        return invocingCoNamePrd;
    }

    /**
     * Sets the value of the invocingCoNamePrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvocingCoNamePrd(String value) {
        this.invocingCoNamePrd = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the vatIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatIdentifier() {
        return vatIdentifier;
    }

    /**
     * Sets the value of the vatIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatIdentifier(String value) {
        this.vatIdentifier = value;
    }

    /**
     * Gets the value of the chargePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargePeriod() {
        return chargePeriod;
    }

    /**
     * Sets the value of the chargePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargePeriod(String value) {
        this.chargePeriod = value;
    }

    /**
     * Gets the value of the refundBoo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundBoo() {
        return refundBoo;
    }

    /**
     * Sets the value of the refundBoo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundBoo(String value) {
        this.refundBoo = value;
    }

    /**
     * Gets the value of the businessUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessUnit() {
        return businessUnit;
    }

    /**
     * Sets the value of the businessUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessUnit(String value) {
        this.businessUnit = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the sourceParentProductSeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceParentProductSeq() {
        return sourceParentProductSeq;
    }

    /**
     * Sets the value of the sourceParentProductSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceParentProductSeq(String value) {
        this.sourceParentProductSeq = value;
    }

    /**
     * Gets the value of the currencyCodePrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCodePrd() {
        return currencyCodePrd;
    }

    /**
     * Sets the value of the currencyCodePrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCodePrd(String value) {
        this.currencyCodePrd = value;
    }

    /**
     * Gets the value of the contractDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractDuration() {
        return contractDuration;
    }

    /**
     * Sets the value of the contractDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractDuration(String value) {
        this.contractDuration = value;
    }

    /**
     * Gets the value of the customerOrderNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerOrderNum() {
        return customerOrderNum;
    }

    /**
     * Sets the value of the customerOrderNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerOrderNum(String value) {
        this.customerOrderNum = value;
    }

    /**
     * Gets the value of the taxExemptRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptRef() {
        return taxExemptRef;
    }

    /**
     * Sets the value of the taxExemptRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptRef(String value) {
        this.taxExemptRef = value;
    }

    /**
     * Gets the value of the taxExemptTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptTxt() {
        return taxExemptTxt;
    }

    /**
     * Sets the value of the taxExemptTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptTxt(String value) {
        this.taxExemptTxt = value;
    }

    /**
     * Gets the value of the prodAddr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdAddr1() {
        return prodAddr1;
    }

    /**
     * Sets the value of the prodAddr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdAddr1(String value) {
        this.prodAddr1 = value;
    }

    /**
     * Gets the value of the prodAddr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdAddr2() {
        return prodAddr2;
    }

    /**
     * Sets the value of the prodAddr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdAddr2(String value) {
        this.prodAddr2 = value;
    }

    /**
     * Gets the value of the prodAddr3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdAddr3() {
        return prodAddr3;
    }

    /**
     * Sets the value of the prodAddr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdAddr3(String value) {
        this.prodAddr3 = value;
    }

    /**
     * Gets the value of the prodCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdCity() {
        return prodCity;
    }

    /**
     * Sets the value of the prodCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdCity(String value) {
        this.prodCity = value;
    }

    /**
     * Gets the value of the prodState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdState() {
        return prodState;
    }

    /**
     * Sets the value of the prodState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdState(String value) {
        this.prodState = value;
    }

    /**
     * Gets the value of the prodZipcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdZipcode() {
        return prodZipcode;
    }

    /**
     * Sets the value of the prodZipcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdZipcode(String value) {
        this.prodZipcode = value;
    }

    /**
     * Gets the value of the prodCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdCountry() {
        return prodCountry;
    }

    /**
     * Sets the value of the prodCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdCountry(String value) {
        this.prodCountry = value;
    }

    /**
     * Gets the value of the prodQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdQuantity() {
        return prodQuantity;
    }

    /**
     * Sets the value of the prodQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdQuantity(String value) {
        this.prodQuantity = value;
    }

    /**
     * Gets the value of the eventSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventSource() {
        return eventSource;
    }

    /**
     * Sets the value of the eventSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventSource(String value) {
        this.eventSource = value;
    }

    /**
     * Gets the value of the eventsourceLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventsourceLabel() {
        return eventsourceLabel;
    }

    /**
     * Sets the value of the eventsourceLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventsourceLabel(String value) {
        this.eventsourceLabel = value;
    }

    /**
     * Gets the value of the eventSourceText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventSourceText() {
        return eventSourceText;
    }

    /**
     * Sets the value of the eventSourceText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventSourceText(String value) {
        this.eventSourceText = value;
    }

    /**
     * Gets the value of the eventString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventString() {
        return eventString;
    }

    /**
     * Sets the value of the eventString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventString(String value) {
        this.eventString = value;
    }

    /**
     * Gets the value of the creationDatePrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDatePrd() {
        return creationDatePrd;
    }

    /**
     * Sets the value of the creationDatePrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDatePrd(String value) {
        this.creationDatePrd = value;
    }

    /**
     * Gets the value of the sourceOldProdSeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOldProdSeq() {
        return sourceOldProdSeq;
    }

    /**
     * Sets the value of the sourceOldProdSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOldProdSeq(String value) {
        this.sourceOldProdSeq = value;
    }

    /**
     * Gets the value of the scenarioType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScenarioType() {
        return scenarioType;
    }

    /**
     * Sets the value of the scenarioType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScenarioType(String value) {
        this.scenarioType = value;
    }

    /**
     * Gets the value of the rateOverrideBoo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateOverrideBoo() {
        return rateOverrideBoo;
    }

    /**
     * Sets the value of the rateOverrideBoo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateOverrideBoo(String value) {
        this.rateOverrideBoo = value;
    }

    /**
     * Gets the value of the finalFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalFlag() {
        return finalFlag;
    }

    /**
     * Sets the value of the finalFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalFlag(String value) {
        this.finalFlag = value;
    }

    /**
     * Gets the value of the discountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountName() {
        return discountName;
    }

    /**
     * Sets the value of the discountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountName(String value) {
        this.discountName = value;
    }

    /**
     * Gets the value of the discountTiers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountTiers() {
        return discountTiers;
    }

    /**
     * Sets the value of the discountTiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountTiers(String value) {
        this.discountTiers = value;
    }

    /**
     * Gets the value of the minQtyTier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinQtyTier() {
        return minQtyTier;
    }

    /**
     * Sets the value of the minQtyTier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinQtyTier(String value) {
        this.minQtyTier = value;
    }

    /**
     * Gets the value of the attr9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttr9() {
        return attr9;
    }

    /**
     * Sets the value of the attr9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttr9(String value) {
        this.attr9 = value;
    }

    /**
     * Gets the value of the attr10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttr10() {
        return attr10;
    }

    /**
     * Sets the value of the attr10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttr10(String value) {
        this.attr10 = value;
    }

    /**
     * Gets the value of the costBandName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostBandName() {
        return costBandName;
    }

    /**
     * Sets the value of the costBandName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostBandName(String value) {
        this.costBandName = value;
    }

    /**
     * Gets the value of the terminateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminateName() {
        return terminateName;
    }

    /**
     * Sets the value of the terminateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminateName(String value) {
        this.terminateName = value;
    }

    /**
     * Gets the value of the eventClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventClassName() {
        return eventClassName;
    }

    /**
     * Sets the value of the eventClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventClassName(String value) {
        this.eventClassName = value;
    }

    /**
     * Gets the value of the chargeSegmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeSegmentName() {
        return chargeSegmentName;
    }

    /**
     * Sets the value of the chargeSegmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeSegmentName(String value) {
        this.chargeSegmentName = value;
    }

    /**
     * Gets the value of the chargingRateValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargingRateValue() {
        return chargingRateValue;
    }

    /**
     * Sets the value of the chargingRateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargingRateValue(String value) {
        this.chargingRateValue = value;
    }

    /**
     * Gets the value of the rateEndDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateEndDtm() {
        return rateEndDtm;
    }

    /**
     * Sets the value of the rateEndDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateEndDtm(String value) {
        this.rateEndDtm = value;
    }

    /**
     * Gets the value of the ovrdnIntPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvrdnIntPrice() {
        return ovrdnIntPrice;
    }

    /**
     * Sets the value of the ovrdnIntPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvrdnIntPrice(String value) {
        this.ovrdnIntPrice = value;
    }

    /**
     * Gets the value of the ovrdnPeriodicPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvrdnPeriodicPrice() {
        return ovrdnPeriodicPrice;
    }

    /**
     * Sets the value of the ovrdnPeriodicPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvrdnPeriodicPrice(String value) {
        this.ovrdnPeriodicPrice = value;
    }

    /**
     * Gets the value of the componentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * Sets the value of the componentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentName(String value) {
        this.componentName = value;
    }

    /**
     * Gets the value of the deliveryAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryAddr() {
        return deliveryAddr;
    }

    /**
     * Sets the value of the deliveryAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryAddr(String value) {
        this.deliveryAddr = value;
    }

    /**
     * Gets the value of the warehouseAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarehouseAddr() {
        return warehouseAddr;
    }

    /**
     * Sets the value of the warehouseAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarehouseAddr(String value) {
        this.warehouseAddr = value;
    }

    /**
     * Gets the value of the equipmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentType() {
        return equipmentType;
    }

    /**
     * Sets the value of the equipmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentType(String value) {
        this.equipmentType = value;
    }

    /**
     * Gets the value of the systemIdicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemIdicator() {
        return systemIdicator;
    }

    /**
     * Sets the value of the systemIdicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemIdicator(String value) {
        this.systemIdicator = value;
    }

    /**
     * Gets the value of the termProposedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermProposedDate() {
        return termProposedDate;
    }

    /**
     * Sets the value of the termProposedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermProposedDate(String value) {
        this.termProposedDate = value;
    }

    /**
     * Gets the value of the termReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermReason() {
        return termReason;
    }

    /**
     * Sets the value of the termReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermReason(String value) {
        this.termReason = value;
    }

    /**
     * Gets the value of the termCharges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermCharges() {
        return termCharges;
    }

    /**
     * Sets the value of the termCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermCharges(String value) {
        this.termCharges = value;
    }

    /**
     * Gets the value of the depositRefundBoo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositRefundBoo() {
        return depositRefundBoo;
    }

    /**
     * Sets the value of the depositRefundBoo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositRefundBoo(String value) {
        this.depositRefundBoo = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the cForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCForm() {
        return cForm;
    }

    /**
     * Sets the value of the cForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCForm(String value) {
        this.cForm = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the copfId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopfId() {
        return copfId;
    }

    /**
     * Sets the value of the copfId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopfId(String value) {
        this.copfId = value;
    }

    /**
     * Gets the value of the addEventSRC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddEventSRC() {
        return addEventSRC;
    }

    /**
     * Sets the value of the addEventSRC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddEventSRC(String value) {
        this.addEventSRC = value;
    }

    /**
     * Gets the value of the termEventSRC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermEventSRC() {
        return termEventSRC;
    }

    /**
     * Sets the value of the termEventSRC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermEventSRC(String value) {
        this.termEventSRC = value;
    }

    /**
     * Gets the value of the iSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISize() {
        return iSize;
    }

    /**
     * Sets the value of the iSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISize(String value) {
        this.iSize = value;
    }

    /**
     * Gets the value of the termEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermEndDate() {
        return termEndDate;
    }

    /**
     * Sets the value of the termEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermEndDate(String value) {
        this.termEndDate = value;
    }

    /**
     * Gets the value of the taxationDocsURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxationDocsURL() {
        return taxationDocsURL;
    }

    /**
     * Sets the value of the taxationDocsURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxationDocsURL(String value) {
        this.taxationDocsURL = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the changeOrderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeOrderType() {
        return changeOrderType;
    }

    /**
     * Sets the value of the changeOrderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeOrderType(String value) {
        this.changeOrderType = value;
    }

    /**
     * Gets the value of the commissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommissionDate() {
        return commissionDate;
    }

    /**
     * Sets the value of the commissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommissionDate(String value) {
        this.commissionDate = value;
    }

    /**
     * Gets the value of the billActivationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillActivationDate() {
        return billActivationDate;
    }

    /**
     * Sets the value of the billActivationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillActivationDate(String value) {
        this.billActivationDate = value;
    }

    /**
     * Gets the value of the billGenerationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillGenerationDate() {
        return billGenerationDate;
    }

    /**
     * Sets the value of the billGenerationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillGenerationDate(String value) {
        this.billGenerationDate = value;
    }

    /**
     * Gets the value of the attributeString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeString() {
        return attributeString;
    }

    /**
     * Sets the value of the attributeString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeString(String value) {
        this.attributeString = value;
    }

    /**
     * Gets the value of the siteAGeoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteAGeoCode() {
        return siteAGeoCode;
    }

    /**
     * Sets the value of the siteAGeoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteAGeoCode(String value) {
        this.siteAGeoCode = value;
    }

    /**
     * Gets the value of the siteZGeoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteZGeoCode() {
        return siteZGeoCode;
    }

    /**
     * Sets the value of the siteZGeoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteZGeoCode(String value) {
        this.siteZGeoCode = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerType(String value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the cpeAccountNums property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeAccountNums() {
        return cpeAccountNums;
    }

    /**
     * Sets the value of the cpeAccountNums property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeAccountNums(String value) {
        this.cpeAccountNums = value;
    }

    /**
     * Gets the value of the cpeDeliveryAdds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeDeliveryAdds() {
        return cpeDeliveryAdds;
    }

    /**
     * Sets the value of the cpeDeliveryAdds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeDeliveryAdds(String value) {
        this.cpeDeliveryAdds = value;
    }

    /**
     * Gets the value of the totalArc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalArc() {
        return totalArc;
    }

    /**
     * Sets the value of the totalArc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalArc(String value) {
        this.totalArc = value;
    }

    /**
     * Gets the value of the totalNrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalNrc() {
        return totalNrc;
    }

    /**
     * Sets the value of the totalNrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalNrc(String value) {
        this.totalNrc = value;
    }

    /**
     * Gets the value of the ciruitCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiruitCount() {
        return ciruitCount;
    }

    /**
     * Sets the value of the ciruitCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiruitCount(String value) {
        this.ciruitCount = value;
    }

    /**
     * Gets the value of the siteaaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSITEAADDRESS() {
        return siteaaddress;
    }

    /**
     * Sets the value of the siteaaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSITEAADDRESS(String value) {
        this.siteaaddress = value;
    }

    /**
     * Gets the value of the sitebaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSITEBADDRESS() {
        return sitebaddress;
    }

    /**
     * Sets the value of the sitebaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSITEBADDRESS(String value) {
        this.sitebaddress = value;
    }

    /**
     * Gets the value of the contractingaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTRACTINGADDRESS() {
        return contractingaddress;
    }

    /**
     * Sets the value of the contractingaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTRACTINGADDRESS(String value) {
        this.contractingaddress = value;
    }

    /**
     * Gets the value of the siteend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSITEEND() {
        return siteend;
    }

    /**
     * Sets the value of the siteend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSITEEND(String value) {
        this.siteend = value;
    }

    /**
     * Gets the value of the contractgstinaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTRACTGSTINADDRESS() {
        return contractgstinaddress;
    }

    /**
     * Sets the value of the contractgstinaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTRACTGSTINADDRESS(String value) {
        this.contractgstinaddress = value;
    }

    /**
     * Gets the value of the sitegstinaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSITEGSTINADDRESS() {
        return sitegstinaddress;
    }

    /**
     * Sets the value of the sitegstinaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSITEGSTINADDRESS(String value) {
        this.sitegstinaddress = value;
    }

    /**
     * Gets the value of the contractinggstinno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTRACTINGGSTINNO() {
        return contractinggstinno;
    }

    /**
     * Sets the value of the contractinggstinno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTRACTINGGSTINNO(String value) {
        this.contractinggstinno = value;
    }

    /**
     * Gets the value of the sitegstinno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSITEGSTINNO() {
        return sitegstinno;
    }

    /**
     * Sets the value of the sitegstinno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSITEGSTINNO(String value) {
        this.sitegstinno = value;
    }

}
