<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SetCLRResponseExport1_SetCLRResponseHttp_Service" targetNamespace="http://ACE_SetCLR_Module/SetCLRResponse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://ACE_SetCLR_Module/SetCLRResponse">
  <wsdl:import namespace="http://ACE_SetCLR_Module/SetCLRResponse" location="SetCLRResponseInterface.wsdl"/>
  <wsdl:binding name="SetCLRResponseExport1_SetCLRResponseHttpBinding" type="this:SetCLRResponseInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="setCLRResponse">
      <soap:operation soapAction=""/>
      <wsdl:input name="setCLRResponseRequest">
        <soap:body parts="setCLRResponseParameters" use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SetCLRResponseExport1_SetCLRResponseHttpService">
    <wsdl:port name="SetCLRResponseExport1_SetCLRResponseHttpPort" binding="this:SetCLRResponseExport1_SetCLRResponseHttpBinding">
      <soap:address location="http://10.133.20.12:9080/ACE_SetCLR_ModuleWeb/sca/SetCLRResponseExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>