<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SetCLRResponse" targetNamespace="http://ACE_SetCLR_Module/SetCLRResponse" xmlns:bons2="http://ACE_SetCLR_Module" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ACE_SetCLR_Module/SetCLRResponse">
  <wsdl:types>
    <xsd:schema targetNamespace="http://ACE_SetCLR_Module/SetCLRResponse">
      <xsd:import namespace="http://ACE_SetCLR_Module" schemaLocation="responseBO.xsd"/>
      <xsd:element name="setCLRResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="response" nillable="true" type="bons2:responseBO"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="setCLRResponseRequestMsg">
    <wsdl:part name="setCLRResponseParameters" element="tns:setCLRResponse"/>
  </wsdl:message>
  <wsdl:portType name="SetCLRResponseInterface">
    <wsdl:operation name="setCLRResponse">
      <wsdl:input name="setCLRResponseRequest" message="tns:setCLRResponseRequestMsg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>