
package com.tcl.dias.serviceactivation.cramer.ipservicesync.beans;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "getIRSRouterInfoFault", targetNamespace = "http://com.tatacommunications.cramer.ace.service.ws.CramerIPServices")
public class GetIRSRouterInfoFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetIRSRouterInfoFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetIRSRouterInfoFault_Exception(String message, GetIRSRouterInfoFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetIRSRouterInfoFault_Exception(String message, GetIRSRouterInfoFault faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: crameripservices.ws.service.ace.cramer.tatacommunications.com.GetIRSRouterInfoFault
     */
    public GetIRSRouterInfoFault getFaultInfo() {
        return faultInfo;
    }

}
