<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Optimus_TerminationExport1_Optimus_TerminationHttp_Service" targetNamespace="http://Optimus_Termination/Optimus_Termination" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://Optimus_Termination/Optimus_Termination" xmlns:bons0="http://OptimusTermination/OptimusTermination">
  <wsdl:import namespace="http://OptimusTermination/OptimusTermination" location="OptimusTermination.wsdl"/>
  <wsdl:binding name="Optimus_TerminationExport1_Optimus_TerminationHttpBinding" type="bons0:OptimusTermination">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Request">
      <soap:operation soapAction=""/>
      <wsdl:input name="RequestRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="RequestResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Optimus_TerminationExport1_Optimus_TerminationHttpService">
    <wsdl:port name="OptimusTerminationExport1_Optimus_TerminationHttpPort" binding="this:Optimus_TerminationExport1_Optimus_TerminationHttpBinding">
      <soap:address location="http://10.133.20.12:9080/OptimusServicesWeb/sca/OptimusTerminationExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>