
package com.tcl.dias.serviceactivation.activation.netp.beans;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NetPRequest", targetNamespace = "http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NetPRequest {


    /**
     * 
     * @param orderDetails
     * @param header
     */
    @WebMethod(action = "http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding/performNetworkOrderRequest")
    @Oneway
    @RequestWrapper(localName = "performNetworkOrderRequest", targetNamespace = "http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest", className = "com.tcl.dias.networkinventoryclient.netp.beans.PerformNetworkOrderRequest")
    public void performNetworkOrderRequest(
        @WebParam(name = "orderDetails", targetNamespace = "")
        OrderInfo orderDetails,
        @WebParam(name = "header", targetNamespace = "")
        ACEHeader header);

    /**
     * 
     * @param orderDetails
     * @param header
     */
    @WebMethod(action = "http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding/performIPServiceActivation")
    @Oneway
    @RequestWrapper(localName = "performIPServiceActivation", targetNamespace = "http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest", className = "com.tcl.dias.networkinventoryclient.netp.beans.PerformIPServiceActivation")
    public void performIPServiceActivation(
        @WebParam(name = "orderDetails", targetNamespace = "")
        OrderInfo3 orderDetails,
        @WebParam(name = "header", targetNamespace = "")
        ACEHeader header);

    /**
     * 
     * @param orderDetails
     * @param header
     */
    @WebMethod(action = "http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding/performTransmissionServiceActivation")
    @Oneway
    @RequestWrapper(localName = "performTransmissionServiceActivation", targetNamespace = "http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest", className = "com.tcl.dias.networkinventoryclient.netp.beans.PerformTransmissionServiceActivation")
    public void performTransmissionServiceActivation(
        @WebParam(name = "orderDetails", targetNamespace = "")
        OrderInfo2 orderDetails,
        @WebParam(name = "header", targetNamespace = "")
        ACEHeader header);

    /**
     * 
     * @param orderDetails
     * @param header
     */
    @WebMethod(action = "http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest/Binding/performIPIORActivation")
    @Oneway
    @RequestWrapper(localName = "performIPIORActivation", targetNamespace = "http://NetPServicesLibrary/netpsvc/wsdl/v1/NetPRequest", className = "com.tcl.dias.networkinventoryclient.netp.beans.PerformIPIORActivation")
    public void performIPIORActivation(
        @WebParam(name = "orderDetails", targetNamespace = "")
        IOROrderInfo orderDetails,
        @WebParam(name = "header", targetNamespace = "")
        ACEHeader header);

}
