//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.22 at 05:10:19 PM IST 
//


package com.tcl.dias.servicehandover.ipc.beans.invoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ackResponse" type="{http://WQMSENT/WQMSINT_BSSEGinvoiceOrder_WS.tws}BSSEResponseObject"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ackResponse"
})
@XmlRootElement(name = "createInvoiceResponse", namespace = "http://InstaccBSSE_WQMSInvoiceModule/createInvoice")
public class CreateInvoiceResponse {

    @XmlElement(namespace = "", required = true, nillable = true)
    protected BSSEResponseObject ackResponse;

    /**
     * Gets the value of the ackResponse property.
     * 
     * @return
     *     possible object is
     *     {@link BSSEResponseObject }
     *     
     */
    public BSSEResponseObject getAckResponse() {
        return ackResponse;
    }

    /**
     * Sets the value of the ackResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BSSEResponseObject }
     *     
     */
    public void setAckResponse(BSSEResponseObject value) {
        this.ackResponse = value;
    }

}
