//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 01:25:30 PM IST 
//


package com.tcl.dias.servicehandover.intl.account.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenevaProfileSaveInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenevaProfileSaveInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InvoiceMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillTermCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingCurrency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InfoCurrency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentTermCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingContactFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingContactLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingContactLandLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingContactMobile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingContactEmailId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingAddressLine1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingAddressLine2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingAddressLine3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingAddressLine4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingAddressLine5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillingPincode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WQMSID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenevaProfileSaveInfo", propOrder = {
    "invoiceMethod",
    "billTermCode",
    "billingCurrency",
    "infoCurrency",
    "paymentTermCode",
    "billingContactFirstName",
    "billingContactLastName",
    "billingContactLandLine",
    "billingContactMobile",
    "billingContactEmailId",
    "billingAddressLine1",
    "billingAddressLine2",
    "billingAddressLine3",
    "billingAddressLine4",
    "billingAddressLine5",
    "billingCity",
    "billingState",
    "billingCountry",
    "billingPincode",
    "wqmsid"
})
public class GenevaProfileSaveInfo {

    @XmlElement(name = "InvoiceMethod")
    protected String invoiceMethod;
    @XmlElement(name = "BillTermCode")
    protected String billTermCode;
    @XmlElement(name = "BillingCurrency")
    protected String billingCurrency;
    @XmlElement(name = "InfoCurrency")
    protected String infoCurrency;
    @XmlElement(name = "PaymentTermCode")
    protected String paymentTermCode;
    @XmlElement(name = "BillingContactFirstName")
    protected String billingContactFirstName;
    @XmlElement(name = "BillingContactLastName")
    protected String billingContactLastName;
    @XmlElement(name = "BillingContactLandLine")
    protected String billingContactLandLine;
    @XmlElement(name = "BillingContactMobile")
    protected String billingContactMobile;
    @XmlElement(name = "BillingContactEmailId")
    protected String billingContactEmailId;
    @XmlElement(name = "BillingAddressLine1")
    protected String billingAddressLine1;
    @XmlElement(name = "BillingAddressLine2")
    protected String billingAddressLine2;
    @XmlElement(name = "BillingAddressLine3")
    protected String billingAddressLine3;
    @XmlElement(name = "BillingAddressLine4")
    protected String billingAddressLine4;
    @XmlElement(name = "BillingAddressLine5")
    protected String billingAddressLine5;
    @XmlElement(name = "BillingCity")
    protected String billingCity;
    @XmlElement(name = "BillingState")
    protected String billingState;
    @XmlElement(name = "BillingCountry")
    protected String billingCountry;
    @XmlElement(name = "BillingPincode")
    protected String billingPincode;
    @XmlElement(name = "WQMSID")
    protected String wqmsid;

    /**
     * Gets the value of the invoiceMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceMethod() {
        return invoiceMethod;
    }

    /**
     * Sets the value of the invoiceMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceMethod(String value) {
        this.invoiceMethod = value;
    }

    /**
     * Gets the value of the billTermCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTermCode() {
        return billTermCode;
    }

    /**
     * Sets the value of the billTermCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTermCode(String value) {
        this.billTermCode = value;
    }

    /**
     * Gets the value of the billingCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingCurrency() {
        return billingCurrency;
    }

    /**
     * Sets the value of the billingCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingCurrency(String value) {
        this.billingCurrency = value;
    }

    /**
     * Gets the value of the infoCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoCurrency() {
        return infoCurrency;
    }

    /**
     * Sets the value of the infoCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoCurrency(String value) {
        this.infoCurrency = value;
    }

    /**
     * Gets the value of the paymentTermCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTermCode() {
        return paymentTermCode;
    }

    /**
     * Sets the value of the paymentTermCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTermCode(String value) {
        this.paymentTermCode = value;
    }

    /**
     * Gets the value of the billingContactFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingContactFirstName() {
        return billingContactFirstName;
    }

    /**
     * Sets the value of the billingContactFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingContactFirstName(String value) {
        this.billingContactFirstName = value;
    }

    /**
     * Gets the value of the billingContactLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingContactLastName() {
        return billingContactLastName;
    }

    /**
     * Sets the value of the billingContactLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingContactLastName(String value) {
        this.billingContactLastName = value;
    }

    /**
     * Gets the value of the billingContactLandLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingContactLandLine() {
        return billingContactLandLine;
    }

    /**
     * Sets the value of the billingContactLandLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingContactLandLine(String value) {
        this.billingContactLandLine = value;
    }

    /**
     * Gets the value of the billingContactMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingContactMobile() {
        return billingContactMobile;
    }

    /**
     * Sets the value of the billingContactMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingContactMobile(String value) {
        this.billingContactMobile = value;
    }

    /**
     * Gets the value of the billingContactEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingContactEmailId() {
        return billingContactEmailId;
    }

    /**
     * Sets the value of the billingContactEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingContactEmailId(String value) {
        this.billingContactEmailId = value;
    }

    /**
     * Gets the value of the billingAddressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAddressLine1() {
        return billingAddressLine1;
    }

    /**
     * Sets the value of the billingAddressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAddressLine1(String value) {
        this.billingAddressLine1 = value;
    }

    /**
     * Gets the value of the billingAddressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAddressLine2() {
        return billingAddressLine2;
    }

    /**
     * Sets the value of the billingAddressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAddressLine2(String value) {
        this.billingAddressLine2 = value;
    }

    /**
     * Gets the value of the billingAddressLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAddressLine3() {
        return billingAddressLine3;
    }

    /**
     * Sets the value of the billingAddressLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAddressLine3(String value) {
        this.billingAddressLine3 = value;
    }

    /**
     * Gets the value of the billingAddressLine4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAddressLine4() {
        return billingAddressLine4;
    }

    /**
     * Sets the value of the billingAddressLine4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAddressLine4(String value) {
        this.billingAddressLine4 = value;
    }

    /**
     * Gets the value of the billingAddressLine5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAddressLine5() {
        return billingAddressLine5;
    }

    /**
     * Sets the value of the billingAddressLine5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAddressLine5(String value) {
        this.billingAddressLine5 = value;
    }

    /**
     * Gets the value of the billingCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingCity() {
        return billingCity;
    }

    /**
     * Sets the value of the billingCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingCity(String value) {
        this.billingCity = value;
    }

    /**
     * Gets the value of the billingState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingState() {
        return billingState;
    }

    /**
     * Sets the value of the billingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingState(String value) {
        this.billingState = value;
    }

    /**
     * Gets the value of the billingCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingCountry() {
        return billingCountry;
    }

    /**
     * Sets the value of the billingCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingCountry(String value) {
        this.billingCountry = value;
    }

    /**
     * Gets the value of the billingPincode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingPincode() {
        return billingPincode;
    }

    /**
     * Sets the value of the billingPincode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingPincode(String value) {
        this.billingPincode = value;
    }

    /**
     * Gets the value of the wqmsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWQMSID() {
        return wqmsid;
    }

    /**
     * Sets the value of the wqmsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWQMSID(String value) {
        this.wqmsid = value;
    }

}
