//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 01:25:30 PM IST 
//


package com.tcl.dias.servicehandover.intl.account.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tcl.dias.servicehandover.intl.account.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tcl.dias.servicehandover.intl.account.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetSECSProfile }
     * 
     */
    public SetSECSProfile createSetSECSProfile() {
        return new SetSECSProfile();
    }

    /**
     * Create an instance of {@link SetSECSProfileInput }
     * 
     */
    public SetSECSProfileInput createSetSECSProfileInput() {
        return new SetSECSProfileInput();
    }

    /**
     * Create an instance of {@link SetSECSProfileResponse }
     * 
     */
    public SetSECSProfileResponse createSetSECSProfileResponse() {
        return new SetSECSProfileResponse();
    }

    /**
     * Create an instance of {@link SetSECSProfileOutput }
     * 
     */
    public SetSECSProfileOutput createSetSECSProfileOutput() {
        return new SetSECSProfileOutput();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link GenevaProfileSaveInfo }
     * 
     */
    public GenevaProfileSaveInfo createGenevaProfileSaveInfo() {
        return new GenevaProfileSaveInfo();
    }

    /**
     * Create an instance of {@link AuditLog }
     * 
     */
    public AuditLog createAuditLog() {
        return new AuditLog();
    }

    /**
     * Create an instance of {@link SECSProfileSaveInfo }
     * 
     */
    public SECSProfileSaveInfo createSECSProfileSaveInfo() {
        return new SECSProfileSaveInfo();
    }

    /**
     * Create an instance of {@link Security }
     * 
     */
    public Security createSecurity() {
        return new Security();
    }

}
