//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 01:25:30 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://WS.InternationalCustomerMngmnt.com")
package com.tcl.dias.servicehandover.intl.account.beans;
