//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 01:25:30 PM IST 
//


package com.tcl.dias.servicehandover.intl.account.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SetSECSProfileOutput" type="{http://WS.InternationalCustomerMngmnt.com}SetSECSProfileOutput"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "setSECSProfileOutput"
})
@XmlRootElement(name = "setSECSProfileResponse", namespace = "http://WS.InternationalCustomerMngmnt.com/SetSECSProfile")
public class SetSECSProfileResponse {

    @XmlElement(name = "SetSECSProfileOutput", required = true, nillable = true)
    protected SetSECSProfileOutput setSECSProfileOutput;

    /**
     * Gets the value of the setSECSProfileOutput property.
     * 
     * @return
     *     possible object is
     *     {@link SetSECSProfileOutput }
     *     
     */
    public SetSECSProfileOutput getSetSECSProfileOutput() {
        return setSECSProfileOutput;
    }

    /**
     * Sets the value of the setSECSProfileOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetSECSProfileOutput }
     *     
     */
    public void setSetSECSProfileOutput(SetSECSProfileOutput value) {
        this.setSECSProfileOutput = value;
    }

}
