//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 01:25:30 PM IST 
//


package com.tcl.dias.servicehandover.intl.account.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SetSECSProfileInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SetSECSProfileInput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Security" type="{http://WS.InternationalCustomerMngmnt.com}Security" minOccurs="0"/&gt;
 *         &lt;element name="OrganizationNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="CompanyID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InputFlag" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ProflieRelNum" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="SECSProfileSaveInfo" type="{http://WS.InternationalCustomerMngmnt.com}SECSProfileSaveInfo" minOccurs="0"/&gt;
 *         &lt;element name="AuditLog" type="{http://WS.InternationalCustomerMngmnt.com}AuditLog" minOccurs="0"/&gt;
 *         &lt;element name="GenevaProfileSaveInfo" type="{http://WS.InternationalCustomerMngmnt.com}GenevaProfileSaveInfo" minOccurs="0"/&gt;
 *         &lt;element name="BillingMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CRN_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetSECSProfileInput", propOrder = {
    "security",
    "organizationNumber",
    "companyID",
    "inputFlag",
    "proflieRelNum",
    "secsProfileSaveInfo",
    "auditLog",
    "genevaProfileSaveInfo",
    "billingMethod",
    "crnid"
})
public class SetSECSProfileInput {

    @XmlElement(name = "Security")
    protected Security security;
    @XmlElement(name = "OrganizationNumber")
    protected Integer organizationNumber;
    @XmlElement(name = "CompanyID")
    protected String companyID;
    @XmlElement(name = "InputFlag")
    protected Integer inputFlag;
    @XmlElement(name = "ProflieRelNum")
    protected Integer proflieRelNum;
    @XmlElement(name = "SECSProfileSaveInfo")
    protected SECSProfileSaveInfo secsProfileSaveInfo;
    @XmlElement(name = "AuditLog")
    protected AuditLog auditLog;
    @XmlElement(name = "GenevaProfileSaveInfo")
    protected GenevaProfileSaveInfo genevaProfileSaveInfo;
    @XmlElement(name = "BillingMethod")
    protected String billingMethod;
    @XmlElement(name = "CRN_ID")
    protected String crnid;

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link Security }
     *     
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setSecurity(Security value) {
        this.security = value;
    }

    /**
     * Gets the value of the organizationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrganizationNumber() {
        return organizationNumber;
    }

    /**
     * Sets the value of the organizationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrganizationNumber(Integer value) {
        this.organizationNumber = value;
    }

    /**
     * Gets the value of the companyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyID() {
        return companyID;
    }

    /**
     * Sets the value of the companyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyID(String value) {
        this.companyID = value;
    }

    /**
     * Gets the value of the inputFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInputFlag() {
        return inputFlag;
    }

    /**
     * Sets the value of the inputFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInputFlag(Integer value) {
        this.inputFlag = value;
    }

    /**
     * Gets the value of the proflieRelNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProflieRelNum() {
        return proflieRelNum;
    }

    /**
     * Sets the value of the proflieRelNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProflieRelNum(Integer value) {
        this.proflieRelNum = value;
    }

    /**
     * Gets the value of the secsProfileSaveInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SECSProfileSaveInfo }
     *     
     */
    public SECSProfileSaveInfo getSECSProfileSaveInfo() {
        return secsProfileSaveInfo;
    }

    /**
     * Sets the value of the secsProfileSaveInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECSProfileSaveInfo }
     *     
     */
    public void setSECSProfileSaveInfo(SECSProfileSaveInfo value) {
        this.secsProfileSaveInfo = value;
    }

    /**
     * Gets the value of the auditLog property.
     * 
     * @return
     *     possible object is
     *     {@link AuditLog }
     *     
     */
    public AuditLog getAuditLog() {
        return auditLog;
    }

    /**
     * Sets the value of the auditLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditLog }
     *     
     */
    public void setAuditLog(AuditLog value) {
        this.auditLog = value;
    }

    /**
     * Gets the value of the genevaProfileSaveInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GenevaProfileSaveInfo }
     *     
     */
    public GenevaProfileSaveInfo getGenevaProfileSaveInfo() {
        return genevaProfileSaveInfo;
    }

    /**
     * Sets the value of the genevaProfileSaveInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenevaProfileSaveInfo }
     *     
     */
    public void setGenevaProfileSaveInfo(GenevaProfileSaveInfo value) {
        this.genevaProfileSaveInfo = value;
    }

    /**
     * Gets the value of the billingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingMethod() {
        return billingMethod;
    }

    /**
     * Sets the value of the billingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingMethod(String value) {
        this.billingMethod = value;
    }

    /**
     * Gets the value of the crnid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRNID() {
        return crnid;
    }

    /**
     * Sets the value of the crnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRNID(String value) {
        this.crnid = value;
    }

}
