<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GetServiceDowntimeDetailsExport1_GetServiceDowntimeDetailsHttp_Service" targetNamespace="http://ACE_ServiceDowntime_Module/GetServiceDowntimeDetails/Binding" xmlns:Port_0="http://ACE_ServiceDowntime_Module/GetServiceDowntimeDetails" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://ACE_ServiceDowntime_Module/GetServiceDowntimeDetails/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:import namespace="http://ACE_ServiceDowntime_Module/GetServiceDowntimeDetails" location="GetServiceDowntimeDetails.wsdl"/>
  <wsdl:binding name="GetServiceDowntimeDetailsExport1_GetServiceDowntimeDetailsHttpBinding" type="Port_0:GetServiceDowntimeDetails">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getServiceDowntimeDetails">
      <soap:operation soapAction=""/>
      <wsdl:input name="getServiceDowntimeDetailsRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getServiceDowntimeDetailsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getServiceDowntimeDetailsFault">
        <soap:fault name="getServiceDowntimeDetailsFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="submitServiceDowntimeFault">
      <soap:operation soapAction=""/>
      <wsdl:input name="submitServiceDowntimeFaultRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="submitServiceDowntimeFaultResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="submitDowntimeFault">
        <soap:fault name="submitDowntimeFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetServiceDowntimeDetailsExport1_GetServiceDowntimeDetailsHttpService">
    <wsdl:port name="GetServiceDowntimeDetailsExport1_GetServiceDowntimeDetailsHttpPort" binding="this:GetServiceDowntimeDetailsExport1_GetServiceDowntimeDetailsHttpBinding">
      <soap:address location="http://10.133.208.194/optimus-serviceactivation/api/ws/downtimeasync.wsdl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>