//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 03:13:07 PM IST 
//


package com.tcl.dias.serviceactivation.cramer.getipserviceasync.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddOnServices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddOnServices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="multicasting" type="{http://www.tcl.com/2012/09/csvc/inf}Multicasting" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddOnServices", propOrder = {
    "multicasting"
})
public class AddOnServices {

    protected Multicasting multicasting;

    /**
     * Gets the value of the multicasting property.
     * 
     * @return
     *     possible object is
     *     {@link Multicasting }
     *     
     */
    public Multicasting getMulticasting() {
        return multicasting;
    }

    /**
     * Sets the value of the multicasting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Multicasting }
     *     
     */
    public void setMulticasting(Multicasting value) {
        this.multicasting = value;
    }

	@Override
	public String toString() {
		return "AddOnServices [multicasting=" + multicasting + "]";
	}

    
    
}
