//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 03:13:07 PM IST 
//


package com.tcl.dias.serviceactivation.cramer.getipserviceasync.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CramerIPServiceInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CramerIPServiceInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.tcl.com/2012/09/csvc/xsd}Service"/>
 *         &lt;element ref="{http://www.tcl.com/2012/09/csvc/inf}lastmile" minOccurs="0"/>
 *         &lt;element name="addOnServices" type="{http://www.tcl.com/2012/09/csvc/inf}AddOnServices" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CramerIPServiceInfo", propOrder = {
    "service",
    "lastmile",
    "addOnServices"
})
public class CramerIPServiceInfo {

    @XmlElement(name = "Service", namespace = "http://www.tcl.com/2012/09/csvc/xsd", required = true)
    protected Service service;
    @XmlElement(namespace = "http://www.tcl.com/2012/09/csvc/xsd")
    protected Lastmile lastmile;
    protected AddOnServices addOnServices;

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link Service }
     *     
     */
    public Service getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link Service }
     *     
     */
    public void setService(Service value) {
        this.service = value;
    }

    /**
     * Gets the value of the lastmile property.
     * 
     * @return
     *     possible object is
     *     {@link Lastmile }
     *     
     */
    public Lastmile getLastmile() {
        return lastmile;
    }

    /**
     * Sets the value of the lastmile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lastmile }
     *     
     */
    public void setLastmile(Lastmile value) {
        this.lastmile = value;
    }

    /**
     * Gets the value of the addOnServices property.
     * 
     * @return
     *     possible object is
     *     {@link AddOnServices }
     *     
     */
    public AddOnServices getAddOnServices() {
        return addOnServices;
    }

    /**
     * Sets the value of the addOnServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddOnServices }
     *     
     */
    public void setAddOnServices(AddOnServices value) {
        this.addOnServices = value;
    }

	@Override
	public String toString() {
		return "CramerIPServiceInfo [service=" + service + ", lastmile=" + lastmile + ", addOnServices=" + addOnServices
				+ "]";
	}
    
    

}
