//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 03:13:07 PM IST 
//


package com.tcl.dias.serviceactivation.cramer.getipserviceasync.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CramerWimaxLastmile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CramerWimaxLastmile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BTSIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BTSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SectorID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BTSType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ManagementVID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CramerWimaxLastmile", propOrder = {
    "btsip",
    "btsName",
    "sectorID",
    "btsType",
    "managementVID"
})
public class CramerWimaxLastmile {

    @XmlElement(name = "BTSIP")
    protected String btsip;
    @XmlElement(name = "BTSName")
    protected String btsName;
    @XmlElement(name = "SectorID")
    protected String sectorID;
    @XmlElement(name = "BTSType")
    protected String btsType;
    @XmlElement(name = "ManagementVID")
    protected String managementVID;

    /**
     * Gets the value of the btsip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTSIP() {
        return btsip;
    }

    /**
     * Sets the value of the btsip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTSIP(String value) {
        this.btsip = value;
    }

    /**
     * Gets the value of the btsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTSName() {
        return btsName;
    }

    /**
     * Sets the value of the btsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTSName(String value) {
        this.btsName = value;
    }

    /**
     * Gets the value of the sectorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectorID() {
        return sectorID;
    }

    /**
     * Sets the value of the sectorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectorID(String value) {
        this.sectorID = value;
    }

    /**
     * Gets the value of the btsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTSType() {
        return btsType;
    }

    /**
     * Sets the value of the btsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTSType(String value) {
        this.btsType = value;
    }

    /**
     * Gets the value of the managementVID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementVID() {
        return managementVID;
    }

    /**
     * Sets the value of the managementVID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementVID(String value) {
        this.managementVID = value;
    }

	@Override
	public String toString() {
		return "CramerWimaxLastmile [btsip=" + btsip + ", btsName=" + btsName + ", sectorID=" + sectorID + ", btsType="
				+ btsType + ", managementVID=" + managementVID + "]";
	}

    
}
