//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 03:13:07 PM IST 
//


package com.tcl.dias.serviceactivation.cramer.getipserviceasync.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CramerVSATLastmile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CramerVSATLastmile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partnerASBRWanv4ip" type="{http://www.tcl.com/2012/09/csvc/inf}IPV4Address" minOccurs="0"/>
 *         &lt;element name="partnerASBRWanv6ip" type="{http://www.tcl.com/2012/09/csvc/inf}IPV6Address" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CramerVSATLastmile", propOrder = {
    "partnerASBRWanv4Ip",
    "partnerASBRWanv6Ip"
})
public class CramerVSATLastmile {

    @XmlElement(name = "partnerASBRWanv4ip")
    protected IPV4Address partnerASBRWanv4Ip;
    @XmlElement(name = "partnerASBRWanv6ip")
    protected IPV6Address partnerASBRWanv6Ip;

    /**
     * Gets the value of the partnerASBRWanv4Ip property.
     * 
     * @return
     *     possible object is
     *     {@link IPV4Address }
     *     
     */
    public IPV4Address getPartnerASBRWanv4Ip() {
        return partnerASBRWanv4Ip;
    }

    /**
     * Sets the value of the partnerASBRWanv4Ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPV4Address }
     *     
     */
    public void setPartnerASBRWanv4Ip(IPV4Address value) {
        this.partnerASBRWanv4Ip = value;
    }

    /**
     * Gets the value of the partnerASBRWanv6Ip property.
     * 
     * @return
     *     possible object is
     *     {@link IPV6Address }
     *     
     */
    public IPV6Address getPartnerASBRWanv6Ip() {
        return partnerASBRWanv6Ip;
    }

    /**
     * Sets the value of the partnerASBRWanv6Ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPV6Address }
     *     
     */
    public void setPartnerASBRWanv6Ip(IPV6Address value) {
        this.partnerASBRWanv6Ip = value;
    }

	@Override
	public String toString() {
		return "CramerVSATLastmile [partnerASBRWanv4Ip=" + partnerASBRWanv4Ip + ", partnerASBRWanv6Ip="
				+ partnerASBRWanv6Ip + "]";
	}

    
    
}
