//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 03:13:07 PM IST 
//


package com.tcl.dias.serviceactivation.cramer.getipserviceasync.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="wimaxLastMile" type="{http://www.tcl.com/2012/09/csvc/inf}CramerWimaxLastmile" minOccurs="0"/>
 *         &lt;element name="l3NNILastmile" type="{http://www.tcl.com/2012/09/csvc/inf}CramerL3NNILastmile" minOccurs="0"/>
 *         &lt;element name="VSATLastmile" type="{http://www.tcl.com/2012/09/csvc/inf}CramerVSATLastmile" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wimaxLastMile",
    "l3NNILastmile",
    "vsatLastmile"
})
@XmlRootElement(name = "lastmile")
public class Lastmile {

    protected CramerWimaxLastmile wimaxLastMile;
    protected CramerL3NNILastmile l3NNILastmile;
    @XmlElement(name = "VSATLastmile")
    protected CramerVSATLastmile vsatLastmile;

    /**
     * Gets the value of the wimaxLastMile property.
     * 
     * @return
     *     possible object is
     *     {@link CramerWimaxLastmile }
     *     
     */
    public CramerWimaxLastmile getWimaxLastMile() {
        return wimaxLastMile;
    }

    /**
     * Sets the value of the wimaxLastMile property.
     * 
     * @param value
     *     allowed object is
     *     {@link CramerWimaxLastmile }
     *     
     */
    public void setWimaxLastMile(CramerWimaxLastmile value) {
        this.wimaxLastMile = value;
    }

    /**
     * Gets the value of the l3NNILastmile property.
     * 
     * @return
     *     possible object is
     *     {@link CramerL3NNILastmile }
     *     
     */
    public CramerL3NNILastmile getL3NNILastmile() {
        return l3NNILastmile;
    }

    /**
     * Sets the value of the l3NNILastmile property.
     * 
     * @param value
     *     allowed object is
     *     {@link CramerL3NNILastmile }
     *     
     */
    public void setL3NNILastmile(CramerL3NNILastmile value) {
        this.l3NNILastmile = value;
    }

    /**
     * Gets the value of the vsatLastmile property.
     * 
     * @return
     *     possible object is
     *     {@link CramerVSATLastmile }
     *     
     */
    public CramerVSATLastmile getVSATLastmile() {
        return vsatLastmile;
    }

    /**
     * Sets the value of the vsatLastmile property.
     * 
     * @param value
     *     allowed object is
     *     {@link CramerVSATLastmile }
     *     
     */
    public void setVSATLastmile(CramerVSATLastmile value) {
        this.vsatLastmile = value;
    }

	@Override
	public String toString() {
		return "Lastmile [wimaxLastMile=" + wimaxLastMile + ", l3NNILastmile=" + l3NNILastmile + ", vsatLastmile="
				+ vsatLastmile + "]";
	}

    
}
