//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 03:13:07 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tcl.com/2012/09/csvc/inf")
package com.tcl.dias.serviceactivation.cramer.getipserviceasync.beans;
