//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 03:13:07 PM IST 
//


package com.tcl.dias.serviceactivation.cramer.getipserviceasync.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="iasService" type="{http://www.tcl.com/2012/09/csvc/inf}CramerIASService" minOccurs="0"/>
 *         &lt;element name="rwService" type="{http://www.tcl.com/2012/09/csvc/inf}CramerRWService" minOccurs="0"/>
 *         &lt;element name="ipsecService" type="{http://www.tcl.com/2012/09/csvc/inf}CramerIPSECService" minOccurs="0"/>
 *         &lt;element name="dmvpnService" type="{http://www.tcl.com/2012/09/csvc/inf}CramerDMVPNService" minOccurs="0"/>
 *         &lt;element name="l2VPNService" type="{http://www.tcl.com/2012/09/csvc/inf}CramerL2VPNService" minOccurs="0"/>
 *         &lt;element name="vplsService" type="{http://www.tcl.com/2012/09/csvc/inf}CramerVPLSService" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iasService",
    "rwService",
    "ipsecService",
    "dmvpnService",
    "l2VPNService",
    "vplsService"
})
@XmlRootElement(name = "Service")
public class Service {

    protected CramerIASService iasService;
    protected CramerRWService rwService;
    protected CramerIPSECService ipsecService;
    protected CramerDMVPNService dmvpnService;
    protected CramerL2VPNService l2VPNService;
    protected CramerVPLSService vplsService;

    /**
     * Gets the value of the iasService property.
     * 
     * @return
     *     possible object is
     *     {@link CramerIASService }
     *     
     */
    public CramerIASService getIasService() {
        return iasService;
    }

    /**
     * Sets the value of the iasService property.
     * 
     * @param value
     *     allowed object is
     *     {@link CramerIASService }
     *     
     */
    public void setIasService(CramerIASService value) {
        this.iasService = value;
    }

    /**
     * Gets the value of the rwService property.
     * 
     * @return
     *     possible object is
     *     {@link CramerRWService }
     *     
     */
    public CramerRWService getRwService() {
        return rwService;
    }

    /**
     * Sets the value of the rwService property.
     * 
     * @param value
     *     allowed object is
     *     {@link CramerRWService }
     *     
     */
    public void setRwService(CramerRWService value) {
        this.rwService = value;
    }

    /**
     * Gets the value of the ipsecService property.
     * 
     * @return
     *     possible object is
     *     {@link CramerIPSECService }
     *     
     */
    public CramerIPSECService getIpsecService() {
        return ipsecService;
    }

    /**
     * Sets the value of the ipsecService property.
     * 
     * @param value
     *     allowed object is
     *     {@link CramerIPSECService }
     *     
     */
    public void setIpsecService(CramerIPSECService value) {
        this.ipsecService = value;
    }

    /**
     * Gets the value of the dmvpnService property.
     * 
     * @return
     *     possible object is
     *     {@link CramerDMVPNService }
     *     
     */
    public CramerDMVPNService getDmvpnService() {
        return dmvpnService;
    }

    /**
     * Sets the value of the dmvpnService property.
     * 
     * @param value
     *     allowed object is
     *     {@link CramerDMVPNService }
     *     
     */
    public void setDmvpnService(CramerDMVPNService value) {
        this.dmvpnService = value;
    }

    /**
     * Gets the value of the l2VPNService property.
     * 
     * @return
     *     possible object is
     *     {@link CramerL2VPNService }
     *     
     */
    public CramerL2VPNService getL2VPNService() {
        return l2VPNService;
    }

    /**
     * Sets the value of the l2VPNService property.
     * 
     * @param value
     *     allowed object is
     *     {@link CramerL2VPNService }
     *     
     */
    public void setL2VPNService(CramerL2VPNService value) {
        this.l2VPNService = value;
    }

    /**
     * Gets the value of the vplsService property.
     * 
     * @return
     *     possible object is
     *     {@link CramerVPLSService }
     *     
     */
    public CramerVPLSService getVplsService() {
        return vplsService;
    }

    /**
     * Sets the value of the vplsService property.
     * 
     * @param value
     *     allowed object is
     *     {@link CramerVPLSService }
     *     
     */
    public void setVplsService(CramerVPLSService value) {
        this.vplsService = value;
    }

	@Override
	public String toString() {
		return "Service [iasService=" + iasService + ", rwService=" + rwService + ", ipsecService=" + ipsecService
				+ ", dmvpnService=" + dmvpnService + ", l2VPNService=" + l2VPNService + ", vplsService=" + vplsService
				+ "]";
	}

    
}
