//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 03:13:07 PM IST 
//


package com.tcl.dias.serviceactivation.cramer.getipserviceasync.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="BGP" type="{http://www.tcl.com/2012/09/csvc/inf}BGP"/>
 *         &lt;element name="EIGRP" type="{http://www.tcl.com/2012/09/csvc/inf}EIGRP"/>
 *         &lt;element name="OSPF" type="{http://www.tcl.com/2012/09/csvc/inf}OSPF"/>
 *         &lt;element name="Static" type="{http://www.tcl.com/2012/09/csvc/inf}Static" minOccurs="0"/>
 *         &lt;element name="RIP" type="{http://www.tcl.com/2012/09/csvc/inf}RIP" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bgp",
    "eigrp",
    "ospf",
    "_static",
    "rip"
})
@XmlRootElement(name = "wanRoutingProtocol")
public class WanRoutingProtocol {

    @XmlElement(name = "BGP")
    protected BGP bgp;
    @XmlElement(name = "EIGRP")
    protected EIGRP eigrp;
    @XmlElement(name = "OSPF")
    protected OSPF ospf;
    @XmlElement(name = "Static")
    protected Static _static;
    @XmlElement(name = "RIP")
    protected RIP rip;

    /**
     * Gets the value of the bgp property.
     * 
     * @return
     *     possible object is
     *     {@link BGP }
     *     
     */
    public BGP getBGP() {
        return bgp;
    }

    /**
     * Sets the value of the bgp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BGP }
     *     
     */
    public void setBGP(BGP value) {
        this.bgp = value;
    }

    /**
     * Gets the value of the eigrp property.
     * 
     * @return
     *     possible object is
     *     {@link EIGRP }
     *     
     */
    public EIGRP getEIGRP() {
        return eigrp;
    }

    /**
     * Sets the value of the eigrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link EIGRP }
     *     
     */
    public void setEIGRP(EIGRP value) {
        this.eigrp = value;
    }

    /**
     * Gets the value of the ospf property.
     * 
     * @return
     *     possible object is
     *     {@link OSPF }
     *     
     */
    public OSPF getOSPF() {
        return ospf;
    }

    /**
     * Sets the value of the ospf property.
     * 
     * @param value
     *     allowed object is
     *     {@link OSPF }
     *     
     */
    public void setOSPF(OSPF value) {
        this.ospf = value;
    }

    /**
     * Gets the value of the static property.
     * 
     * @return
     *     possible object is
     *     {@link Static }
     *     
     */
    public Static getStatic() {
        return _static;
    }

    /**
     * Sets the value of the static property.
     * 
     * @param value
     *     allowed object is
     *     {@link Static }
     *     
     */
    public void setStatic(Static value) {
        this._static = value;
    }

    /**
     * Gets the value of the rip property.
     * 
     * @return
     *     possible object is
     *     {@link RIP }
     *     
     */
    public RIP getRIP() {
        return rip;
    }

    /**
     * Sets the value of the rip property.
     * 
     * @param value
     *     allowed object is
     *     {@link RIP }
     *     
     */
    public void setRIP(RIP value) {
        this.rip = value;
    }

}
