//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 11:07:44 AM IST 
//


package com.tcl.dias.servicehandover.beans.sureaddress;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetZIPsWithinDistanceSimpleResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getZIPsWithinDistanceSimpleResult"
})
@XmlRootElement(name = "GetZIPsWithinDistanceSimpleResponse")
public class GetZIPsWithinDistanceSimpleResponse {

    @XmlElement(name = "GetZIPsWithinDistanceSimpleResult")
    protected String getZIPsWithinDistanceSimpleResult;

    /**
     * Gets the value of the getZIPsWithinDistanceSimpleResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetZIPsWithinDistanceSimpleResult() {
        return getZIPsWithinDistanceSimpleResult;
    }

    /**
     * Sets the value of the getZIPsWithinDistanceSimpleResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetZIPsWithinDistanceSimpleResult(String value) {
        this.getZIPsWithinDistanceSimpleResult = value;
    }

}
