
package com.tcl.dias.serviceactivation.cramer.isvalidbts.beans;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BTSValidation", targetNamespace = "http://cramerserviceslibrary/csvc/wsdl/v2/ws/bts", wsdlLocation = "http://uswv1vuap003a.vsnl.co.in:8080/Ace_E2E/ValidateBTS.cnms?wsdl")
public class BTSValidation_Service
    extends Service
{

    private final static URL BTSVALIDATION_WSDL_LOCATION;
    private final static WebServiceException BTSVALIDATION_EXCEPTION;
    private final static QName BTSVALIDATION_QNAME = new QName("http://cramerserviceslibrary/csvc/wsdl/v2/ws/bts", "BTSValidation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://uswv1vuap003a.vsnl.co.in:8080/Ace_E2E/ValidateBTS.cnms?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BTSVALIDATION_WSDL_LOCATION = url;
        BTSVALIDATION_EXCEPTION = e;
    }

    public BTSValidation_Service() {
        super(__getWsdlLocation(), BTSVALIDATION_QNAME);
    }

    public BTSValidation_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BTSVALIDATION_QNAME, features);
    }

    public BTSValidation_Service(URL wsdlLocation) {
        super(wsdlLocation, BTSVALIDATION_QNAME);
    }

    public BTSValidation_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BTSVALIDATION_QNAME, features);
    }

    public BTSValidation_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BTSValidation_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BTSValidation
     */
    @WebEndpoint(name = "BTSValidationPort")
    public BTSValidation getBTSValidationPort() {
        return super.getPort(new QName("http://cramerserviceslibrary/csvc/wsdl/v2/ws/bts", "BTSValidationPort"), BTSValidation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTSValidation
     */
    @WebEndpoint(name = "BTSValidationPort")
    public BTSValidation getBTSValidationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cramerserviceslibrary/csvc/wsdl/v2/ws/bts", "BTSValidationPort"), BTSValidation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BTSVALIDATION_EXCEPTION!= null) {
            throw BTSVALIDATION_EXCEPTION;
        }
        return BTSVALIDATION_WSDL_LOCATION;
    }

}
