//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.24 at 10:33:40 AM IST 
//


package com.tcl.dias.servicehandover.ipc.beans.customerdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomerContactDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerContactDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CntctPersonTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CntctPersonFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CntctPersonLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CntctPersonEmailId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CntctPersonLandLineNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CntctPersonFaxNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CntctPersonCellPhoneNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerContactDetails", propOrder = {
    "cntctPersonTitle",
    "cntctPersonFirstName",
    "cntctPersonLastName",
    "cntctPersonEmailId",
    "cntctPersonLandLineNo",
    "cntctPersonFaxNo",
    "cntctPersonCellPhoneNo"
})
public class CustomerContactDetails {

    @XmlElement(name = "CntctPersonTitle")
    protected String cntctPersonTitle;
    @XmlElement(name = "CntctPersonFirstName")
    protected String cntctPersonFirstName;
    @XmlElement(name = "CntctPersonLastName")
    protected String cntctPersonLastName;
    @XmlElement(name = "CntctPersonEmailId")
    protected String cntctPersonEmailId;
    @XmlElement(name = "CntctPersonLandLineNo")
    protected String cntctPersonLandLineNo;
    @XmlElement(name = "CntctPersonFaxNo")
    protected String cntctPersonFaxNo;
    @XmlElement(name = "CntctPersonCellPhoneNo")
    protected String cntctPersonCellPhoneNo;

    /**
     * Gets the value of the cntctPersonTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntctPersonTitle() {
        return cntctPersonTitle;
    }

    /**
     * Sets the value of the cntctPersonTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntctPersonTitle(String value) {
        this.cntctPersonTitle = value;
    }

    /**
     * Gets the value of the cntctPersonFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntctPersonFirstName() {
        return cntctPersonFirstName;
    }

    /**
     * Sets the value of the cntctPersonFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntctPersonFirstName(String value) {
        this.cntctPersonFirstName = value;
    }

    /**
     * Gets the value of the cntctPersonLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntctPersonLastName() {
        return cntctPersonLastName;
    }

    /**
     * Sets the value of the cntctPersonLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntctPersonLastName(String value) {
        this.cntctPersonLastName = value;
    }

    /**
     * Gets the value of the cntctPersonEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntctPersonEmailId() {
        return cntctPersonEmailId;
    }

    /**
     * Sets the value of the cntctPersonEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntctPersonEmailId(String value) {
        this.cntctPersonEmailId = value;
    }

    /**
     * Gets the value of the cntctPersonLandLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntctPersonLandLineNo() {
        return cntctPersonLandLineNo;
    }

    /**
     * Sets the value of the cntctPersonLandLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntctPersonLandLineNo(String value) {
        this.cntctPersonLandLineNo = value;
    }

    /**
     * Gets the value of the cntctPersonFaxNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntctPersonFaxNo() {
        return cntctPersonFaxNo;
    }

    /**
     * Sets the value of the cntctPersonFaxNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntctPersonFaxNo(String value) {
        this.cntctPersonFaxNo = value;
    }

    /**
     * Gets the value of the cntctPersonCellPhoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntctPersonCellPhoneNo() {
        return cntctPersonCellPhoneNo;
    }

    /**
     * Sets the value of the cntctPersonCellPhoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntctPersonCellPhoneNo(String value) {
        this.cntctPersonCellPhoneNo = value;
    }

}
