//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.24 at 10:33:40 AM IST 
//


package com.tcl.dias.servicehandover.ipc.beans.customerdata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tcl.dias.servicehandover.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tcl.dias.servicehandover.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCustomerAccountNumber }
     * 
     */
    public GetCustomerAccountNumber createGetCustomerAccountNumber() {
        return new GetCustomerAccountNumber();
    }

    /**
     * Create an instance of {@link GetCustomerAccountNumberInput }
     * 
     */
    public GetCustomerAccountNumberInput createGetCustomerAccountNumberInput() {
        return new GetCustomerAccountNumberInput();
    }

    /**
     * Create an instance of {@link GetCustomerAccountNumberResponse }
     * 
     */
    public GetCustomerAccountNumberResponse createGetCustomerAccountNumberResponse() {
        return new GetCustomerAccountNumberResponse();
    }

    /**
     * Create an instance of {@link GetCustomerAccountNumberOutput }
     * 
     */
    public GetCustomerAccountNumberOutput createGetCustomerAccountNumberOutput() {
        return new GetCustomerAccountNumberOutput();
    }

    /**
     * Create an instance of {@link GetCustomerDetails }
     * 
     */
    public GetCustomerDetails createGetCustomerDetails() {
        return new GetCustomerDetails();
    }

    /**
     * Create an instance of {@link GetCustomerDetailsInput }
     * 
     */
    public GetCustomerDetailsInput createGetCustomerDetailsInput() {
        return new GetCustomerDetailsInput();
    }

    /**
     * Create an instance of {@link GetCustomerDetailsResponse }
     * 
     */
    public GetCustomerDetailsResponse createGetCustomerDetailsResponse() {
        return new GetCustomerDetailsResponse();
    }

    /**
     * Create an instance of {@link GetCustomerDetailsOutput }
     * 
     */
    public GetCustomerDetailsOutput createGetCustomerDetailsOutput() {
        return new GetCustomerDetailsOutput();
    }

    /**
     * Create an instance of {@link GetCustomerGeneralInformation }
     * 
     */
    public GetCustomerGeneralInformation createGetCustomerGeneralInformation() {
        return new GetCustomerGeneralInformation();
    }

    /**
     * Create an instance of {@link GetCustomerGeneralInformationInput }
     * 
     */
    public GetCustomerGeneralInformationInput createGetCustomerGeneralInformationInput() {
        return new GetCustomerGeneralInformationInput();
    }

    /**
     * Create an instance of {@link GetCustomerGeneralInformationResponse }
     * 
     */
    public GetCustomerGeneralInformationResponse createGetCustomerGeneralInformationResponse() {
        return new GetCustomerGeneralInformationResponse();
    }

    /**
     * Create an instance of {@link GetCustomerGeneralInformationOutput }
     * 
     */
    public GetCustomerGeneralInformationOutput createGetCustomerGeneralInformationOutput() {
        return new GetCustomerGeneralInformationOutput();
    }

    /**
     * Create an instance of {@link GetCustomer }
     * 
     */
    public GetCustomer createGetCustomer() {
        return new GetCustomer();
    }

    /**
     * Create an instance of {@link GetCustomerInput }
     * 
     */
    public GetCustomerInput createGetCustomerInput() {
        return new GetCustomerInput();
    }

    /**
     * Create an instance of {@link GetCustomerResponse }
     * 
     */
    public GetCustomerResponse createGetCustomerResponse() {
        return new GetCustomerResponse();
    }

    /**
     * Create an instance of {@link GetCustomerOutput }
     * 
     */
    public GetCustomerOutput createGetCustomerOutput() {
        return new GetCustomerOutput();
    }

    /**
     * Create an instance of {@link CustomerHQAddress }
     * 
     */
    public CustomerHQAddress createCustomerHQAddress() {
        return new CustomerHQAddress();
    }

    /**
     * Create an instance of {@link CustomerInformation }
     * 
     */
    public CustomerInformation createCustomerInformation() {
        return new CustomerInformation();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link Security }
     * 
     */
    public Security createSecurity() {
        return new Security();
    }

    /**
     * Create an instance of {@link CustomerContactDetails }
     * 
     */
    public CustomerContactDetails createCustomerContactDetails() {
        return new CustomerContactDetails();
    }

    /**
     * Create an instance of {@link CustomerPersonalInformation }
     * 
     */
    public CustomerPersonalInformation createCustomerPersonalInformation() {
        return new CustomerPersonalInformation();
    }

    /**
     * Create an instance of {@link AccountBillingAddress }
     * 
     */
    public AccountBillingAddress createAccountBillingAddress() {
        return new AccountBillingAddress();
    }

    /**
     * Create an instance of {@link AccountContactDetails }
     * 
     */
    public AccountContactDetails createAccountContactDetails() {
        return new AccountContactDetails();
    }

    /**
     * Create an instance of {@link AccountInformation }
     * 
     */
    public AccountInformation createAccountInformation() {
        return new AccountInformation();
    }

    /**
     * Create an instance of {@link CustomerDetails }
     * 
     */
    public CustomerDetails createCustomerDetails() {
        return new CustomerDetails();
    }

    /**
     * Create an instance of {@link AccountServiceInformation }
     * 
     */
    public AccountServiceInformation createAccountServiceInformation() {
        return new AccountServiceInformation();
    }

}
