//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.24 at 10:33:40 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://WS.CustomerManagement.com")
package com.tcl.dias.servicehandover.ipc.beans.customerdata;
