
package com.tcl.dias.oms.cisco.beans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "B2BService_b2b_AcquireQuotePortType", targetNamespace = "http://www.openapplications.org/oagis/9")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface B2BServiceB2BAcquireQuotePortType {


    /**
     * 
     * @param getQuoteInputType
     * @return
     *     returns org.openapplications.oagis._9.ShowQuoteType
     */
    @WebMethod(operationName = "Mesha_AcquireQuoteProxy_H", action = "urn:pushB2BAction")
    @WebResult(name = "ShowQuote", targetNamespace = "http://www.openapplications.org/oagis/9", partName = "showQuoteOutputType")
    public ShowQuoteType meshaAcquireQuoteProxyH(
            @WebParam(name = "GetQuote", targetNamespace = "http://www.openapplications.org/oagis/9", partName = "getQuoteInputType")
                    GetQuoteType getQuoteInputType);

}
