//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.30 at 06:34:20 PM IST 
//


package com.tcl.dias.oms.cisco.beans;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.optimus.cisco package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Messaging_QNAME = new QName("http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", "Messaging");
    private final static QName _PullResponse_QNAME = new QName("http://ciscoB2BService.ws.cisco.com", "PullResponse");
    private final static QName _PushRequest_QNAME = new QName("http://ciscoB2BService.ws.cisco.com", "PushRequest");
    private final static QName _CiscoExtensions_QNAME = new QName("urn:cisco:b2bngc:services:1.0", "CiscoExtensions");
    private final static QName _CiscoHeader_QNAME = new QName("urn:cisco:b2bngc:services:1.0", "CiscoHeader");
    private final static QName _CiscoLine_QNAME = new QName("urn:cisco:b2bngc:services:1.0", "CiscoLine");
    private final static QName _ConfigurationMessages_QNAME = new QName("urn:cisco:b2bngc:services:1.0", "ConfigurationMessages");
    private final static QName _ConfigurationReference_QNAME = new QName("urn:cisco:b2bngc:services:1.0", "ConfigurationReference");
    private final static QName _ConfiguratorInformation_QNAME = new QName("urn:cisco:b2bngc:services:1.0", "ConfiguratorInformation");
    private final static QName _PriceList_QNAME = new QName("urn:cisco:b2bngc:services:1.0", "PriceList");
    private final static QName _ShowQuote_QNAME = new QName("http://www.openapplications.org/oagis/9", "ShowQuote");
    private final static QName _GetQuote_QNAME = new QName("http://www.openapplications.org/oagis/9", "GetQuote");
    private final static QName _Quote_QNAME = new QName("http://www.openapplications.org/oagis/9", "Quote");
    private final static QName _QuoteHeader_QNAME = new QName("http://www.openapplications.org/oagis/9", "QuoteHeader");
    private final static QName _QuoteLine_QNAME = new QName("http://www.openapplications.org/oagis/9", "QuoteLine");
    private final static QName _QualificationTerm_QNAME = new QName("http://www.openapplications.org/oagis/9", "QualificationTerm");
    private final static QName _Address_QNAME = new QName("http://www.openapplications.org/oagis/9", "Address");
    private final static QName _Allowance_QNAME = new QName("http://www.openapplications.org/oagis/9", "Allowance");
    private final static QName _BillToParty_QNAME = new QName("http://www.openapplications.org/oagis/9", "BillToParty");
    private final static QName _Classification_QNAME = new QName("http://www.openapplications.org/oagis/9", "Classification");
    private final static QName _Contact_QNAME = new QName("http://www.openapplications.org/oagis/9", "Contact");
    private final static QName _Discount_QNAME = new QName("http://www.openapplications.org/oagis/9", "Discount");
    private final static QName _DocumentID_QNAME = new QName("http://www.openapplications.org/oagis/9", "DocumentID");
    private final static QName _EMailAddressCommunication_QNAME = new QName("http://www.openapplications.org/oagis/9", "EMailAddressCommunication");
    private final static QName _EffectiveTimePeriod_QNAME = new QName("http://www.openapplications.org/oagis/9", "EffectiveTimePeriod");
    private final static QName _Effectivity_QNAME = new QName("http://www.openapplications.org/oagis/9", "Effectivity");
    private final static QName _FormattedNumber_QNAME = new QName("http://www.openapplications.org/oagis/9", "FormattedNumber");
    private final static QName _Item_QNAME = new QName("http://www.openapplications.org/oagis/9", "Item");
    private final static QName _ItemID_QNAME = new QName("http://www.openapplications.org/oagis/9", "ItemID");
    private final static QName _Location_QNAME = new QName("http://www.openapplications.org/oagis/9", "Location");
    private final static QName _Party_QNAME = new QName("http://www.openapplications.org/oagis/9", "Party");
    private final static QName _PartyIDs_QNAME = new QName("http://www.openapplications.org/oagis/9", "PartyIDs");
    private final static QName _PaymentTerm_QNAME = new QName("http://www.openapplications.org/oagis/9", "PaymentTerm");
    private final static QName _Property_QNAME = new QName("http://www.openapplications.org/oagis/9", "Property");
    private final static QName _Specification_QNAME = new QName("http://www.openapplications.org/oagis/9", "Specification");
    private final static QName _Status_QNAME = new QName("http://www.openapplications.org/oagis/9", "Status");
    private final static QName _TelephoneCommunication_QNAME = new QName("http://www.openapplications.org/oagis/9", "TelephoneCommunication");
    private final static QName _UnitPrice_QNAME = new QName("http://www.openapplications.org/oagis/9", "UnitPrice");
    private final static QName _ApplicationArea_QNAME = new QName("http://www.openapplications.org/oagis/9", "ApplicationArea");
    private final static QName _BODID_QNAME = new QName("http://www.openapplications.org/oagis/9", "BODID");
    private final static QName _ChangeStatus_QNAME = new QName("http://www.openapplications.org/oagis/9", "ChangeStatus");
    private final static QName _ComponentID_QNAME = new QName("http://www.openapplications.org/oagis/9", "ComponentID");
    private final static QName _CreationDateTime_QNAME = new QName("http://www.openapplications.org/oagis/9", "CreationDateTime");
    private final static QName _Expression_QNAME = new QName("http://www.openapplications.org/oagis/9", "Expression");
    private final static QName _Get_QNAME = new QName("http://www.openapplications.org/oagis/9", "Get");
    private final static QName _LogicalID_QNAME = new QName("http://www.openapplications.org/oagis/9", "LogicalID");
    private final static QName _Receiver_QNAME = new QName("http://www.openapplications.org/oagis/9", "Receiver");
    private final static QName _ReferenceID_QNAME = new QName("http://www.openapplications.org/oagis/9", "ReferenceID");
    private final static QName _ResponseCriteria_QNAME = new QName("http://www.openapplications.org/oagis/9", "ResponseCriteria");
    private final static QName _Sender_QNAME = new QName("http://www.openapplications.org/oagis/9", "Sender");
    private final static QName _Show_QNAME = new QName("http://www.openapplications.org/oagis/9", "Show");
    private final static QName _Amount_QNAME = new QName("http://www.openapplications.org/oagis/9", "Amount");
    private final static QName _Text_QNAME = new QName("http://www.openapplications.org/oagis/9", "Text");
    private final static QName _AuthorizationID_QNAME = new QName("http://www.openapplications.org/oagis/9", "AuthorizationID");
    private final static QName _CityName_QNAME = new QName("http://www.openapplications.org/oagis/9", "CityName");
    private final static QName _Code_QNAME = new QName("http://www.openapplications.org/oagis/9", "Code");
    private final static QName _CountryCode_QNAME = new QName("http://www.openapplications.org/oagis/9", "CountryCode");
    private final static QName _CountrySubDivisionCode_QNAME = new QName("http://www.openapplications.org/oagis/9", "CountrySubDivisionCode");
    private final static QName _Description_QNAME = new QName("http://www.openapplications.org/oagis/9", "Description");
    private final static QName _DiscountPercent_QNAME = new QName("http://www.openapplications.org/oagis/9", "DiscountPercent");
    private final static QName _DocumentDateTime_QNAME = new QName("http://www.openapplications.org/oagis/9", "DocumentDateTime");
    private final static QName _Duration_QNAME = new QName("http://www.openapplications.org/oagis/9", "Duration");
    private final static QName _EMailAddressID_QNAME = new QName("http://www.openapplications.org/oagis/9", "EMailAddressID");
    private final static QName _EndDateTime_QNAME = new QName("http://www.openapplications.org/oagis/9", "EndDateTime");
    private final static QName _ExtendedAmount_QNAME = new QName("http://www.openapplications.org/oagis/9", "ExtendedAmount");
    private final static QName _ID_QNAME = new QName("http://www.openapplications.org/oagis/9", "ID");
    private final static QName _JobTitle_QNAME = new QName("http://www.openapplications.org/oagis/9", "JobTitle");
    private final static QName _LastModificationDateTime_QNAME = new QName("http://www.openapplications.org/oagis/9", "LastModificationDateTime");
    private final static QName _LineNumber_QNAME = new QName("http://www.openapplications.org/oagis/9", "LineNumber");
    private final static QName _AddressLine_QNAME = new QName("http://www.openapplications.org/oagis/9", "AddressLine");
    private final static QName _LineOne_QNAME = new QName("http://www.openapplications.org/oagis/9", "LineOne");
    private final static QName _LineThree_QNAME = new QName("http://www.openapplications.org/oagis/9", "LineThree");
    private final static QName _LineTwo_QNAME = new QName("http://www.openapplications.org/oagis/9", "LineTwo");
    private final static QName _Name_QNAME = new QName("http://www.openapplications.org/oagis/9", "Name");
    private final static QName _NameValue_QNAME = new QName("http://www.openapplications.org/oagis/9", "NameValue");
    private final static QName _ParentID_QNAME = new QName("http://www.openapplications.org/oagis/9", "ParentID");
    private final static QName _PostalCode_QNAME = new QName("http://www.openapplications.org/oagis/9", "PostalCode");
    private final static QName _Quantity_QNAME = new QName("http://www.openapplications.org/oagis/9", "Quantity");
    private final static QName _Reason_QNAME = new QName("http://www.openapplications.org/oagis/9", "Reason");
    private final static QName _TotalAmount_QNAME = new QName("http://www.openapplications.org/oagis/9", "TotalAmount");
    private final static QName _Type_QNAME = new QName("http://www.openapplications.org/oagis/9", "Type");
    private final static QName _Extension_QNAME = new QName("http://www.openapplications.org/oagis/9", "Extension");
    private final static QName _UserArea_QNAME = new QName("http://www.openapplications.org/oagis/9", "UserArea");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.optimus.cisco
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NonRepudiationInformation }
     * 
     */
    public NonRepudiationInformation createNonRepudiationInformation() {
        return new NonRepudiationInformation();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Messaging }
     * 
     */
    public Messaging createMessaging() {
        return new Messaging();
    }

    /**
     * Create an instance of {@link NonRepudiationInformation.MessagePartNRInformation }
     * 
     */
    public NonRepudiationInformation.MessagePartNRInformation createNonRepudiationInformationMessagePartNRInformation() {
        return new NonRepudiationInformation.MessagePartNRInformation();
    }

    /**
     * Create an instance of {@link Reference.DigestMethod }
     * 
     */
    public Reference.DigestMethod createReferenceDigestMethod() {
        return new Reference.DigestMethod();
    }

    /**
     * Create an instance of {@link SignalMessage }
     * 
     */
    public SignalMessage createSignalMessage() {
        return new SignalMessage();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link PullRequest }
     * 
     */
    public PullRequest createPullRequest() {
        return new PullRequest();
    }

    /**
     * Create an instance of {@link Receipt }
     * 
     */
    public Receipt createReceipt() {
        return new Receipt();
    }

    /**
     * Create an instance of {@link UserMessage }
     * 
     */
    public UserMessage createUserMessage() {
        return new UserMessage();
    }

    /**
     * Create an instance of {@link MessageInfo }
     * 
     */
    public MessageInfo createMessageInfo() {
        return new MessageInfo();
    }

    /**
     * Create an instance of {@link PartyInfo }
     * 
     */
    public PartyInfo createPartyInfo() {
        return new PartyInfo();
    }

    /**
     * Create an instance of {@link PartyId }
     * 
     */
    public PartyId createPartyId() {
        return new PartyId();
    }

    /**
     * Create an instance of {@link From }
     * 
     */
    public From createFrom() {
        return new From();
    }

    /**
     * Create an instance of {@link To }
     * 
     */
    public To createTo() {
        return new To();
    }

    /**
     * Create an instance of {@link CollaborationInfo }
     * 
     */
    public CollaborationInfo createCollaborationInfo() {
        return new CollaborationInfo();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link AgreementRef }
     * 
     */
    public AgreementRef createAgreementRef() {
        return new AgreementRef();
    }

    /**
     * Create an instance of {@link PayloadInfo }
     * 
     */
    public PayloadInfo createPayloadInfo() {
        return new PayloadInfo();
    }

    /**
     * Create an instance of {@link PartInfo }
     * 
     */
    public PartInfo createPartInfo() {
        return new PartInfo();
    }

    /**
     * Create an instance of {@link Schema }
     * 
     */
    public Schema createSchema() {
        return new Schema();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link PartProperties }
     * 
     */
    public PartProperties createPartProperties() {
        return new PartProperties();
    }

    /**
     * Create an instance of {@link MessageProperties }
     * 
     */
    public MessageProperties createMessageProperties() {
        return new MessageProperties();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link CiscoExtensionsType }
     * 
     */
    public CiscoExtensionsType createCiscoExtensionsType() {
        return new CiscoExtensionsType();
    }

    /**
     * Create an instance of {@link CiscoHeaderType }
     * 
     */
    public CiscoHeaderType createCiscoHeaderType() {
        return new CiscoHeaderType();
    }

    /**
     * Create an instance of {@link CiscoLineType }
     * 
     */
    public CiscoLineType createCiscoLineType() {
        return new CiscoLineType();
    }

    /**
     * Create an instance of {@link ConfigurationMessagesType }
     * 
     */
    public ConfigurationMessagesType createConfigurationMessagesType() {
        return new ConfigurationMessagesType();
    }

    /**
     * Create an instance of {@link ConfigurationReferenceType }
     * 
     */
    public ConfigurationReferenceType createConfigurationReferenceType() {
        return new ConfigurationReferenceType();
    }

    /**
     * Create an instance of {@link ConfiguratorInformationType }
     * 
     */
    public ConfiguratorInformationType createConfiguratorInformationType() {
        return new ConfiguratorInformationType();
    }

    /**
     * Create an instance of {@link PriceListType }
     * 
     */
    public PriceListType createPriceListType() {
        return new PriceListType();
    }

    /**
     * Create an instance of {@link ShowQuoteType }
     * 
     */
    public ShowQuoteType createShowQuoteType() {
        return new ShowQuoteType();
    }

    /**
     * Create an instance of {@link GetQuoteType }
     * 
     */
    public GetQuoteType createGetQuoteType() {
        return new GetQuoteType();
    }

    /**
     * Create an instance of {@link QuoteType }
     * 
     */
    public QuoteType createQuoteType() {
        return new QuoteType();
    }

    /**
     * Create an instance of {@link QuoteHeaderType }
     * 
     */
    public QuoteHeaderType createQuoteHeaderType() {
        return new QuoteHeaderType();
    }

    /**
     * Create an instance of {@link QuoteLineType }
     * 
     */
    public QuoteLineType createQuoteLineType() {
        return new QuoteLineType();
    }

    /**
     * Create an instance of {@link QualificationTermType }
     * 
     */
    public QualificationTermType createQualificationTermType() {
        return new QualificationTermType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link AllowanceType }
     * 
     */
    public AllowanceType createAllowanceType() {
        return new AllowanceType();
    }

    /**
     * Create an instance of {@link CustomerPartyType }
     * 
     */
    public CustomerPartyType createCustomerPartyType() {
        return new CustomerPartyType();
    }

    /**
     * Create an instance of {@link ClassificationType }
     * 
     */
    public ClassificationType createClassificationType() {
        return new ClassificationType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link TermType }
     * 
     */
    public TermType createTermType() {
        return new TermType();
    }

    /**
     * Create an instance of {@link DocumentIDType }
     * 
     */
    public DocumentIDType createDocumentIDType() {
        return new DocumentIDType();
    }

    /**
     * Create an instance of {@link EMailAddressCommunicationType }
     * 
     */
    public EMailAddressCommunicationType createEMailAddressCommunicationType() {
        return new EMailAddressCommunicationType();
    }

    /**
     * Create an instance of {@link TimePeriodType }
     * 
     */
    public TimePeriodType createTimePeriodType() {
        return new TimePeriodType();
    }

    /**
     * Create an instance of {@link EffectivityType }
     * 
     */
    public EffectivityType createEffectivityType() {
        return new EffectivityType();
    }

    /**
     * Create an instance of {@link TextType2 }
     * 
     */
    public TextType2 createTextType2() {
        return new TextType2();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link ItemIDType }
     * 
     */
    public ItemIDType createItemIDType() {
        return new ItemIDType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link PartyType }
     * 
     */
    public PartyType createPartyType() {
        return new PartyType();
    }

    /**
     * Create an instance of {@link PartyIDsType }
     * 
     */
    public PartyIDsType createPartyIDsType() {
        return new PartyIDsType();
    }

    /**
     * Create an instance of {@link PaymentTermType }
     * 
     */
    public PaymentTermType createPaymentTermType() {
        return new PaymentTermType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link SpecificationType }
     * 
     */
    public SpecificationType createSpecificationType() {
        return new SpecificationType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link TelephoneCommunicationType }
     * 
     */
    public TelephoneCommunicationType createTelephoneCommunicationType() {
        return new TelephoneCommunicationType();
    }

    /**
     * Create an instance of {@link PriceABIEType }
     * 
     */
    public PriceABIEType createPriceABIEType() {
        return new PriceABIEType();
    }

    /**
     * Create an instance of {@link ApplicationAreaType }
     * 
     */
    public ApplicationAreaType createApplicationAreaType() {
        return new ApplicationAreaType();
    }

    /**
     * Create an instance of {@link IdentifierType2 }
     * 
     */
    public IdentifierType2 createIdentifierType2() {
        return new IdentifierType2();
    }

    /**
     * Create an instance of {@link ChangeStatusType }
     * 
     */
    public ChangeStatusType createChangeStatusType() {
        return new ChangeStatusType();
    }

    /**
     * Create an instance of {@link ExpressionType }
     * 
     */
    public ExpressionType createExpressionType() {
        return new ExpressionType();
    }

    /**
     * Create an instance of {@link GetType }
     * 
     */
    public GetType createGetType() {
        return new GetType();
    }

    /**
     * Create an instance of {@link ReceiverType }
     * 
     */
    public ReceiverType createReceiverType() {
        return new ReceiverType();
    }

    /**
     * Create an instance of {@link ResponseActionCriteriaType }
     * 
     */
    public ResponseActionCriteriaType createResponseActionCriteriaType() {
        return new ResponseActionCriteriaType();
    }

    /**
     * Create an instance of {@link SenderType }
     * 
     */
    public SenderType createSenderType() {
        return new SenderType();
    }

    /**
     * Create an instance of {@link ShowType }
     * 
     */
    public ShowType createShowType() {
        return new ShowType();
    }

    /**
     * Create an instance of {@link AmountType2 }
     * 
     */
    public AmountType2 createAmountType2() {
        return new AmountType2();
    }

    /**
     * Create an instance of {@link NameType2 }
     * 
     */
    public NameType2 createNameType2() {
        return new NameType2();
    }

    /**
     * Create an instance of {@link CodeType2 }
     * 
     */
    public CodeType2 createCodeType2() {
        return new CodeType2();
    }

    /**
     * Create an instance of {@link CountryCodeType }
     * 
     */
    public CountryCodeType createCountryCodeType() {
        return new CountryCodeType();
    }

    /**
     * Create an instance of {@link CountrySubDivisionCodeType }
     * 
     */
    public CountrySubDivisionCodeType createCountrySubDivisionCodeType() {
        return new CountrySubDivisionCodeType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link SequencedTextType }
     * 
     */
    public SequencedTextType createSequencedTextType() {
        return new SequencedTextType();
    }

    /**
     * Create an instance of {@link NameValuePairType }
     * 
     */
    public NameValuePairType createNameValuePairType() {
        return new NameValuePairType();
    }

    /**
     * Create an instance of {@link QuantityType2 }
     * 
     */
    public QuantityType2 createQuantityType2() {
        return new QuantityType2();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link UserAreaType }
     * 
     */
    public UserAreaType createUserAreaType() {
        return new UserAreaType();
    }

    /**
     * Create an instance of {@link ShowQuoteDataAreaType }
     * 
     */
    public ShowQuoteDataAreaType createShowQuoteDataAreaType() {
        return new ShowQuoteDataAreaType();
    }

    /**
     * Create an instance of {@link GetQuoteDataAreaType }
     * 
     */
    public GetQuoteDataAreaType createGetQuoteDataAreaType() {
        return new GetQuoteDataAreaType();
    }

    /**
     * Create an instance of {@link ProcurementHeaderType }
     * 
     */
    public ProcurementHeaderType createProcurementHeaderType() {
        return new ProcurementHeaderType();
    }

    /**
     * Create an instance of {@link ProcurementLineType }
     * 
     */
    public ProcurementLineType createProcurementLineType() {
        return new ProcurementLineType();
    }

    /**
     * Create an instance of {@link RequestLineType }
     * 
     */
    public RequestLineType createRequestLineType() {
        return new RequestLineType();
    }

    /**
     * Create an instance of {@link AmountPerQuantityType }
     * 
     */
    public AmountPerQuantityType createAmountPerQuantityType() {
        return new AmountPerQuantityType();
    }

    /**
     * Create an instance of {@link LineType }
     * 
     */
    public LineType createLineType() {
        return new LineType();
    }

    /**
     * Create an instance of {@link LocationABIEType }
     * 
     */
    public LocationABIEType createLocationABIEType() {
        return new LocationABIEType();
    }

    /**
     * Create an instance of {@link NamedIDType }
     * 
     */
    public NamedIDType createNamedIDType() {
        return new NamedIDType();
    }

    /**
     * Create an instance of {@link OpenPartyType }
     * 
     */
    public OpenPartyType createOpenPartyType() {
        return new OpenPartyType();
    }

    /**
     * Create an instance of {@link PayerPartyBaseType }
     * 
     */
    public PayerPartyBaseType createPayerPartyBaseType() {
        return new PayerPartyBaseType();
    }

    /**
     * Create an instance of {@link SemanticContactType }
     * 
     */
    public SemanticContactType createSemanticContactType() {
        return new SemanticContactType();
    }

    /**
     * Create an instance of {@link SeparatedDateTimeType }
     * 
     */
    public SeparatedDateTimeType createSeparatedDateTimeType() {
        return new SeparatedDateTimeType();
    }

    /**
     * Create an instance of {@link SequencedCodesType }
     * 
     */
    public SequencedCodesType createSequencedCodesType() {
        return new SequencedCodesType();
    }

    /**
     * Create an instance of {@link StatusABIEType }
     * 
     */
    public StatusABIEType createStatusABIEType() {
        return new StatusABIEType();
    }

    /**
     * Create an instance of {@link StatusEnabledHeaderType }
     * 
     */
    public StatusEnabledHeaderType createStatusEnabledHeaderType() {
        return new StatusEnabledHeaderType();
    }

    /**
     * Create an instance of {@link StatusEnabledLineType }
     * 
     */
    public StatusEnabledLineType createStatusEnabledLineType() {
        return new StatusEnabledLineType();
    }

    /**
     * Create an instance of {@link TermABIEType }
     * 
     */
    public TermABIEType createTermABIEType() {
        return new TermABIEType();
    }

    /**
     * Create an instance of {@link TimePeriodABIEType }
     * 
     */
    public TimePeriodABIEType createTimePeriodABIEType() {
        return new TimePeriodABIEType();
    }

    /**
     * Create an instance of {@link BusinessObjectDocumentType }
     * 
     */
    public BusinessObjectDocumentType createBusinessObjectDocumentType() {
        return new BusinessObjectDocumentType();
    }

    /**
     * Create an instance of {@link StatusBasisType }
     * 
     */
    public StatusBasisType createStatusBasisType() {
        return new StatusBasisType();
    }

    /**
     * Create an instance of {@link SequencedCodeType }
     * 
     */
    public SequencedCodeType createSequencedCodeType() {
        return new SequencedCodeType();
    }

    /**
     * Create an instance of {@link SequencedIDType }
     * 
     */
    public SequencedIDType createSequencedIDType() {
        return new SequencedIDType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Messaging }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", name = "Messaging")
    public JAXBElement<Messaging> createMessaging(Messaging value) {
        return new JAXBElement<Messaging>(_Messaging_QNAME, Messaging.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ciscoB2BService.ws.cisco.com", name = "PullResponse")
    public JAXBElement<Object> createPullResponse(Object value) {
        return new JAXBElement<Object>(_PullResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ciscoB2BService.ws.cisco.com", name = "PushRequest")
    public JAXBElement<Object> createPushRequest(Object value) {
        return new JAXBElement<Object>(_PushRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CiscoExtensionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cisco:b2bngc:services:1.0", name = "CiscoExtensions")
    public JAXBElement<CiscoExtensionsType> createCiscoExtensions(CiscoExtensionsType value) {
        return new JAXBElement<CiscoExtensionsType>(_CiscoExtensions_QNAME, CiscoExtensionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CiscoHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cisco:b2bngc:services:1.0", name = "CiscoHeader")
    public JAXBElement<CiscoHeaderType> createCiscoHeader(CiscoHeaderType value) {
        return new JAXBElement<CiscoHeaderType>(_CiscoHeader_QNAME, CiscoHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CiscoLineType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cisco:b2bngc:services:1.0", name = "CiscoLine")
    public JAXBElement<CiscoLineType> createCiscoLine(CiscoLineType value) {
        return new JAXBElement<CiscoLineType>(_CiscoLine_QNAME, CiscoLineType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigurationMessagesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cisco:b2bngc:services:1.0", name = "ConfigurationMessages")
    public JAXBElement<ConfigurationMessagesType> createConfigurationMessages(ConfigurationMessagesType value) {
        return new JAXBElement<ConfigurationMessagesType>(_ConfigurationMessages_QNAME, ConfigurationMessagesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigurationReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cisco:b2bngc:services:1.0", name = "ConfigurationReference")
    public JAXBElement<ConfigurationReferenceType> createConfigurationReference(ConfigurationReferenceType value) {
        return new JAXBElement<ConfigurationReferenceType>(_ConfigurationReference_QNAME, ConfigurationReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfiguratorInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cisco:b2bngc:services:1.0", name = "ConfiguratorInformation")
    public JAXBElement<ConfiguratorInformationType> createConfiguratorInformation(ConfiguratorInformationType value) {
        return new JAXBElement<ConfiguratorInformationType>(_ConfiguratorInformation_QNAME, ConfiguratorInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PriceListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cisco:b2bngc:services:1.0", name = "PriceList")
    public JAXBElement<PriceListType> createPriceList(PriceListType value) {
        return new JAXBElement<PriceListType>(_PriceList_QNAME, PriceListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowQuoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ShowQuote")
    public JAXBElement<ShowQuoteType> createShowQuote(ShowQuoteType value) {
        return new JAXBElement<ShowQuoteType>(_ShowQuote_QNAME, ShowQuoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetQuoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "GetQuote")
    public JAXBElement<GetQuoteType> createGetQuote(GetQuoteType value) {
        return new JAXBElement<GetQuoteType>(_GetQuote_QNAME, GetQuoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Quote")
    public JAXBElement<QuoteType> createQuote(QuoteType value) {
        return new JAXBElement<QuoteType>(_Quote_QNAME, QuoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuoteHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "QuoteHeader")
    public JAXBElement<QuoteHeaderType> createQuoteHeader(QuoteHeaderType value) {
        return new JAXBElement<QuoteHeaderType>(_QuoteHeader_QNAME, QuoteHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuoteLineType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "QuoteLine")
    public JAXBElement<QuoteLineType> createQuoteLine(QuoteLineType value) {
        return new JAXBElement<QuoteLineType>(_QuoteLine_QNAME, QuoteLineType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualificationTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "QualificationTerm")
    public JAXBElement<QualificationTermType> createQualificationTerm(QualificationTermType value) {
        return new JAXBElement<QualificationTermType>(_QualificationTerm_QNAME, QualificationTermType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Address")
    public JAXBElement<AddressType> createAddress(AddressType value) {
        return new JAXBElement<AddressType>(_Address_QNAME, AddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllowanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Allowance")
    public JAXBElement<AllowanceType> createAllowance(AllowanceType value) {
        return new JAXBElement<AllowanceType>(_Allowance_QNAME, AllowanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerPartyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "BillToParty")
    public JAXBElement<CustomerPartyType> createBillToParty(CustomerPartyType value) {
        return new JAXBElement<CustomerPartyType>(_BillToParty_QNAME, CustomerPartyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Classification")
    public JAXBElement<ClassificationType> createClassification(ClassificationType value) {
        return new JAXBElement<ClassificationType>(_Classification_QNAME, ClassificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Contact")
    public JAXBElement<ContactType> createContact(ContactType value) {
        return new JAXBElement<ContactType>(_Contact_QNAME, ContactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Discount")
    public JAXBElement<TermType> createDiscount(TermType value) {
        return new JAXBElement<TermType>(_Discount_QNAME, TermType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "DocumentID")
    public JAXBElement<DocumentIDType> createDocumentID(DocumentIDType value) {
        return new JAXBElement<DocumentIDType>(_DocumentID_QNAME, DocumentIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EMailAddressCommunicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "EMailAddressCommunication")
    public JAXBElement<EMailAddressCommunicationType> createEMailAddressCommunication(EMailAddressCommunicationType value) {
        return new JAXBElement<EMailAddressCommunicationType>(_EMailAddressCommunication_QNAME, EMailAddressCommunicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimePeriodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "EffectiveTimePeriod")
    public JAXBElement<TimePeriodType> createEffectiveTimePeriod(TimePeriodType value) {
        return new JAXBElement<TimePeriodType>(_EffectiveTimePeriod_QNAME, TimePeriodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EffectivityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Effectivity")
    public JAXBElement<EffectivityType> createEffectivity(EffectivityType value) {
        return new JAXBElement<EffectivityType>(_Effectivity_QNAME, EffectivityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "FormattedNumber")
    public JAXBElement<TextType2> createFormattedNumber(TextType2 value) {
        return new JAXBElement<TextType2>(_FormattedNumber_QNAME, TextType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Item")
    public JAXBElement<ItemType> createItem(ItemType value) {
        return new JAXBElement<ItemType>(_Item_QNAME, ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ItemID")
    public JAXBElement<ItemIDType> createItemID(ItemIDType value) {
        return new JAXBElement<ItemIDType>(_ItemID_QNAME, ItemIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Location")
    public JAXBElement<LocationType> createLocation(LocationType value) {
        return new JAXBElement<LocationType>(_Location_QNAME, LocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Party")
    public JAXBElement<PartyType> createParty(PartyType value) {
        return new JAXBElement<PartyType>(_Party_QNAME, PartyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyIDsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "PartyIDs")
    public JAXBElement<PartyIDsType> createPartyIDs(PartyIDsType value) {
        return new JAXBElement<PartyIDsType>(_PartyIDs_QNAME, PartyIDsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaymentTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "PaymentTerm")
    public JAXBElement<PaymentTermType> createPaymentTerm(PaymentTermType value) {
        return new JAXBElement<PaymentTermType>(_PaymentTerm_QNAME, PaymentTermType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Property")
    public JAXBElement<PropertyType> createProperty(PropertyType value) {
        return new JAXBElement<PropertyType>(_Property_QNAME, PropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Specification")
    public JAXBElement<SpecificationType> createSpecification(SpecificationType value) {
        return new JAXBElement<SpecificationType>(_Specification_QNAME, SpecificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Status")
    public JAXBElement<StatusType> createStatus(StatusType value) {
        return new JAXBElement<StatusType>(_Status_QNAME, StatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelephoneCommunicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "TelephoneCommunication")
    public JAXBElement<TelephoneCommunicationType> createTelephoneCommunication(TelephoneCommunicationType value) {
        return new JAXBElement<TelephoneCommunicationType>(_TelephoneCommunication_QNAME, TelephoneCommunicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PriceABIEType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "UnitPrice")
    public JAXBElement<PriceABIEType> createUnitPrice(PriceABIEType value) {
        return new JAXBElement<PriceABIEType>(_UnitPrice_QNAME, PriceABIEType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ApplicationArea")
    public JAXBElement<ApplicationAreaType> createApplicationArea(ApplicationAreaType value) {
        return new JAXBElement<ApplicationAreaType>(_ApplicationArea_QNAME, ApplicationAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "BODID")
    public JAXBElement<IdentifierType2> createBODID(IdentifierType2 value) {
        return new JAXBElement<IdentifierType2>(_BODID_QNAME, IdentifierType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ChangeStatus")
    public JAXBElement<ChangeStatusType> createChangeStatus(ChangeStatusType value) {
        return new JAXBElement<ChangeStatusType>(_ChangeStatus_QNAME, ChangeStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ComponentID")
    public JAXBElement<IdentifierType2> createComponentID(IdentifierType2 value) {
        return new JAXBElement<IdentifierType2>(_ComponentID_QNAME, IdentifierType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "CreationDateTime")
    public JAXBElement<String> createCreationDateTime(String value) {
        return new JAXBElement<String>(_CreationDateTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpressionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Expression")
    public JAXBElement<ExpressionType> createExpression(ExpressionType value) {
        return new JAXBElement<ExpressionType>(_Expression_QNAME, ExpressionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Get")
    public JAXBElement<GetType> createGet(GetType value) {
        return new JAXBElement<GetType>(_Get_QNAME, GetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "LogicalID")
    public JAXBElement<IdentifierType2> createLogicalID(IdentifierType2 value) {
        return new JAXBElement<IdentifierType2>(_LogicalID_QNAME, IdentifierType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiverType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Receiver")
    public JAXBElement<ReceiverType> createReceiver(ReceiverType value) {
        return new JAXBElement<ReceiverType>(_Receiver_QNAME, ReceiverType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ReferenceID")
    public JAXBElement<IdentifierType2> createReferenceID(IdentifierType2 value) {
        return new JAXBElement<IdentifierType2>(_ReferenceID_QNAME, IdentifierType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseActionCriteriaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ResponseCriteria")
    public JAXBElement<ResponseActionCriteriaType> createResponseCriteria(ResponseActionCriteriaType value) {
        return new JAXBElement<ResponseActionCriteriaType>(_ResponseCriteria_QNAME, ResponseActionCriteriaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SenderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Sender")
    public JAXBElement<SenderType> createSender(SenderType value) {
        return new JAXBElement<SenderType>(_Sender_QNAME, SenderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Show")
    public JAXBElement<ShowType> createShow(ShowType value) {
        return new JAXBElement<ShowType>(_Show_QNAME, ShowType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Amount")
    public JAXBElement<AmountType2> createAmount(AmountType2 value) {
        return new JAXBElement<AmountType2>(_Amount_QNAME, AmountType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Text")
    public JAXBElement<TextType2> createText(TextType2 value) {
        return new JAXBElement<TextType2>(_Text_QNAME, TextType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "AuthorizationID")
    public JAXBElement<IdentifierType2> createAuthorizationID(IdentifierType2 value) {
        return new JAXBElement<IdentifierType2>(_AuthorizationID_QNAME, IdentifierType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "CityName")
    public JAXBElement<NameType2> createCityName(NameType2 value) {
        return new JAXBElement<NameType2>(_CityName_QNAME, NameType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Code")
    public JAXBElement<CodeType2> createCode(CodeType2 value) {
        return new JAXBElement<CodeType2>(_Code_QNAME, CodeType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountryCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "CountryCode")
    public JAXBElement<CountryCodeType> createCountryCode(CountryCodeType value) {
        return new JAXBElement<CountryCodeType>(_CountryCode_QNAME, CountryCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountrySubDivisionCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "CountrySubDivisionCode")
    public JAXBElement<CountrySubDivisionCodeType> createCountrySubDivisionCode(CountrySubDivisionCodeType value) {
        return new JAXBElement<CountrySubDivisionCodeType>(_CountrySubDivisionCode_QNAME, CountrySubDivisionCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Description")
    public JAXBElement<DescriptionType> createDescription(DescriptionType value) {
        return new JAXBElement<DescriptionType>(_Description_QNAME, DescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "DiscountPercent")
    public JAXBElement<BigDecimal> createDiscountPercent(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DiscountPercent_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "DocumentDateTime")
    public JAXBElement<String> createDocumentDateTime(String value) {
        return new JAXBElement<String>(_DocumentDateTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "EMailAddressID")
    public JAXBElement<IdentifierType2> createEMailAddressID(IdentifierType2 value) {
        return new JAXBElement<IdentifierType2>(_EMailAddressID_QNAME, IdentifierType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "EndDateTime")
    public JAXBElement<String> createEndDateTime(String value) {
        return new JAXBElement<String>(_EndDateTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ExtendedAmount")
    public JAXBElement<AmountType2> createExtendedAmount(AmountType2 value) {
        return new JAXBElement<AmountType2>(_ExtendedAmount_QNAME, AmountType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ID")
    public JAXBElement<IdentifierType2> createID(IdentifierType2 value) {
        return new JAXBElement<IdentifierType2>(_ID_QNAME, IdentifierType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "JobTitle")
    public JAXBElement<TextType2> createJobTitle(TextType2 value) {
        return new JAXBElement<TextType2>(_JobTitle_QNAME, TextType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "LastModificationDateTime")
    public JAXBElement<String> createLastModificationDateTime(String value) {
        return new JAXBElement<String>(_LastModificationDateTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "LineNumber")
    public JAXBElement<IdentifierType2> createLineNumber(IdentifierType2 value) {
        return new JAXBElement<IdentifierType2>(_LineNumber_QNAME, IdentifierType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SequencedTextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "AddressLine")
    public JAXBElement<SequencedTextType> createAddressLine(SequencedTextType value) {
        return new JAXBElement<SequencedTextType>(_AddressLine_QNAME, SequencedTextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "LineOne")
    public JAXBElement<TextType2> createLineOne(TextType2 value) {
        return new JAXBElement<TextType2>(_LineOne_QNAME, TextType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "LineThree")
    public JAXBElement<TextType2> createLineThree(TextType2 value) {
        return new JAXBElement<TextType2>(_LineThree_QNAME, TextType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "LineTwo")
    public JAXBElement<TextType2> createLineTwo(TextType2 value) {
        return new JAXBElement<TextType2>(_LineTwo_QNAME, TextType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Name")
    public JAXBElement<NameType2> createName(NameType2 value) {
        return new JAXBElement<NameType2>(_Name_QNAME, NameType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePairType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "NameValue")
    public JAXBElement<NameValuePairType> createNameValue(NameValuePairType value) {
        return new JAXBElement<NameValuePairType>(_NameValue_QNAME, NameValuePairType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "ParentID")
    public JAXBElement<IdentifierType2> createParentID(IdentifierType2 value) {
        return new JAXBElement<IdentifierType2>(_ParentID_QNAME, IdentifierType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "PostalCode")
    public JAXBElement<CodeType2> createPostalCode(CodeType2 value) {
        return new JAXBElement<CodeType2>(_PostalCode_QNAME, CodeType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantityType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Quantity")
    public JAXBElement<QuantityType2> createQuantity(QuantityType2 value) {
        return new JAXBElement<QuantityType2>(_Quantity_QNAME, QuantityType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SequencedTextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Reason")
    public JAXBElement<SequencedTextType> createReason(SequencedTextType value) {
        return new JAXBElement<SequencedTextType>(_Reason_QNAME, SequencedTextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "TotalAmount")
    public JAXBElement<AmountType2> createTotalAmount(AmountType2 value) {
        return new JAXBElement<AmountType2>(_TotalAmount_QNAME, AmountType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Type")
    public JAXBElement<CodeType2> createType(CodeType2 value) {
        return new JAXBElement<CodeType2>(_Type_QNAME, CodeType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "Extension")
    public JAXBElement<ExtensionType> createExtension(ExtensionType value) {
        return new JAXBElement<ExtensionType>(_Extension_QNAME, ExtensionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openapplications.org/oagis/9", name = "UserArea")
    public JAXBElement<UserAreaType> createUserArea(UserAreaType value) {
        return new JAXBElement<UserAreaType>(_UserArea_QNAME, UserAreaType.class, null, value);
    }

}
