//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.30 at 06:34:20 PM IST 
//


package com.tcl.dias.oms.cisco.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestLineType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.openapplications.org/oagis/9}StatusEnabledLineType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.openapplications.org/oagis/9}ItemInstanceGroup" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openapplications.org/oagis/9}UnitPrice" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openapplications.org/oagis/9}ExtendedAmount" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openapplications.org/oagis/9}TotalAmount" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestLineType", propOrder = {
    "item",
    "quantity",
    "unitPrice",
    "extendedAmount",
    "totalAmount"
})
@XmlSeeAlso({
    ProcurementLineType.class
})
public class RequestLineType
    extends StatusEnabledLineType
{

    @XmlElement(name = "Item")
    protected ItemType item;
    @XmlElement(name = "Quantity")
    protected QuantityType2 quantity;
    @XmlElement(name = "UnitPrice")
    protected PriceABIEType unitPrice;
    @XmlElement(name = "ExtendedAmount")
    protected AmountType2 extendedAmount;
    @XmlElement(name = "TotalAmount")
    protected AmountType2 totalAmount;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link ItemType }
     *     
     */
    public ItemType getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemType }
     *     
     */
    public void setItem(ItemType value) {
        this.item = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType2 }
     *     
     */
    public QuantityType2 getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType2 }
     *     
     */
    public void setQuantity(QuantityType2 value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link PriceABIEType }
     *     
     */
    public PriceABIEType getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceABIEType }
     *     
     */
    public void setUnitPrice(PriceABIEType value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the extendedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType2 }
     *     
     */
    public AmountType2 getExtendedAmount() {
        return extendedAmount;
    }

    /**
     * Sets the value of the extendedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType2 }
     *     
     */
    public void setExtendedAmount(AmountType2 value) {
        this.extendedAmount = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType2 }
     *     
     */
    public AmountType2 getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType2 }
     *     
     */
    public void setTotalAmount(AmountType2 value) {
        this.totalAmount = value;
    }

}
