//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.30 at 06:34:20 PM IST 
//


package com.tcl.dias.oms.cisco.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserAreaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserAreaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:cisco:b2bngc:services:1.0}CiscoExtensions" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserAreaType", propOrder = {
    "ciscoExtensions"
})
public class UserAreaType {

    @XmlElement(name = "CiscoExtensions", namespace = "urn:cisco:b2bngc:services:1.0")
    protected CiscoExtensionsType ciscoExtensions;

    /**
     * Gets the value of the ciscoExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link CiscoExtensionsType }
     *     
     */
    public CiscoExtensionsType getCiscoExtensions() {
        return ciscoExtensions;
    }

    /**
     * Sets the value of the ciscoExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CiscoExtensionsType }
     *     
     */
    public void setCiscoExtensions(CiscoExtensionsType value) {
        this.ciscoExtensions = value;
    }

}
