package com.tcl.dias.serviceactivation;

import org.json.JSONObject;
import org.json.XML;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import com.tcl.dias.serviceactivation.datamigration.DataMigrationGVPN;

/**
 * This class has test controllers for data migration methods in Data Migration
 * class
 * 
 * @author diksha garg
 * @link http://www.tatacommunications.com/
 * @copyright 2019 Tata Communications Limited
 */
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
public class DataMigrationGvpnTest {
	@Autowired
	DataMigrationGVPN dataMigration;

	/*
	 * @Autowired DataMigration2 dataMigration2;
	 */

	public String s() {
		StringBuilder s = new StringBuilder();
		s.append("<MDM_GVPN_Data>\r\n" + "   <OrderInfo>\r\n" + "      <orderId>1272287</orderId>\r\n"
				+ "      <serviceInstanceId>[1272287]</serviceInstanceId>\r\n"
				+ "      <orderType>CHANGE_ORDER</orderType>\r\n"
				+ "      <orderCategory>CUSTOMER_ORDER</orderCategory>\r\n"
				+ "      <orderStatus>CLOSED</orderStatus>\r\n"
				+ "      <SFDCOpportunityID>1583687</SFDCOpportunityID>\r\n"
				+ "      <serviceId>091PUNE623014142593</serviceId>\r\n" + "      <COPFID>417324</COPFID>\r\n"
				+ "      <LastMileType>WIRELESS</LastMileType>\r\n" + "      <LMProviderName>WIMAX</LMProviderName>\r\n"
				+ "      <programManagerName>SVAMEYA</programManagerName>\r\n" + "      <OriginatorDetails>\r\n"
				+ "         <originatorName>MIGRATION_USER</originatorName>\r\n"
				+ "         <originatedDate>2017-07-14 16:46:05</originatedDate>\r\n"
				+ "         <groupID>MIGRATION GROUP</groupID>\r\n" + "      </OriginatorDetails>\r\n"
				+ "      <customerInfo>\r\n" + "         <CRNID>VT000434</CRNID>\r\n"
				+ "         <customerName>TATA AIA LIFE INSURANCE COMPANY LIMITED</customerName>\r\n"
				+ "         <customerCategory>Enterprise</customerCategory>\r\n"
				+ "         <customerEmail>Manish.Halgekar@tataaia.com</customerEmail>\r\n"
				+ "         <customerAddress>\r\n"
				+ "            <addressLine1>Second Floor, Adinath Chamber, Swarget, Pune</addressLine1>\r\n"
				+ "            <location>Pune</location>\r\n" + "            <city>Pune</city>\r\n"
				+ "            <state>Maharashtra</state>\r\n" + "            <country>India</country>\r\n"
				+ "            <pincode>411045</pincode>\r\n" + "         </customerAddress>\r\n"
				+ "         <SAMCustomerDescription>TATA_AIA_LIFE_INSURANCE_COMPANY_LIMITED</SAMCustomerDescription>\r\n"
				+ "         <ALUCustomerID>100399</ALUCustomerID>\r\n" + "      </customerInfo>\r\n"
				+ "   </OrderInfo>\r\n" + "   <GVPNService>\r\n"
				+ "      <serviceInstanceId>1272287</serviceInstanceId>\r\n"
				+ "      <serviceType>GVPN</serviceType>\r\n" + "      <serviceSubType>GVPN</serviceSubType>\r\n"
				+ "      <componentType>VPN PORT</componentType>\r\n"
				+ "      <serviceId>091PUNE623014142593</serviceId>\r\n"
				+ "      <instanceVersion>3</instanceVersion>\r\n"
				+ "      <netpRefId>MIG_ALU_201707132542</netpRefId>\r\n"
				+ "      <serviceState>TERMINATED</serviceState>\r\n"
				+ "      <interfaceDescriptionServiceTag>GVPN</interfaceDescriptionServiceTag>\r\n"
				+ "      <isServiceInstanceLocked>Yes</isServiceInstanceLocked>\r\n" + "      <VRFDetails>\r\n"
				+ "         <isVRFLiteEnabled>false</isVRFLiteEnabled>\r\n" + "      </VRFDetails>\r\n"
				+ "      <vpnSolutionDetails>\r\n" + "         <VPNSolutionID>TATA_AIA_LIFE</VPNSolutionID>\r\n"
				+ "         <VPNLegID>144</VPNLegID>\r\n" + "         <VLANNumber>0</VLANNumber>\r\n"
				+ "         <VPNName>TATA_AIA_LIFE</VPNName>\r\n" + "         <attr2>FULL-MESH</attr2>\r\n"
				+ "      </vpnSolutionDetails>\r\n" + "      <VPNSolutionTableDetails>\r\n"
				+ "         <solutionID>TATA_AIA_LIFE</solutionID>\r\n" + "         <VPN>\r\n"
				+ "            <vpnID>TATA_AIA_LIFE</vpnID>\r\n"
				+ "            <vpnFriendlyName>TATA_AIA_LIFE</vpnFriendlyName>\r\n"
				+ "            <vpnType>CUSTOMER</vpnType>\r\n" + "            <topology>MESH</topology>\r\n"
				+ "            <leg>\r\n" + "               <legID>144</legID>\r\n"
				+ "               <legServiceID>091PUNE623014142593</legServiceID>\r\n"
				+ "               <role>FULL-MESH</role>\r\n" + "            </leg>\r\n" + "         </VPN>\r\n"
				+ "      </VPNSolutionTableDetails>\r\n" + "      <IPService>\r\n"
				+ "         <solutionID>TATA_AIA_LIFE</solutionID>\r\n" + "         <serviceBandwidth>\r\n"
				+ "            <bandwidthValue>512.0</bandwidthValue>\r\n"
				+ "            <bandwidthUnit>KBPS</bandwidthUnit>\r\n" + "         </serviceBandwidth>\r\n"
				+ "         <burstableBandwidth/>\r\n" + "         <redundancyRole>SINGLE</redundancyRole>\r\n"
				+ "         <managementType>UNMANAGED</managementType>\r\n"
				+ "         <triggerNCCMOrder>false</triggerNCCMOrder>\r\n"
				+ "         <isCustomConfigRequired>false</isCustomConfigRequired>\r\n"
				+ "         <manualPostValidation>false</manualPostValidation>\r\n"
				+ "         <pathIPType>IPV4 Stack</pathIPType>\r\n" + "         <pingAddress1>\r\n"
				+ "            <isCustomerOwned>false</isCustomerOwned>\r\n" + "         </pingAddress1>\r\n"
				+ "         <pingAddress2>\r\n" + "            <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "         </pingAddress2>\r\n" + "         <NMSServerIPv4Address>\r\n"
				+ "            <isCustomerOwned>false</isCustomerOwned>\r\n" + "         </NMSServerIPv4Address>\r\n"
				+ "         <WANv4IPAddress>\r\n" + "            <address>10.6.134.96/30</address>\r\n"
				+ "            <isCustomerOwned>false</isCustomerOwned>\r\n" + "         </WANv4IPAddress>\r\n"
				+ "         <WANIPv6Address>\r\n" + "            <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "         </WANIPv6Address>\r\n" + "         <LANIPv4Address>\r\n"
				+ "            <isManualInput>false</isManualInput>\r\n" + "            <LANIPAddress>\r\n"
				+ "               <isCustomerOwned>true</isCustomerOwned>\r\n" + "            </LANIPAddress>\r\n"
				+ "         </LANIPv4Address>\r\n" + "         <LANIPv6Address>\r\n"
				+ "            <isManualInput>false</isManualInput>\r\n" + "            <LANIPAddress>\r\n"
				+ "               <isCustomerOwned>true</isCustomerOwned>\r\n" + "            </LANIPAddress>\r\n"
				+ "         </LANIPv6Address>\r\n" + "         <ExtendedLAN>\r\n"
				+ "            <isEnabled>false</isEnabled>\r\n" + "         </ExtendedLAN>\r\n" + "         <QoS>\r\n"
				+ "            <COSType>6COS</COSType>\r\n" + "            <QoSProfile>PREMIUM</QoSProfile>\r\n"
				+ "            <isBandwidthApplicable>true</isBandwidthApplicable>\r\n" + "            <COS>\r\n"
				+ "               <CoSName>COS1</CoSName>\r\n" + "               <BandWidth/>\r\n"
				+ "               <ClassificationCriteria>\r\n" + "                  <qosACL>\r\n"
				+ "                     <name>COS1</name>\r\n" + "                     <isEnabled>false</isEnabled>\r\n"
				+ "                     <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                     <ACLEntry>\r\n" + "                        <seqNo>0</seqNo>\r\n"
				+ "                        <isSourceSubnetAny>false</isSourceSubnetAny>\r\n"
				+ "                        <destinationSubnetAny>false</destinationSubnetAny>\r\n"
				+ "                        <portNumber>0</portNumber>\r\n"
				+ "                        <sourcePortNumber>0</sourcePortNumber>\r\n"
				+ "                     </ACLEntry>\r\n" + "                  </qosACL>\r\n"
				+ "                  <dscpValueList/>\r\n" + "                  <ipPrecedentValueList/>\r\n"
				+ "                  <ANY>ANY</ANY>\r\n" + "               </ClassificationCriteria>\r\n"
				+ "            </COS>\r\n" + "            <COS>\r\n" + "               <CoSName>COS2</CoSName>\r\n"
				+ "               <BandWidth/>\r\n" + "               <ClassificationCriteria>\r\n"
				+ "                  <qosACL>\r\n" + "                     <name>COS2</name>\r\n"
				+ "                     <isEnabled>false</isEnabled>\r\n"
				+ "                     <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                     <ACLEntry>\r\n" + "                        <seqNo>0</seqNo>\r\n"
				+ "                        <isSourceSubnetAny>false</isSourceSubnetAny>\r\n"
				+ "                        <destinationSubnetAny>false</destinationSubnetAny>\r\n"
				+ "                        <portNumber>0</portNumber>\r\n"
				+ "                        <sourcePortNumber>0</sourcePortNumber>\r\n"
				+ "                     </ACLEntry>\r\n" + "                  </qosACL>\r\n"
				+ "                  <dscpValueList/>\r\n" + "                  <ipPrecedentValueList/>\r\n"
				+ "                  <ANY>ANY</ANY>\r\n" + "               </ClassificationCriteria>\r\n"
				+ "            </COS>\r\n" + "            <COS>\r\n" + "               <CoSName>COS3</CoSName>\r\n"
				+ "               <percentage>100</percentage>\r\n" + "               <BandWidth>\r\n"
				+ "                  <bandwidthValue>512000.0</bandwidthValue>\r\n"
				+ "                  <bandwidthUnit>BPS</bandwidthUnit>\r\n" + "               </BandWidth>\r\n"
				+ "               <ClassificationCriteria>\r\n"
				+ "                  <classificationCriteriaList>ANY</classificationCriteriaList>\r\n"
				+ "                  <qosACL>\r\n" + "                     <name>COS3</name>\r\n"
				+ "                     <isEnabled>false</isEnabled>\r\n"
				+ "                     <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  </qosACL>\r\n" + "                  <dscpValueList/>\r\n"
				+ "                  <ipPrecedentValueList/>\r\n" + "                  <ANY>ANY</ANY>\r\n"
				+ "               </ClassificationCriteria>\r\n" + "            </COS>\r\n" + "            <COS>\r\n"
				+ "               <CoSName>COS4</CoSName>\r\n" + "               <BandWidth/>\r\n"
				+ "               <ClassificationCriteria>\r\n" + "                  <qosACL>\r\n"
				+ "                     <name>COS4</name>\r\n" + "                     <isEnabled>false</isEnabled>\r\n"
				+ "                     <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                     <ACLEntry>\r\n" + "                        <seqNo>0</seqNo>\r\n"
				+ "                        <isSourceSubnetAny>false</isSourceSubnetAny>\r\n"
				+ "                        <destinationSubnetAny>false</destinationSubnetAny>\r\n"
				+ "                        <portNumber>0</portNumber>\r\n"
				+ "                        <sourcePortNumber>0</sourcePortNumber>\r\n"
				+ "                     </ACLEntry>\r\n" + "                  </qosACL>\r\n"
				+ "                  <dscpValueList/>\r\n" + "                  <ipPrecedentValueList/>\r\n"
				+ "                  <ANY>ANY</ANY>\r\n" + "               </ClassificationCriteria>\r\n"
				+ "            </COS>\r\n" + "            <COS>\r\n" + "               <CoSName>COS5</CoSName>\r\n"
				+ "               <BandWidth/>\r\n" + "               <ClassificationCriteria>\r\n"
				+ "                  <qosACL>\r\n" + "                     <name>COS5</name>\r\n"
				+ "                     <isEnabled>false</isEnabled>\r\n"
				+ "                     <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                     <ACLEntry>\r\n" + "                        <seqNo>0</seqNo>\r\n"
				+ "                        <isSourceSubnetAny>false</isSourceSubnetAny>\r\n"
				+ "                        <destinationSubnetAny>false</destinationSubnetAny>\r\n"
				+ "                        <portNumber>0</portNumber>\r\n"
				+ "                        <sourcePortNumber>0</sourcePortNumber>\r\n"
				+ "                     </ACLEntry>\r\n" + "                  </qosACL>\r\n"
				+ "                  <dscpValueList/>\r\n" + "                  <ipPrecedentValueList/>\r\n"
				+ "                  <ANY>ANY</ANY>\r\n" + "               </ClassificationCriteria>\r\n"
				+ "            </COS>\r\n" + "            <COS>\r\n" + "               <CoSName>COS6</CoSName>\r\n"
				+ "               <BandWidth/>\r\n" + "               <ClassificationCriteria>\r\n"
				+ "                  <qosACL>\r\n" + "                     <name>COS6</name>\r\n"
				+ "                     <isEnabled>false</isEnabled>\r\n"
				+ "                     <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                     <ACLEntry>\r\n" + "                        <seqNo>0</seqNo>\r\n"
				+ "                        <isSourceSubnetAny>false</isSourceSubnetAny>\r\n"
				+ "                        <destinationSubnetAny>false</destinationSubnetAny>\r\n"
				+ "                        <portNumber>0</portNumber>\r\n"
				+ "                        <sourcePortNumber>0</sourcePortNumber>\r\n"
				+ "                     </ACLEntry>\r\n" + "                  </qosACL>\r\n"
				+ "                  <dscpValueList/>\r\n" + "                  <ipPrecedentValueList/>\r\n"
				+ "                  <ANY>ANY</ANY>\r\n" + "               </ClassificationCriteria>\r\n"
				+ "            </COS>\r\n" + "            <IsFlexiCoS>false</IsFlexiCoS>\r\n"
				+ "            <QosTrafficMode>UNICAST</QosTrafficMode>\r\n" + "            <ALUSchedulerPolicy>\r\n"
				+ "               <Name>512Kbps</Name>\r\n"
				+ "               <isPreProvisioned>false</isPreProvisioned>\r\n"
				+ "               <totalPIRBandwidth>512</totalPIRBandwidth>\r\n"
				+ "               <totalCIRBandwidth>512</totalCIRBandwidth>\r\n"
				+ "            </ALUSchedulerPolicy>\r\n" + "            <SAPEgressPolicy>\r\n"
				+ "               <Name>Access Egress-30003</Name>\r\n"
				+ "               <isPreProvisioned>false</isPreProvisioned>\r\n" + "            </SAPEgressPolicy>\r\n"
				+ "            <SAPIngressPolicy>\r\n" + "               <Name>Access Ingress-30003</Name>\r\n"
				+ "               <isPreProvisioned>false</isPreProvisioned>\r\n"
				+ "            </SAPIngressPolicy>\r\n" + "         </QoS>\r\n" + "         <ServiceLink/>\r\n"
				+ "         <Router>\r\n" + "            <hostname>pu-man-ma02-hrt01</hostname>\r\n"
				+ "            <routerType>MPLS</routerType>\r\n" + "            <routerRole>PE</routerRole>\r\n"
				+ "            <routerMake>ALCATEL IP</routerMake>\r\n"
				+ "            <routerModel>ALU7750 SR-A8</routerModel>\r\n"
				+ "            <isBFDEnabled>false</isBFDEnabled>\r\n" + "            <WANInterface>\r\n"
				+ "               <WANInterface>ETHERNET</WANInterface>\r\n" + "               <ethernetInterface>\r\n"
				+ "                  <interfaceName>Lag 1:1001:3586</interfaceName>\r\n"
				+ "                  <physicalPort>Lag 1</physicalPort>\r\n" + "                  <IPv4Address>\r\n"
				+ "                     <address>10.6.134.97/30</address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv4Address>\r\n" + "                  <IPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv6Address>\r\n" + "                  <vlan>3586</vlan>\r\n"
				+ "                  <mode>ACCESS</mode>\r\n" + "                  <speed>NOT_APPLICABLE</speed>\r\n"
				+ "                  <secondaryIPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </secondaryIPv6Address>\r\n" + "                  <OuterVLAN>1001</OuterVLAN>\r\n"
				+ "                  <encapsulation>QnQ</encapsulation>\r\n" + "                  <BFD>\r\n"
				+ "                     <BFDTransmitinterval>false</BFDTransmitinterval>\r\n"
				+ "                     <BFDReceiveinterval>500</BFDReceiveinterval>\r\n"
				+ "                     <BFDMultiplier>500</BFDMultiplier>\r\n"
				+ "                     <isBFDEnabled>true</isBFDEnabled>\r\n" + "                  </BFD>\r\n"
				+ "               </ethernetInterface>\r\n" + "               <SerialInterface>\r\n"
				+ "                  <IPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv4Address>\r\n" + "                  <IPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv6Address>\r\n" + "                  <isFramed>false</isFramed>\r\n"
				+ "                  <CRCSize>0</CRCSize>\r\n"
				+ "                  <isCRC4Enabled>false</isCRC4Enabled>\r\n"
				+ "                  <secondaryIPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </secondaryIPv4Address>\r\n" + "                  <secondaryIPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </secondaryIPv6Address>\r\n" + "                  <HDLCConfig>\r\n"
				+ "                     <upCount>0</upCount>\r\n" + "                     <keepAlive>0</keepAlive>\r\n"
				+ "                     <downCount>0</downCount>\r\n" + "                  </HDLCConfig>\r\n"
				+ "                  <BFD>\r\n"
				+ "                     <BFDTransmitinterval>false</BFDTransmitinterval>\r\n"
				+ "                  </BFD>\r\n" + "               </SerialInterface>\r\n"
				+ "               <ChannelSDH>\r\n" + "                  <IPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv4Address>\r\n" + "                  <IPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv6Address>\r\n" + "                  <isFramed>false</isFramed>\r\n"
				+ "                  <secondaryIPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </secondaryIPv4Address>\r\n" + "                  <secondaryIPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </secondaryIPv6Address>\r\n" + "                  <BFD>\r\n"
				+ "                     <BFDTransmitinterval>false</BFDTransmitinterval>\r\n"
				+ "                  </BFD>\r\n" + "                  <HDLCConfig>\r\n"
				+ "                     <upCount>0</upCount>\r\n" + "                     <keepAlive>0</keepAlive>\r\n"
				+ "                     <downCount>0</downCount>\r\n" + "                  </HDLCConfig>\r\n"
				+ "               </ChannelSDH>\r\n" + "               <tunnelInterface>\r\n"
				+ "                  <IPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv4Address>\r\n" + "                  <IPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv6Address>\r\n" + "                  <tunnelSource>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </tunnelSource>\r\n" + "                  <tunnelDestination>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </tunnelDestination>\r\n" + "                  <ipMTU>0</ipMTU>\r\n"
				+ "               </tunnelInterface>\r\n" + "               <ISDN>\r\n"
				+ "                  <IPV4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPV4Address>\r\n" + "                  <IPV6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPV6Address>\r\n" + "                  <meritRadiusServerIP>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </meritRadiusServerIP>\r\n" + "                  <openRadiusServerIP>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </openRadiusServerIP>\r\n" + "                  <radiusServerIP>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </radiusServerIP>\r\n" + "                  <secondaryIPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </secondaryIPv4Address>\r\n" + "                  <secondaryIPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </secondaryIPv6Address>\r\n" + "               </ISDN>\r\n"
				+ "               <hsrpProtocol>\r\n" + "                  <enableHRSP>false</enableHRSP>\r\n"
				+ "               </hsrpProtocol>\r\n" + "               <InboundAccessControlList>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <ACLEntry>\r\n" + "                     <seqNo>0</seqNo>\r\n"
				+ "                     <isSourceSubnetAny>false</isSourceSubnetAny>\r\n"
				+ "                     <destinationSubnetAny>false</destinationSubnetAny>\r\n"
				+ "                     <portNumber>0</portNumber>\r\n"
				+ "                     <sourcePortNumber>0</sourcePortNumber>\r\n"
				+ "                  </ACLEntry>\r\n" + "               </InboundAccessControlList>\r\n"
				+ "               <outBoundAccessControlList>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <ACLEntry>\r\n" + "                     <seqNo>0</seqNo>\r\n"
				+ "                     <isSourceSubnetAny>false</isSourceSubnetAny>\r\n"
				+ "                     <destinationSubnetAny>false</destinationSubnetAny>\r\n"
				+ "                     <portNumber>0</portNumber>\r\n"
				+ "                     <sourcePortNumber>0</sourcePortNumber>\r\n"
				+ "                  </ACLEntry>\r\n" + "               </outBoundAccessControlList>\r\n"
				+ "               <inboundAccessControlListV6>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </inboundAccessControlListV6>\r\n"
				+ "               <outboundAccessControlListV6>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </outboundAccessControlListV6>\r\n" + "            </WANInterface>\r\n"
				+ "            <managementLoopbackInterface>\r\n" + "               <IPv4Address>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n" + "               </IPv4Address>\r\n"
				+ "               <IPv6Address>\r\n" + "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </IPv6Address>\r\n" + "            </managementLoopbackInterface>\r\n"
				+ "            <topologyInterface1>\r\n" + "               <IPv4Address>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n" + "               </IPv4Address>\r\n"
				+ "               <IPv6Address>\r\n" + "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </IPv6Address>\r\n" + "            </topologyInterface1>\r\n"
				+ "            <topologyInterface2>\r\n" + "               <IPv4Address>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n" + "               </IPv4Address>\r\n"
				+ "               <IPv6Address>\r\n" + "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </IPv6Address>\r\n" + "            </topologyInterface2>\r\n"
				+ "            <topologyInfo>\r\n"
				+ "               <topologyName>pu-man-kri-wi5-as01_b1</topologyName>\r\n"
				+ "               <uniSwitch>\r\n" + "                  <hostName>pu-man-kri-wi5-as01</hostName>\r\n"
				+ "                  <v4ManagementIPAddress>172.21.220.75</v4ManagementIPAddress>\r\n"
				+ "                  <uniInterface>\r\n"
				+ "                     <interfaceName>GigabitEthernet0/0/3</interfaceName>\r\n"
				+ "                     <physicalPort>GigabitEthernet0/0/3</physicalPort>\r\n"
				+ "                     <IPv4Address>\r\n"
				+ "                        <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                     </IPv4Address>\r\n" + "                     <IPv6Address>\r\n"
				+ "                        <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                     </IPv6Address>\r\n" + "                     <vlan>3586</vlan>\r\n"
				+ "                     <mode>TRUNK</mode>\r\n"
				+ "                     <speed>NOT_APPLICABLE</speed>\r\n"
				+ "                     <duplex>NOT_APPLICABLE</duplex>\r\n"
				+ "                     <autoNegotiationEnabled>NOT_APPLICABLE</autoNegotiationEnabled>\r\n"
				+ "                     <secondaryIPv4Address>\r\n"
				+ "                        <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                     </secondaryIPv4Address>\r\n" + "                     <secondaryIPv6Address>\r\n"
				+ "                        <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                     </secondaryIPv6Address>\r\n"
				+ "                     <OuterVLAN>1001</OuterVLAN>\r\n" + "                     <BFD>\r\n"
				+ "                        <BFDTransmitinterval>false</BFDTransmitinterval>\r\n"
				+ "                     </BFD>\r\n" + "                     <handOff>BS</handOff>\r\n"
				+ "                  </uniInterface>\r\n" + "               </uniSwitch>\r\n"
				+ "            </topologyInfo>\r\n" + "         </Router>\r\n" + "         <RoutingProtocol>\r\n"
				+ "            <routingProtocol>BGP</routingProtocol>\r\n" + "            <BGPRoutingProtocol>\r\n"
				+ "               <remoteASNumber>\r\n" + "                  <number>65239</number>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </remoteASNumber>\r\n" + "               <remoteUpdateSourceInterface>\r\n"
				+ "                  <IPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv4Address>\r\n" + "                  <IPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv6Address>\r\n" + "               </remoteUpdateSourceInterface>\r\n"
				+ "               <localASNumber>\r\n" + "                  <number>4755</number>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </localASNumber>\r\n" + "               <localUpdateSourceInterface>\r\n"
				+ "                  <IPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv4Address>\r\n" + "                  <IPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv6Address>\r\n" + "               </localUpdateSourceInterface>\r\n"
				+ "               <ASOverride>TRUE</ASOverride>\r\n"
				+ "               <isAuthReqd>false</isAuthReqd>\r\n"
				+ "               <isSOOReqd>false</isSOOReqd>\r\n"
				+ "               <maxPrefixThreshold>90</maxPrefixThreshold>\r\n"
				+ "               <isRedistributeConnectEnabled>false</isRedistributeConnectEnabled>\r\n"
				+ "               <isRedistributeStaticEnabled>false</isRedistributeStaticEnabled>\r\n"
				+ "               <helloTime>0</helloTime>\r\n" + "               <holdTime>90</holdTime>\r\n"
				+ "               <neighbourOn>WAN</neighbourOn>\r\n"
				+ "               <isOriginateDefaultEnabled>false</isOriginateDefaultEnabled>\r\n"
				+ "               <viewPassword>false</viewPassword>\r\n" + "               <remoteIPv4address>\r\n"
				+ "                  <address>10.6.134.98</address>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </remoteIPv4address>\r\n" + "               <remoteIPv6address>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </remoteIPv6address>\r\n" + "               <inboundBGPv4Prefixes>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <prefixListEntry>\r\n" + "                     <GEValue>0</GEValue>\r\n"
				+ "                     <LEValue>0</LEValue>\r\n" + "                  </prefixListEntry>\r\n"
				+ "               </inboundBGPv4Prefixes>\r\n" + "               <inboundBGPv6Prefixes>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <prefixListEntry>\r\n" + "                     <GEValue>0</GEValue>\r\n"
				+ "                     <LEValue>0</LEValue>\r\n" + "                  </prefixListEntry>\r\n"
				+ "               </inboundBGPv6Prefixes>\r\n" + "               <outboundBGPv4Prefixes>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <prefixListEntry>\r\n" + "                     <GEValue>0</GEValue>\r\n"
				+ "                     <LEValue>0</LEValue>\r\n" + "                  </prefixListEntry>\r\n"
				+ "               </outboundBGPv4Prefixes>\r\n" + "               <outboundBGPv6Prefixes>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <prefixListEntry>\r\n" + "                     <GEValue>0</GEValue>\r\n"
				+ "                     <LEValue>0</LEValue>\r\n" + "                  </prefixListEntry>\r\n"
				+ "               </outboundBGPv6Prefixes>\r\n" + "               <BGPInboundv4RouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </BGPInboundv4RouteMap>\r\n" + "               <BGPInboundv6RouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </BGPInboundv6RouteMap>\r\n"
				+ "               <isNeighbourShutdownRequired>false</isNeighbourShutdownRequired>\r\n"
				+ "               <BGPPeerGroupName>Tata_AIA_Life_Insura_100635_1</BGPPeerGroupName>\r\n"
				+ "               <ALUKeepAlive>30</ALUKeepAlive>\r\n"
				+ "               <ALUDisableBGPPeerGrpExtCommunity>TRUE</ALUDisableBGPPeerGrpExtCommunity>\r\n"
				+ "               <PEERType>external</PEERType>\r\n"
				+ "               <ALUBackupPath>NOT_APPLICABLE</ALUBackupPath>\r\n"
				+ "               <ALUDefaultOrginiateConfig>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <prefixListEntry>\r\n" + "                     <GEValue>0</GEValue>\r\n"
				+ "                     <LEValue>0</LEValue>\r\n" + "                  </prefixListEntry>\r\n"
				+ "               </ALUDefaultOrginiateConfig>\r\n" + "               <ALUDefaultOrginiateV6Config>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <prefixListEntry>\r\n" + "                     <GEValue>0</GEValue>\r\n"
				+ "                     <LEValue>0</LEValue>\r\n" + "                  </prefixListEntry>\r\n"
				+ "               </ALUDefaultOrginiateV6Config>\r\n"
				+ "               <BGPneigbourInboundRoutingPolicyv4>\r\n"
				+ "                  <enable>true</enable>\r\n"
				+ "                  <isPreprovisioned>true</isPreprovisioned>\r\n"
				+ "                  <name>IMPORT_EBGP_100635_1</name>\r\n" + "                  <matchCriteria/>\r\n"
				+ "                  <setCriteria/>\r\n" + "               </BGPneigbourInboundRoutingPolicyv4>\r\n"
				+ "               <BGPneigbourOutboundRoutingPolicyv4>\r\n"
				+ "                  <enable>true</enable>\r\n"
				+ "                  <isPreprovisioned>true</isPreprovisioned>\r\n"
				+ "                  <name>PE-CE_EXPORT</name>\r\n" + "                  <matchCriteria/>\r\n"
				+ "                  <setCriteria/>\r\n" + "               </BGPneigbourOutboundRoutingPolicyv4>\r\n"
				+ "               <BGPneigbourInboundRoutingPolicyv6>\r\n"
				+ "                  <enable>false</enable>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <matchCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <matchingCriteriaProtocol>false</matchingCriteriaProtocol>\r\n"
				+ "                     <matchingCriteriaPrefixlist>\r\n"
				+ "                        <isEnabled>false</isEnabled>\r\n"
				+ "                        <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                        <prefixListEntry>\r\n"
				+ "                           <GEValue>0</GEValue>\r\n"
				+ "                           <LEValue>0</LEValue>\r\n"
				+ "                        </prefixListEntry>\r\n"
				+ "                     </matchingCriteriaPrefixlist>\r\n"
				+ "                     <routingPolicyNeighbourCommunity/>\r\n"
				+ "                  </matchCriteria>\r\n" + "               </BGPneigbourInboundRoutingPolicyv6>\r\n"
				+ "               <BGPneigbourOutboundRoutingPolicyv6>\r\n"
				+ "                  <enable>false</enable>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <matchCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <matchingCriteriaProtocol>false</matchingCriteriaProtocol>\r\n"
				+ "                     <matchingCriteriaPrefixlist>\r\n"
				+ "                        <isEnabled>false</isEnabled>\r\n"
				+ "                        <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                        <prefixListEntry>\r\n"
				+ "                           <GEValue>0</GEValue>\r\n"
				+ "                           <LEValue>0</LEValue>\r\n"
				+ "                        </prefixListEntry>\r\n"
				+ "                     </matchingCriteriaPrefixlist>\r\n"
				+ "                     <routingPolicyNeighbourCommunity/>\r\n"
				+ "                  </matchCriteria>\r\n" + "                  <setCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <setCriteriaLocalPreference>false</setCriteriaLocalPreference>\r\n"
				+ "                     <metric>false</metric>\r\n"
				+ "                     <SetCriteriaASPathPrepend>false</SetCriteriaASPathPrepend>\r\n"
				+ "                     <routingPolicyNeighbourCommunity/>\r\n" + "                  </setCriteria>\r\n"
				+ "               </BGPneigbourOutboundRoutingPolicyv6>\r\n" + "            </BGPRoutingProtocol>\r\n"
				+ "            <StaticRoutingProtocol>\r\n" + "               <PEWANStaticRoutes>\r\n"
				+ "                  <IPSubnet>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPSubnet>\r\n" + "               </PEWANStaticRoutes>\r\n"
				+ "               <CEWANStaticRoutes>\r\n" + "                  <IPSubnet>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPSubnet>\r\n" + "               </CEWANStaticRoutes>\r\n"
				+ "               <redistributionRouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </redistributionRouteMap>\r\n" + "            </StaticRoutingProtocol>\r\n"
				+ "            <OSPFRoutingProtocol>\r\n"
				+ "               <ignoreIPOSPFMTU>false</ignoreIPOSPFMTU>\r\n"
				+ "               <isAuthReqd>false</isAuthReqd>\r\n"
				+ "               <isRedistributeConnectedEnabled>false</isRedistributeConnectedEnabled>\r\n"
				+ "               <isRedistributeStaticEnabled>false</isRedistributeStaticEnabled>\r\n"
				+ "               <OSPFCost>0</OSPFCost>\r\n" + "               <redistributionRouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </redistributionRouteMap>\r\n" + "               <shamlinkConfig>\r\n"
				+ "                  <enableShamlink>false</enableShamlink>\r\n"
				+ "               </shamlinkConfig>\r\n" + "               <ALUDefaultOrginiateConfig>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <prefixListEntry>\r\n" + "                     <GEValue>0</GEValue>\r\n"
				+ "                     <LEValue>0</LEValue>\r\n" + "                  </prefixListEntry>\r\n"
				+ "               </ALUDefaultOrginiateConfig>\r\n"
				+ "               <isNetworkP2p>false</isNetworkP2p>\r\n" + "            </OSPFRoutingProtocol>\r\n"
				+ "            <EIGRPRoutingProtocol>\r\n"
				+ "               <isRedistributeConnectedEnabled>false</isRedistributeConnectedEnabled>\r\n"
				+ "               <isRedistributeStaticEnabled>false</isRedistributeStaticEnabled>\r\n"
				+ "               <delay>0</delay>\r\n" + "               <reliablity>0</reliablity>\r\n"
				+ "               <load>0</load>\r\n" + "               <MTU>0</MTU>\r\n"
				+ "               <reDistributionDelay>0</reDistributionDelay>\r\n"
				+ "               <remoteCPEASNumber>0</remoteCPEASNumber>\r\n"
				+ "               <reDistributionRouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </reDistributionRouteMap>\r\n" + "            </EIGRPRoutingProtocol>\r\n"
				+ "            <RIPRoutingProtocol>\r\n" + "               <version>V2</version>\r\n"
				+ "               <isRedistributeConnectedEnabled>false</isRedistributeConnectedEnabled>\r\n"
				+ "               <isRedistributeStaticEnabled>false</isRedistributeStaticEnabled>\r\n"
				+ "               <redistributionRouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </redistributionRouteMap>\r\n" + "               <ALUDefaultOrginiateConfig>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <prefixListEntry>\r\n" + "                     <GEValue>0</GEValue>\r\n"
				+ "                     <LEValue>0</LEValue>\r\n" + "                  </prefixListEntry>\r\n"
				+ "               </ALUDefaultOrginiateConfig>\r\n" + "            </RIPRoutingProtocol>\r\n"
				+ "         </RoutingProtocol>\r\n" + "         <CSSSAMManagerId>100635</CSSSAMManagerId>\r\n"
				+ "         <ALUServiceName>TATA_AIA_LIFE</ALUServiceName>\r\n" + "      </IPService>\r\n"
				+ "      <cpeId>[1272287]</cpeId>\r\n" + "      <addOnServiceId>[1272287]</addOnServiceId>\r\n"
				+ "      <attr2>2018-12-11 20:01:15</attr2>\r\n" + "      <ALUVPRNImportPolicy>\r\n"
				+ "         <enable>false</enable>\r\n" + "         <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "         <matchCriteria>\r\n" + "            <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "            <regexASPath>false</regexASPath>\r\n"
				+ "            <matchingCriteriaProtocol>false</matchingCriteriaProtocol>\r\n"
				+ "            <matchingCriteriaPrefixlist>\r\n" + "               <isEnabled>false</isEnabled>\r\n"
				+ "               <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               <prefixListEntry>\r\n" + "                  <GEValue>0</GEValue>\r\n"
				+ "                  <LEValue>0</LEValue>\r\n" + "               </prefixListEntry>\r\n"
				+ "            </matchingCriteriaPrefixlist>\r\n" + "         </matchCriteria>\r\n"
				+ "         <setCriteria>\r\n" + "            <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "            <setCriteriaLocalPreference>false</setCriteriaLocalPreference>\r\n"
				+ "            <metric>false</metric>\r\n"
				+ "            <SetCriteriaASPathPrepend>false</SetCriteriaASPathPrepend>\r\n"
				+ "         </setCriteria>\r\n" + "      </ALUVPRNImportPolicy>\r\n" + "      <ALUVPRNExportPolicy>\r\n"
				+ "         <enable>false</enable>\r\n" + "         <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "         <matchCriteria>\r\n" + "            <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "            <regexASPath>false</regexASPath>\r\n"
				+ "            <matchingCriteriaProtocol>false</matchingCriteriaProtocol>\r\n"
				+ "            <matchingCriteriaPrefixlist>\r\n" + "               <isEnabled>false</isEnabled>\r\n"
				+ "               <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               <prefixListEntry>\r\n" + "                  <GEValue>0</GEValue>\r\n"
				+ "                  <LEValue>0</LEValue>\r\n" + "               </prefixListEntry>\r\n"
				+ "            </matchingCriteriaPrefixlist>\r\n" + "         </matchCriteria>\r\n"
				+ "         <setCriteria>\r\n" + "            <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "            <regexASPath>false</regexASPath>\r\n"
				+ "            <setCriteriaLocalPreference>false</setCriteriaLocalPreference>\r\n"
				+ "            <metric>false</metric>\r\n"
				+ "            <SetCriteriaASPathPrepend>false</SetCriteriaASPathPrepend>\r\n"
				+ "            <routingPolicyNeighbourCommunity/>\r\n" + "         </setCriteria>\r\n"
				+ "      </ALUVPRNExportPolicy>\r\n" + "   </GVPNService>\r\n" + "   <CPE>\r\n"
				+ "      <cpeId>1272287</cpeId>\r\n" + "      <loopbackInterface>\r\n" + "         <IPv4Address>\r\n"
				+ "            <isCustomerOwned>false</isCustomerOwned>\r\n" + "         </IPv4Address>\r\n"
				+ "         <IPv6Address>\r\n" + "            <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "         </IPv6Address>\r\n" + "      </loopbackInterface>\r\n"
				+ "      <managementIPv4LoopbackInterface>\r\n" + "         <IPv4Address>\r\n"
				+ "            <isCustomerOwned>false</isCustomerOwned>\r\n" + "         </IPv4Address>\r\n"
				+ "         <IPv6Address>\r\n" + "            <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "         </IPv6Address>\r\n" + "      </managementIPv4LoopbackInterface>\r\n"
				+ "      <isCPE_ACEConfigurable>false</isCPE_ACEConfigurable>\r\n"
				+ "      <discoverCPE>false</discoverCPE>\r\n" + "      <WANInterface>\r\n"
				+ "         <WANInterface>ETHERNET</WANInterface>\r\n" + "         <ethernetInterface>\r\n"
				+ "            <IPv4Address>\r\n" + "               <address>10.6.134.98/30</address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n" + "            </IPv4Address>\r\n"
				+ "            <IPv6Address>\r\n" + "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </IPv6Address>\r\n" + "            <vlan>0</vlan>\r\n"
				+ "            <mode>NOT_APPLICABLE</mode>\r\n" + "            <secondaryIPv6Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </secondaryIPv6Address>\r\n" + "         </ethernetInterface>\r\n"
				+ "         <SerialInterface>\r\n" + "            <IPv4Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n" + "            </IPv4Address>\r\n"
				+ "            <IPv6Address>\r\n" + "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </IPv6Address>\r\n" + "            <isFramed>false</isFramed>\r\n"
				+ "            <CRCSize>0</CRCSize>\r\n" + "            <isCRC4Enabled>false</isCRC4Enabled>\r\n"
				+ "            <secondaryIPv4Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </secondaryIPv4Address>\r\n" + "            <secondaryIPv6Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </secondaryIPv6Address>\r\n" + "         </SerialInterface>\r\n"
				+ "         <ChannelSDH>\r\n" + "            <IPv4Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n" + "            </IPv4Address>\r\n"
				+ "            <IPv6Address>\r\n" + "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </IPv6Address>\r\n" + "            <isFramed>false</isFramed>\r\n"
				+ "            <secondaryIPv4Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </secondaryIPv4Address>\r\n" + "            <secondaryIPv6Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </secondaryIPv6Address>\r\n" + "         </ChannelSDH>\r\n"
				+ "         <tunnelInterface>\r\n" + "            <IPv4Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n" + "            </IPv4Address>\r\n"
				+ "            <IPv6Address>\r\n" + "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </IPv6Address>\r\n" + "            <tunnelSource>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n" + "            </tunnelSource>\r\n"
				+ "            <tunnelDestination>\r\n" + "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </tunnelDestination>\r\n" + "            <ipMTU>0</ipMTU>\r\n"
				+ "         </tunnelInterface>\r\n" + "         <ISDN>\r\n" + "            <IPV4Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n" + "            </IPV4Address>\r\n"
				+ "            <IPV6Address>\r\n" + "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </IPV6Address>\r\n" + "            <meritRadiusServerIP>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </meritRadiusServerIP>\r\n" + "            <openRadiusServerIP>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </openRadiusServerIP>\r\n" + "            <radiusServerIP>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n" + "            </radiusServerIP>\r\n"
				+ "            <secondaryIPv4Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </secondaryIPv4Address>\r\n" + "            <secondaryIPv6Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </secondaryIPv6Address>\r\n" + "         </ISDN>\r\n" + "         <hsrpProtocol>\r\n"
				+ "            <enableHRSP>false</enableHRSP>\r\n" + "         </hsrpProtocol>\r\n"
				+ "         <InboundAccessControlList>\r\n" + "            <isEnabled>false</isEnabled>\r\n"
				+ "            <isPreprovisioned>false</isPreprovisioned>\r\n" + "            <ACLEntry>\r\n"
				+ "               <seqNo>0</seqNo>\r\n"
				+ "               <isSourceSubnetAny>false</isSourceSubnetAny>\r\n"
				+ "               <destinationSubnetAny>false</destinationSubnetAny>\r\n"
				+ "               <portNumber>0</portNumber>\r\n"
				+ "               <sourcePortNumber>0</sourcePortNumber>\r\n" + "            </ACLEntry>\r\n"
				+ "         </InboundAccessControlList>\r\n" + "         <outBoundAccessControlList>\r\n"
				+ "            <isEnabled>false</isEnabled>\r\n"
				+ "            <isPreprovisioned>false</isPreprovisioned>\r\n" + "            <ACLEntry>\r\n"
				+ "               <seqNo>0</seqNo>\r\n"
				+ "               <isSourceSubnetAny>false</isSourceSubnetAny>\r\n"
				+ "               <destinationSubnetAny>false</destinationSubnetAny>\r\n"
				+ "               <portNumber>0</portNumber>\r\n"
				+ "               <sourcePortNumber>0</sourcePortNumber>\r\n" + "            </ACLEntry>\r\n"
				+ "         </outBoundAccessControlList>\r\n" + "      </WANInterface>\r\n" + "      <LANInterface>\r\n"
				+ "         <ethernet>\r\n" + "            <IPv4Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n" + "            </IPv4Address>\r\n"
				+ "            <IPv6Address>\r\n" + "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </IPv6Address>\r\n" + "            <vlan>0</vlan>\r\n"
				+ "            <mode>NOT_APPLICABLE</mode>\r\n" + "            <secondaryIPv4Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </secondaryIPv4Address>\r\n" + "            <secondaryIPv6Address>\r\n"
				+ "               <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "            </secondaryIPv6Address>\r\n" + "            <OuterVLAN>0</OuterVLAN>\r\n"
				+ "            <BFD>\r\n" + "               <BFDTransmitinterval>false</BFDTransmitinterval>\r\n"
				+ "            </BFD>\r\n" + "         </ethernet>\r\n" + "         <HSRPProtocol>\r\n"
				+ "            <enableHRSP>false</enableHRSP>\r\n" + "         </HSRPProtocol>\r\n"
				+ "         <LANRoutingProtocol>\r\n" + "            <BGPRoutingProtocol>\r\n"
				+ "               <remoteASNumber>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </remoteASNumber>\r\n" + "               <remoteUpdateSourceInterface>\r\n"
				+ "                  <IPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv4Address>\r\n" + "                  <IPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv6Address>\r\n" + "               </remoteUpdateSourceInterface>\r\n"
				+ "               <localASNumber>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </localASNumber>\r\n" + "               <localUpdateSourceInterface>\r\n"
				+ "                  <IPv4Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv4Address>\r\n" + "                  <IPv6Address>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPv6Address>\r\n" + "               </localUpdateSourceInterface>\r\n"
				+ "               <isAuthReqd>false</isAuthReqd>\r\n"
				+ "               <isSOOReqd>false</isSOOReqd>\r\n"
				+ "               <isRedistributeConnectEnabled>false</isRedistributeConnectEnabled>\r\n"
				+ "               <isRedistributeStaticEnabled>false</isRedistributeStaticEnabled>\r\n"
				+ "               <helloTime>0</helloTime>\r\n"
				+ "               <isOriginateDefaultEnabled>false</isOriginateDefaultEnabled>\r\n"
				+ "               <viewPassword>false</viewPassword>\r\n" + "               <remoteIPv4address>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </remoteIPv4address>\r\n" + "               <remoteIPv6address>\r\n"
				+ "                  <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "               </remoteIPv6address>\r\n" + "               <inboundBGPv4Prefixes>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </inboundBGPv4Prefixes>\r\n" + "               <inboundBGPv6Prefixes>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </inboundBGPv6Prefixes>\r\n" + "               <outboundBGPv4Prefixes>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </outboundBGPv4Prefixes>\r\n" + "               <outboundBGPv6Prefixes>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </outboundBGPv6Prefixes>\r\n" + "               <BGPInboundv4RouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </BGPInboundv4RouteMap>\r\n" + "               <BGPInboundv6RouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </BGPInboundv6RouteMap>\r\n"
				+ "               <isNeighbourShutdownRequired>false</isNeighbourShutdownRequired>\r\n"
				+ "               <ALUDefaultOrginiateConfig>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </ALUDefaultOrginiateConfig>\r\n" + "               <ALUDefaultOrginiateV6Config>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </ALUDefaultOrginiateV6Config>\r\n"
				+ "               <BGPneigbourInboundRoutingPolicyv4>\r\n"
				+ "                  <enable>false</enable>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <matchCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <matchingCriteriaProtocol>false</matchingCriteriaProtocol>\r\n"
				+ "                     <matchingCriteriaPrefixlist>\r\n"
				+ "                        <isEnabled>false</isEnabled>\r\n"
				+ "                        <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                     </matchingCriteriaPrefixlist>\r\n" + "                  </matchCriteria>\r\n"
				+ "                  <setCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <setCriteriaLocalPreference>false</setCriteriaLocalPreference>\r\n"
				+ "                     <metric>false</metric>\r\n"
				+ "                     <SetCriteriaASPathPrepend>false</SetCriteriaASPathPrepend>\r\n"
				+ "                  </setCriteria>\r\n" + "               </BGPneigbourInboundRoutingPolicyv4>\r\n"
				+ "               <BGPneigbourOutboundRoutingPolicyv4>\r\n"
				+ "                  <enable>false</enable>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <matchCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <matchingCriteriaProtocol>false</matchingCriteriaProtocol>\r\n"
				+ "                     <matchingCriteriaPrefixlist>\r\n"
				+ "                        <isEnabled>false</isEnabled>\r\n"
				+ "                        <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                     </matchingCriteriaPrefixlist>\r\n" + "                  </matchCriteria>\r\n"
				+ "                  <setCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <setCriteriaLocalPreference>false</setCriteriaLocalPreference>\r\n"
				+ "                     <metric>false</metric>\r\n"
				+ "                     <SetCriteriaASPathPrepend>false</SetCriteriaASPathPrepend>\r\n"
				+ "                  </setCriteria>\r\n" + "               </BGPneigbourOutboundRoutingPolicyv4>\r\n"
				+ "               <BGPneigbourInboundRoutingPolicyv6>\r\n"
				+ "                  <enable>false</enable>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <matchCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <matchingCriteriaProtocol>false</matchingCriteriaProtocol>\r\n"
				+ "                     <matchingCriteriaPrefixlist>\r\n"
				+ "                        <isEnabled>false</isEnabled>\r\n"
				+ "                        <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                     </matchingCriteriaPrefixlist>\r\n" + "                  </matchCriteria>\r\n"
				+ "                  <setCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <setCriteriaLocalPreference>false</setCriteriaLocalPreference>\r\n"
				+ "                     <metric>false</metric>\r\n"
				+ "                     <SetCriteriaASPathPrepend>false</SetCriteriaASPathPrepend>\r\n"
				+ "                  </setCriteria>\r\n" + "               </BGPneigbourInboundRoutingPolicyv6>\r\n"
				+ "               <BGPneigbourOutboundRoutingPolicyv6>\r\n"
				+ "                  <enable>false</enable>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                  <matchCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <matchingCriteriaProtocol>false</matchingCriteriaProtocol>\r\n"
				+ "                     <matchingCriteriaPrefixlist>\r\n"
				+ "                        <isEnabled>false</isEnabled>\r\n"
				+ "                        <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "                     </matchingCriteriaPrefixlist>\r\n" + "                  </matchCriteria>\r\n"
				+ "                  <setCriteria>\r\n"
				+ "                     <neighbourCommunity>false</neighbourCommunity>\r\n"
				+ "                     <regexASPath>false</regexASPath>\r\n"
				+ "                     <setCriteriaLocalPreference>false</setCriteriaLocalPreference>\r\n"
				+ "                     <metric>false</metric>\r\n"
				+ "                     <SetCriteriaASPathPrepend>false</SetCriteriaASPathPrepend>\r\n"
				+ "                  </setCriteria>\r\n" + "               </BGPneigbourOutboundRoutingPolicyv6>\r\n"
				+ "            </BGPRoutingProtocol>\r\n" + "            <StaticRoutingProtocol>\r\n"
				+ "               <PEWANStaticRoutes>\r\n" + "                  <IPSubnet>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPSubnet>\r\n" + "               </PEWANStaticRoutes>\r\n"
				+ "               <CEWANStaticRoutes>\r\n" + "                  <IPSubnet>\r\n"
				+ "                     <isCustomerOwned>false</isCustomerOwned>\r\n"
				+ "                  </IPSubnet>\r\n" + "               </CEWANStaticRoutes>\r\n"
				+ "               <redistributionRouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </redistributionRouteMap>\r\n" + "            </StaticRoutingProtocol>\r\n"
				+ "            <OSPFRoutingProtocol>\r\n"
				+ "               <ignoreIPOSPFMTU>false</ignoreIPOSPFMTU>\r\n"
				+ "               <isAuthReqd>false</isAuthReqd>\r\n"
				+ "               <isRedistributeConnectedEnabled>false</isRedistributeConnectedEnabled>\r\n"
				+ "               <isRedistributeStaticEnabled>false</isRedistributeStaticEnabled>\r\n"
				+ "               <OSPFCost>0</OSPFCost>\r\n" + "               <redistributionRouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </redistributionRouteMap>\r\n" + "               <shamlinkConfig>\r\n"
				+ "                  <enableShamlink>false</enableShamlink>\r\n"
				+ "               </shamlinkConfig>\r\n" + "               <ALUDefaultOrginiateConfig>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </ALUDefaultOrginiateConfig>\r\n"
				+ "               <isNetworkP2p>false</isNetworkP2p>\r\n" + "            </OSPFRoutingProtocol>\r\n"
				+ "            <EIGRPRoutingProtocol>\r\n"
				+ "               <isRedistributeConnectedEnabled>false</isRedistributeConnectedEnabled>\r\n"
				+ "               <isRedistributeStaticEnabled>false</isRedistributeStaticEnabled>\r\n"
				+ "               <delay>0</delay>\r\n" + "               <reliablity>0</reliablity>\r\n"
				+ "               <load>0</load>\r\n" + "               <MTU>0</MTU>\r\n"
				+ "               <reDistributionDelay>0</reDistributionDelay>\r\n"
				+ "               <remoteCPEASNumber>0</remoteCPEASNumber>\r\n"
				+ "               <reDistributionRouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </reDistributionRouteMap>\r\n" + "            </EIGRPRoutingProtocol>\r\n"
				+ "            <RIPRoutingProtocol>\r\n"
				+ "               <isRedistributeConnectedEnabled>false</isRedistributeConnectedEnabled>\r\n"
				+ "               <isRedistributeStaticEnabled>false</isRedistributeStaticEnabled>\r\n"
				+ "               <redistributionRouteMap>\r\n"
				+ "                  <isRouteMapEnabled>false</isRouteMapEnabled>\r\n"
				+ "                  <isRouteMapPreprovisioned>false</isRouteMapPreprovisioned>\r\n"
				+ "               </redistributionRouteMap>\r\n" + "               <ALUDefaultOrginiateConfig>\r\n"
				+ "                  <isEnabled>false</isEnabled>\r\n"
				+ "                  <isPreprovisioned>false</isPreprovisioned>\r\n"
				+ "               </ALUDefaultOrginiateConfig>\r\n" + "            </RIPRoutingProtocol>\r\n"
				+ "         </LANRoutingProtocol>\r\n" + "         <inboundAccessControlList>\r\n"
				+ "            <isEnabled>false</isEnabled>\r\n"
				+ "            <isPreprovisioned>false</isPreprovisioned>\r\n" + "            <ACLEntry/>\r\n"
				+ "         </inboundAccessControlList>\r\n" + "         <outboundAccessControlList>\r\n"
				+ "            <isEnabled>false</isEnabled>\r\n"
				+ "            <isPreprovisioned>false</isPreprovisioned>\r\n" + "            <ACLEntry/>\r\n"
				+ "         </outboundAccessControlList>\r\n" + "         <secondaryIPv4Address>\r\n"
				+ "            <isCustomerOwned>false</isCustomerOwned>\r\n" + "         </secondaryIPv4Address>\r\n"
				+ "      </LANInterface>\r\n" + "      <CPEInitConfigParam>\r\n"
				+ "         <sendInitTemplate>false</sendInitTemplate>\r\n"
				+ "         <isCPEShared>false</isCPEShared>\r\n" + "      </CPEInitConfigParam>\r\n" + "   </CPE>\r\n"
				+ "   <AddOnServiceDetails>\r\n" + "      <addOnServiceId>1272287</addOnServiceId>\r\n"
				+ "      <aceGVPNAddOnServicesIsEnabled>\r\n"
				+ "         <isExchangeNattingEnabled>false</isExchangeNattingEnabled>\r\n"
				+ "         <isTelePreseneceEnabled>false</isTelePreseneceEnabled>\r\n"
				+ "         <isITIMSEnabled>false</isITIMSEnabled>\r\n"
				+ "         <isMultiCastEnabled>false</isMultiCastEnabled>\r\n"
				+ "         <isNNICPEConfigEnabled>false</isNNICPEConfigEnabled>\r\n"
				+ "         <isVSATCPEConfigEnabled>false</isVSATCPEConfigEnabled>\r\n"
				+ "      </aceGVPNAddOnServicesIsEnabled>\r\n" + "   </AddOnServiceDetails>\r\n" + "</MDM_GVPN_Data>");
		return s.toString();

	}

	/**
	 * Test method for migrateGVPN in Data Migration
	 * 
	 * @author diksha garg
	 * @throws Exception
	 */
	@Test
	public void testMigrateGVPN() throws Exception {

		JSONObject obj = XML.toJSONObject(s());
		String response;
		response = dataMigration.migrateGVPN(obj,
				obj.getJSONObject("MDM_GVPN_Data").getJSONObject("GVPNService").get("serviceId").toString(),null,null,null);
		System.out.println(response);

	}
}
