
package com.tcl.dias.serviceactivation.cramer.checkclrinfo.beans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckClrStatus", targetNamespace = "http://com.tatacommunications.cramer.ace.service.ws.checkclrstatus")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckClrStatus {


    /**
     * 
     * @param relationshipType
     * @param requestId
     * @param objectName
     * @param objectType
     * @param requestingSystem
     * @return
     *     returns com.tcl.dias.networkinventoryclient.cramer.checkclrinfo.beans.OrderInfo
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "checkClrInfo", targetNamespace = "http://com.tatacommunications.cramer.ace.service.ws.checkclrstatus", className = "com.tcl.dias.networkinventoryclient.cramer.checkclrinfo.beans.CheckClrInfo")
    @ResponseWrapper(localName = "checkClrInfoResponse", targetNamespace = "http://com.tatacommunications.cramer.ace.service.ws.checkclrstatus", className = "com.tcl.dias.networkinventoryclient.cramer.checkclrinfo.beans.CheckClrInfoResponse")
    public OrderInfo checkClrInfo(
        @WebParam(name = "objectType", targetNamespace = "")
        ObjectType objectType,
        @WebParam(name = "objectName", targetNamespace = "")
        String objectName,
        @WebParam(name = "relationshipType", targetNamespace = "")
        RelationShip relationshipType,
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "requestingSystem", targetNamespace = "")
        String requestingSystem)
        throws SOAPException_Exception
    ;

}
